- funcx/executors/high_throughput/funcx_manager.py
- funcx/sdk/client.py
Adds support for tagging container info to the task header.
> Coupling functions with containers #5

- funcx/executors/high_throughput/funcx_manager.py
- funcx/executors/high_throughput/worker_map.py
The PR
1. Changes the worker launch cmd to `shell=False`
2. Adds a `worker_procs` list at the manager and kills the worker procs at exit
> add worker_procs to manager and kill all worker procs at exit

- funcx/endpoint/endpoint.py
This extends the funcx-endpoint cli's start command with an optional endpoint_uuid.
> Allow users to specify endpoint uuid on start

- funcx/sdk/client.py
- funcx/sdk/utils/throttling.py
- funcx/tests/test_throttling.py
@ryanchard Let me know how well this matches up to what you 
envisioned! It seemed the most straight forward to hook into the
`_request` call in the BaseClient. 
These changes restrict the number of requests a user can make to
1/second in a 5 second period, and the size of a given request
body for a POST request to 2MB (Both of these restrictions are
hard to reach). It's also easy to disable both of these if they
somehow interfer and a user really wants to disable them:
funcx_cli.throttling_enabled = False
> Added request throttling to the SDK

- funcx/sdk/client.py
Adding a method to register containers. This was removed by accident earlier in July 2019.
> Adding container registration back

- requirements.txt
Updates to 3.2.0. Endpoints still work in testing and this meets DLHub requirements.
> Updating to 3.2.0

- funcx/sdk/client.py
- funcx/sdk/utils/batch.py
Uses tuples rather than lists and works with /submit instead of /batch_run.
> Updates routes to send tuples, not lists.

- requirements.txt
funcx does not work gracefully with parsl 1.0. before we update, we should fix the requirement to `parsl==0.9.0`
> set parsl version to 0.9 for funcx for now

- funcx/executors/high_throughput/global_config.py
Updates the default ~/.funcx/config.py to use Parsl's address_by_hostname() as the default endpoint address. This replaces the current default "localhost", which does not work for managers that are deployed on a different machine than the endpoint.
> Sets address by hostname as the default

- README.rst
Super basic -- I just noticed this link was broken when first searching for the docs
> Fix docs badge broken link

- funcx/executors/high_throughput/interchange_task_dispatch.py
The soft scheduling mode has two loops when deciding the tasks to send to a manager. Prior to this PR, a task from the first loop is not appended to the second loop, causing the task lost during soft scheduling.
> fix a losing task problem in soft scheduling mode

- funcx/sdk/utils/throttling.py
Modifies the throttling client to set the default max request size to 5Mb.
> Increases limit to 5Mb

- funcx/executors/high_throughput/interchange_task_dispatch.py
PR #190 mistakenly introduced some extra characters. This PR removes those characters.
> remove some extra characters (typos) from a previous PR on interchange task dispatching

- funcx/sdk/client.py
- funcx/version.py
Addresses the client side checking of versions per https://github.com/funcx-faas/funcX/issues/197.  The `FuncXClient` checks its `funcx.VERSION` against the `min_ep_version` returned by the web service.
Web service PR [here](https://github.com/funcx-faas/funcx-web-service/pull/182) should be merged first.
> More version checking

- README.rst
- funcx/executors/high_throughput/executor.py
- funcx/sdk/client.py
Endpoint status used to be sent in a specific message.  It's now bundled in with the task statuses.  Just moved the code for inserting into db to the place where the new message type is handled.
> Fix ep status

- funcx/config.py
- funcx/endpoint/endpoint.py
- funcx/executors/high_throughput/default_config.py
In response to https://github.com/funcx-faas/funcX/issues/170.  Places a field in the default endpoint config for `funcx_service_address`.  This is then passed to the FuncXClient when starting the endpoint.
> Configurable service address

- funcx_endpoint/funcx/endpoint/endpoint.py
- funcx_endpoint/funcx/executors/high_throughput/default_config.py
- funcx_sdk/funcx/utils/config.py
This is exactly the same set of changes made by Theodore in #177. 
This allows the user to set the service address via updating `~/.funcx/ENDPOINT_NAME/config.py`
TODO for later: 
`funcx/funcx_sdk/funcx/utils/config.py` needs to be moved to funcx_endpoint.
> Redoing theodore's changes in PR #177 into dev.

- funcx_endpoint/funcx_endpoint/endpoint/version.py
- funcx_endpoint/funcx_endpoint/providers/kubernetes/kube.py
- helm/README.md
- helm/funcx_endpoint/.helmignore
- helm/funcx_endpoint/Chart.yaml
- helm/funcx_endpoint/templates/NOTES.txt
- helm/funcx_endpoint/templates/_helpers.tpl
- helm/funcx_endpoint/templates/endpoint-config.yaml
- helm/funcx_endpoint/templates/endpoint-deployment.yaml
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
- helm/funcx_endpoint/templates/role.yaml
- helm/funcx_endpoint/templates/rolebinding.yaml
- helm/funcx_endpoint/templates/service_account.yaml
- helm/funcx_endpoint/values.yaml
Want to be able to deploy a configurable and workable kubernetes endpoint on any cluster
Create a helm chart that deploys:
1. Endpoint Kubernetes deployment
2. A global config
3. An endpoint config
4. Service Account with role bindings to create pods
Added a parameter to the KubernetesProvider to obtain Kubernetes config from in-cluster. This is the default
now for this provider, but they can optionally be picked up from a mounted .kube file.
The default values for the chart try to put the launched worker pods in the `default` namespace. This may not work
with your kubernetes account, so minimally, you will need a `values.yaml` file that sets:
```
workerNamespace: servicex
```
> Helm Chart for Kubernetes Endpoint

- funcx_sdk/funcx/sdk/client.py
change `'False'` to `False`
return `completion_t` as part of the status dict on `update_table` in sdk
> add `completion_t` to `update_table` status dict and change "False" status from a string to boolean

- funcx_sdk/funcx/sdk/client.py
Adds authorizers for Search and OpenID to the client's init function. This allows other codes to pass through authorizers and skip doing a second authentication flow if permissions have already been granted.
> Fixes #210

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Currently some modules for funcx-manager do not log to `manager.log` because of the rearch. This fixes the issue.
> fix funcx-manager logger name after separating to funcx_endpoint and funcx repos

- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_sdk/funcx/utils/loggers.py
This PR adds new options for users to limit the log size for interchange.log and manager.log. Fixes #271
> Add RotateFileHandler for interchange.log and manager.log to limit the log size

- funcx_endpoint/funcx_endpoint/__init__.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/strategies/kube_simple.py
- funcx_endpoint/requirements.txt
There is a race condition within the Helm deployment where the endpoint attempts to connect to the web service. If that service is not yet up, the endpoint will silently fail.
Fixes #280 
Added a retry around the `register_endpoint` function
Also, debugging this was difficult with the noisy _Task breakdown_ messages. Demoted this log message to _debug_
> Retry Endpoint Registration

- helm/funcx_endpoint/values.yaml
The workerInit in the endpoint values.yaml installs the wrong library so the endpoint code is not available
Change the workerInit to pip install funcx-endpoint>=0.0.3
> Update workerInit to pull in the new split out endpoint library

- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
The interchange always logs to a file. This means that for Kubernetes endpoints, the output doesn't show up in the Kubectl logs. There is also far too many info log messages to see what is going on.
Solution to #289  
1. Added a new option to the config: `interchange_file_logger` - the default is True which keeps the file logging behavior
2. The helm chart will set this to False to have logging sent to the pod's log
3. Based on this setting, `start_file_logger` will create a `RotatingFileHandler` or a `StreamHandler`
4. Changed some of the interchange log statements to _debug_ instead of _info_
5. Supressed the Heartbeat messages, the "Sending status report to forwarder", and zero items in batch messages
This PR depends on code submitted to #285 
Deploy an endpoint using this helm chart. …
> Allow interchange logger to report to pod log

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
The Kubernetes endpoint writes the daemon's logs to files in the .funcx directory. This is inconvenient for Kubernetes admins since they don't show up in `Kubectl log` command output. You have to create a bash shell into the pod and tail the file.
Solution to Issue #285 
The endpoint cli launches an endpoint as a daemon. In kubernetes it is considered an anti-pattern to have multiple detached processes running in a pod. This is why other attempts have failed.
There is an option to `daemon.DaemonContext` to tell it to not detach the daemon process. Added a new config setting to the endpoint to say whether this should be set to True or False. Updated the config created by the helm chart to set this to False.
During development of this it was clear that there needs to be more flexibility in …
> Endpoint Logging for Kubernetes 

- funcx_endpoint/funcx_endpoint/__init__.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
After this [commit](https://github.com/funcx-faas/funcX/pull/175/commits/6aea93a4625312833471325ab4cb28ad6074ca38) and this [commit](https://github.com/funcx-faas/funcX/pull/175/commits/e56aeaec73eb6d9388ebc6310e50f15f9ffa5cf4) in PR #175 , the message format between forwarder and interchange is changed.
This PR fixes the inconsistency for the exception message.
Fixes #278
> Fix exception message format from interchange

- funcx_endpoint/funcx_endpoint/__init__.py
- funcx_sdk/funcx/sdk/client.py
We (this is my fault, oops.) were checking for various globus failures by doing the following:
```
if r.get("status", "Failure") == "Failure":
raise MalformedResponse("FuncX Request failed: {}".format(r.get("reason", "Unknown")))
```
Globus actually returns the status code "Failed".
> Replace checks for "failure" with checks for "Failed"

- funcx_endpoint/funcx_endpoint/strategies/kube_simple.py
- funcx_endpoint/funcx_endpoint/tests/strategies/test_kube_simple.py
The Kubernetes strategy is complicated and needs to consider a number of different scenarios. 
Added unit tests to exercise all of the cases for this class. With the confidence that unit tests bring, clean up the 
class by removing redundant branches and rename variables to make the mapping to Kubernetes resources obvious
> Add Units Tests to Kubernetes Strategy

- funcx_endpoint/funcx_endpoint/providers/kubernetes/kube.py
- funcx_endpoint/funcx_endpoint/strategies/kube_simple.py
The strategy should allow users to set `min_blocks` to greater than 0, so they can keep at least one container of each type during execution. The more reasonable assertion should be `init_blocks == 0`, because we don't know which pod/container to scale for initialization.
> remove assert min_pods == 0 in strategy for k8s provider

- funcx_endpoint/funcx_endpoint/executors/high_throughput/container_sched.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/worker_map.py
This PR improves multiple logging lines and fixes a typo of the bracket. 
It also fixes multiple bugs relevant to `task_status_delta`.
1. `task_status_delta` could be empty after it is sent to the interchange---`del` may raise keyError in this case.
2. `task_status_delta` includes reports of killer tasks, which would also be reported to interchange.
> Improve multiple log line descriptions and fix multiple small bugs and typos

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
This is meant to fix: https://github.com/funcx-faas/funcX/issues/251
My idea here is that there should be an initial endpoint registration attempt before the daemon is started. If this initial registration fails, the `funcx-endpoint start` fails, and no daemon is started. This is also useful because rather than having the stdout and stderr of this registration vanishing to the daemon's output files, it gets printed for the user when running the `start` command.
So, for example, trying this:
```
funcx-endpoint start --endpoint-uuid abc test
```
would result in:
A couple things I'm still thinking about:
- I got rid of the previous use of `retry`, because I think it is better to manually run a retry loop in the case where the daemon is running on its own. In this case, it is obviously better …
> Better exceptions at endpoint when registering

- funcx_sdk/funcx/sdk/client.py
This addresses the sdk side of [#195](https://github.com/funcx-faas/funcx-web-service/issues/195) by allowing client id and scope to be overridden via environment variables.
> Adding configurable client ids and scopes to sdk

- funcx_sdk/funcx/tests/conftest.py
Tiny fix, I noticed the default CLI arg needs to be in an array
> pytest default cli arg needs to be an array

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/utils/errors.py
Fixes: https://github.com/funcx-faas/funcX/issues/329
It looks like there was a fix on `main` that just didn't get put on this branch, although the message from just this is still a bit misleading (I think `MalformedResponse` was meant to imply that the user's request was malformed, but its confusing and seems more like it is implying the response from the service was malformed):
I think a new error class would be more fitting and informative. Here is with my added changes:
Edit: If we want more specific error names for these cases like `InvalidEndpoint`, we would need more specific error messages from the service that contain some sort of error code, which I think would be overkill for now at least
> Better exceptions when task sent to bad endpoint

- funcx_sdk/funcx/tests/README.rst
- funcx_sdk/funcx/tests/conftest.py
Making the pytest suite a little more useable with a `--service-address` arg.
> Add service address CLI arg and an example

- funcx_sdk/test-requirements.txt
Not sure why there is a `funcx` requirement in `funcx_sdk/test-requirements.txt`. Removing that.
Note this PR is merging to `forwarder_rearch_1` branch, rather than `main`
> remove funcx from test-requirements in forwarder_rearch_1 branch

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
This PR adds an import line to the endpoint module. Previously, the retry module was used in the endpoint module before it is imported. This raised the following traceback:
```
(funcx_py3.6) yadu@borgmachine:~/src/funcx$ funcx-endpoint list
File "/home/yadu/anaconda3/envs/funcx_py3.6/bin/funcx-endpoint", line 5, in <module>
from funcx_endpoint.endpoint.endpoint import cli_run
File "/home/yadu/anaconda3/envs/funcx_py3.6/lib/python3.6/site-packages/funcx_endpoint/endpoint/endpoint.py", line 309, in <module>
@retry(delay=10, max_delay=300, backoff=1.2, logger=logging.getLogger('funcx'))
NameError: name 'retry' is not defined
```
> Adding missing retry import

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/test-requirements.txt
- funcx_sdk/funcx/sdk/search.py
- funcx_sdk/test-requirements.txt
Fixes #373  by clearing out unused dependencies in the test-requirements files
Also fixed the flake8 errors that are preventing a clean build
> 373 remove tornado

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
Fixes a bad merge where the code still called `handle_start_registration` instead of using the `endpoint_register` method which now blocks even if the remote side cannot be reached.
> Replacing broken call to handle_start_registration

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
The issue was reported as Issue #369: after starting an endpoint, the `endpoint_id` in `endpoint.json` and the `Endpoint id` in `HighThroughputExecutor/interchange.log` are different. This is due to the fact that when an executor is constructed, if the variable `endpoint_id` is not given, a random string will be assigned to executor's member variable.
To fix the issue, when an executor are constructed in `interchange.py`, we assign the interchange's `endpoint_id`, which is also the endpoint's `endpoint_id`, to the executor.
To test the fix, we created a new unit test, and checked after an interchange's construction, if its `endpoint_id` is consistent with its executors' `endpoint_id`.
> Fixed endpoint_id consistency in interchange.log and endpoint.json

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/error_handling_client.py
- funcx_sdk/funcx/tests/test_errors/test_invalid_endpoint.py
- funcx_sdk/funcx/tests/test_errors/test_invalid_function.py
- funcx_sdk/funcx/utils/handle_service_response.py
- funcx_sdk/funcx/utils/response_errors.py
This PR goes along with: https://github.com/funcx-faas/funcx-web-service/pull/204
The idea here is that all response-related errors that the web service might have can live on the funcx sdk side. Each error type will have:
- A unique identifier `code`
- An error reason string `reason`
- An `error_args` value that is an array of args passed into the exception
When a request to the funcx web service comes back with an error message such as this:
```python
{'status': 'Failed',
'code': 2,
'error_args': ["uuid-1234"],
'reason': 'Function uuid-1234 could not be resolved'}
```
the error handler will know to throw the error with code 2 (`FunctionNotFound` for example), and it will know which arguments to pass into the exception, because the service provided them.
If for some reason an error code …
> Refactor service response errors

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/tests/test_batch.py
- funcx_sdk/funcx/tests/test_performance/test_performance.py
Current `main` and some funcx tests are broken because:
1. The new `Task` object format is not used consistently on funcx-manager. See issue #377 
2. The API `get_batch_status` is renamed to `get_batch_result` on sdk.
This PR fixes the issues by using `Task` in the correct way and correcting the naming of `get_batch_status` API in tests.
Fixes #377
> Use new Task object consistently on funcx-manager and fix batch tests after merging to main

- funcx_endpoint/tests/integration/test_per_func_batch.py
- funcx_sdk/funcx/sdk/client.py
It looks like the `get_batch_result` method unintentionally got swapped with another name. Unless we wanted `get_batch_status` instead?
> fix get_batch_result naming

- funcx_sdk/funcx/sdk/error_handling_client.py
- funcx_sdk/funcx/utils/response_errors.py
I would like the `http_status_code` in the packed json error, and also we need to be more lenient on what status code is allowed through in order to accept 207.
> Modify http status code error handling

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
Fixes: https://github.com/funcx-faas/funcX/issues/383
Moved endpoint registration logging outside of the daemon process. I'm not exactly sure what purpose it serves to keep retrying endpoint registration, especially without first informing the user.
There used to be a `while True` loop around the daemon code, meaning if the interchange were to terminate, endpoint registration would happen again and the interchange would start again. However, this loop has since been removed. I believe this is because `EndpointInterchange.start` is designed to never terminate, and this would also mean endpoint registration would only ever happen when the daemon starts up. Does this sound correct?
> Fix endpoint registration logging

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
This PR contains only the version bump.
> Updating to funcx==0.0.6a2 and funcx-endpoint==0.0.6a4

- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/requirements.txt
- funcx_sdk/funcx/sdk/version.py
- funcx_sdk/requirements.txt
Fixes issue described in #393. This PR also updates the version strings for funcx and funcx-endpoint to `0.0.6a5`.
> Updating pyzmq version string to >= 22.0.0

- funcx_sdk/funcx/serialize/concretes.py
Serializing methods in the main context is done by reference in pickle
which doesn't work in a remote context. This fault is difficult to detect
without having a clean process to attempt deserialization.
> Dill prioritized over pickle for code serialization.

- docs/changelog.rst
- docs/endpoints.rst
- funcx_endpoint/funcx_endpoint/endpoint/default_config.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
- funcx_sdk/funcx/sdk/client.py
> Updating funcx-service-address to https://api2.funcx.org/v2

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
For Issue #432
After the fix, when we try to start a non-configured endpoint `test-ep`:
```
$ funcx-endpoint start test-ep
Endpoint test-ep is not configured!
1. Please create a configuration template with:
funcx-endpoint configure test-ep
2. Update the configuration
3. Start the endpoint
```
> Added notification message and exception for starting a non-configured endpoint

- README.rst
- docs/quickstart.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
Updates the version numbers for funcx, funcx-endpoint and the docs.
We still need to update the changelog with info on recent fixes.
> Updating the version number to 0.2.2

- funcx_endpoint/requirements.txt
Updating `funcx-endpoint` to require `funcx>=0.2.2`
> Updating version requirement to match funcx sdk

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
When a task is associated with a container, the current main is routed based on `container_id`, which does not work. A task should be routed based on `local_container` instead.
This PR fixes this error.
> Fix container routing from manager to worker

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Currently, if we execute `funcx-endpoint start endpoint_name` from a directory, a new directory `HighThroughputExecutor` would be created in the present directory, which includes `worker_logs`, i.e, `HighThroughputExecutor/worker_logs/...`. The behavior is automatic, and the user cannot change it.
After the change, user can use `run_dir` in the config to specify the directory of worker log. If the `run_dir` does not appear in the config file, the logs will be automatically put within the `~/.funcx` under proper endpoint name directory. i.e.,
- If the user has `run_dir='/tmp'` in the config, the log would appear at `/tmp/HighThroughputExecutor/worker_logs`
- If the user does not have `run_dir` in the config, the log would appear at …
> Made worker_logs appeared at correct location within .funcx dir

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/worker_map.py
- funcx_endpoint/tests/integration/test_config.py
Current path joining:
Using direct string concatenation with linux/mac convention: `{}/{}`
After the PR change:
Using python universal path joining tool: `os.path.join()`
> Changed path joining to using os.path.join()

- funcx_endpoint/funcx_endpoint/endpoint/config.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
This is mostly documentation changes and removal of obsolete options. Please note that I am renaming the `Config.working_dir` to `Config.log_dir` for internal consistency.
Fixes #453
> Cleanup obsolete config opts

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
This PR makes updates EndpointManager init interface and the way loggers are handled.
* The EndpointManager init now takes all the info it needs at init, rather than being injected separately.
* The loggers in the `endpoint.py` and `endpoint_manager.py` are named `endpoint` to keep those logs separate from the EndpointInterchange.
* Loggers are now simple globals rather than being accessed from inside the EndpointManager object
> Refactor endpoint manager

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
There's a redundant call to `EndpointManager.init_endpoint_dir` that creates an endpoint dir instead of leaving that responsibility to the `EndpointManager.configure_endpoint` step that follows. This currently has the `funcx-endpoint configure [<optional_endpoint_name>]` command fail with the `ConfigExists` exception due to the duplicate attempt to create the same dir.
This PR removes this redundant call.
> Removing the redundant configure step in init_endpoint

- Dockerfile-endpoint
- helm/README.md
- helm/boot.sh
- helm/funcx_endpoint/templates/endpoint-deployment.yaml
- helm/funcx_endpoint/values.yaml
Redeploying a kubernetes endpoint causes the endpoint ID to be randomly generated, breaking existing code
Solution to #429 
Move the extremely long and awkward command for starting the endpoint to a script, `boot.sh` - this script takes two arguments:
* The endpoint name
* An optional endpoint id
If endpointID is provided then the endpoint script is run with the `--endpoint-uuid` option.
Added a new value to the helm chart `endpointUUID` - if a value is provided, that is the uuid passed into the script. If the value is empty or omitted then the endpoint generates a new uuid
> Accept an existing endpoint UUID in helm chart

- docs/configs/kube.py
- docs/configs/midway.py
- docs/configs/theta.py
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
- helm/funcx_endpoint/values.yaml
In PR #457 , we removed some old config options like `working_dir` and `scaling_enabled`. They need to be removed from docs and helm too.
> Remove old config options from docs and helm chart config

- funcx_endpoint/funcx_endpoint/providers/kubernetes/kube.py
Since  Kubernetes provider doesn't really know which pods by container to initialize, so best to set init_blocks to 0
fix #237
> Set k8r provider init_block default to 0

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/mac_safe_queue.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
Tested successfully with the following procedure
1. `funcx-endpoint start` on mac, which generated a uuid
2. Executed a function from a laptop with the uuid
We noticed with `conda 4.10.0` it works for `python=3.7`. But for `conda=4.10.0,python=3.8` and `conda=4.10.0,python=3.9`, `funcx-endpoint start pytest` would give error message
```
$ /Users/willr/miniconda3/envs/funcx-mac38/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
> mac fix for htex

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
This is to fix a small issue in #462 , where the killer task status is reported in task delta from manager to interchange.
> Don't put killer task status in task delta message from manager

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/tests/funcx_endpoint/executors/high_throughput/test_funcx_manager.py
Issue: The worker killer task does not use `class Task` as other tasks. Need to make it consistent.
After the PR:
The worker killer task is encoded to `Task` type before being put onto the task queue.
Note:
- `logger = logging.getLogger("funcx_manager")` was added to the top of `funcx_manager.py`. It does not change any behavior of the application, because `funcx-manager` is invoked only through the `cli_run()` of the module, and `logger` is re-set in `cli_run` via `set_file_logger` to its desired setting.
- The reason for adding this is for the correctness of the unit test. `logger` was originally declared in `cli_run` of `funcx_manager.py`, and used in the module thoroughly. When we initiates `Manager` in unit test by `manager = Manager()`, `Manager`'s constructor calls `logger`, but it …
> Made worker killer tasks have consistent type

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/serialize/concretes.py
- funcx_sdk/funcx/serialize/facade.py
- funcx_sdk/funcx/serialize/off_process_checker.py
- funcx_sdk/funcx/tests/test_fn_serialization.py
- funcx_sdk/funcx/tests/test_param_serialization.py
- funcx_sdk/setup.py
This change adds:
* off_process_checker.py: A subprocess'ed server that attempts
deserialization in a clean isolated env and reports success/fail
* Updates to concretes.py to prioritize source based fn serialization
methods that are cross-python-version reliable
* Updates to facade.py to launch the off_process_checker as a subprocess
and send it fn's over a socket protected with a mutex. The checker will
print the port it's listening to on a file.
* Adding off_process_checker as an installed script to setup.py
Needs testing code that I'm in the process of cleaning up to add onto this branch.
> Adding an isolated function deserialization checking mechanism.

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/zmq_pipes.py
- funcx_endpoint/funcx_endpoint/mock_broker/forwarder.py
- funcx_endpoint/tests/integration/test_executor.py
- funcx_endpoint/tests/integration/test_executor_passthrough.py
- funcx_endpoint/tests/integration/test_status.py
- funcx_sdk/funcx/__init__.py
- funcx_sdk/funcx/utils/loggers.py
Before the PR:
`start_file_logger()` were defined separately in two files, which had the same functionality as `set_file_logger()`
In the PR:
Replaced `start_file_logger()` by `set_file_logger()`, and cleaned up the `loggers.py` module
> Cleaned up for log modularization

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
As Issue #488 described, `funcx-endpoint restart` cli did not work properly, because when its call to the `EndpointManager` lacks two (2) parameters. This PR fixes the issue.
> Fixed endpoint restart cli

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
As reported in #496, the typer autocomplete function relied on a non-existent manager context to come up with autocomplete responses. This PR sets the default funcx_dir to `<USERHOME/.funcx` and the autocomplete methods now work.
Now, when you press tab on the endpoint string in `funcx-endpoint start test_`, you get this:
```
(funcx_py3.7) yadu@borgmachine:/tmp/funcx$ funcx-endpoint start test_
backup             default            test_1             test_10            test_2             test_3             test_4             testing_local_dev  ws_test_1          
(funcx_py3.7) yadu@borgmachine:/tmp/funcx$ funcx-endpoint start test_10
(funcx_py3.7) yadu@borgmachine:/tmp/funcx$ funcx-endpoint stop def
backup             default            test_1             test_10 
```
Fixes #496 
Choose …
> Fix typer autocomplete in funcx-endpoint

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/utils/errors.py
Adds a new exception class `TaskPending` when a blocking call to `client.get_result()` is made for a task that is pending.
Fixes #489 
I need to add a test for this.
> Adding a new exception class TaskPending

- README.rst
- docs/changelog.rst
- docs/quickstart.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/requirements.txt
- funcx_sdk/funcx/sdk/version.py
This PR bumps the versions to `funcx==0.2.3` and `funcx-endpoint==0.2.3`.
To keep `funcx-endpoint` in sync, it now requires `funcx>=0.2.3`.
> Point release v0.2.3

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_sdk/funcx/tests/test_result_size.py
Please refer to #494. This PR adds a result size limit of 10MB. The worker will raise a `MaxResultSizeExceeded` exception
when it finds an object that exceeds this limit. Test included. Here's a snippet of the exception message that is now produced:
```
Task_id:  15735a5b-3e22-4cfa-bc0f-46cd3853e9cf
Got exception  Task result of 2833101B exceeded current limit of 1048576B
File "test_result_size.py", line 53, in <module>
test_large_result(fxc, endpoint, 2**21)
File "test_result_size.py", line 35, in test_large_result
r = fxc.get_result(task_id)
File "/home/yadu/anaconda3/envs/funcx_py3.7/lib/python3.7/site-packages/funcx/sdk/client.py", line 258, in get_result
task['exception'].reraise()
File "/home/yadu/anaconda3/envs/funcx_py3.7/lib/python3.7/site-packag …
```
> Enforce a limit of result size on the worker side

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
This PR fixes the endpoint status report, which was disabled in funcx-endpoint 0.2.X.
fix #444 
> Enable endpoint status report to send to forwarder

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
As described in Issue#486, when manager has an incompatible version with the interchange, it triggers
```
Exception in thread Thread-3:
File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/funcx_endpoint/executors/high_throughput/executor.py", line 525, in _queue_management_worker
self._executor_exception, _ = fx_serializer.deserialize(msg['exception'])
TypeError: cannot unpack non-iterable ManagerLost object
```
This PR fixes the issue.
> Fixed exception handling for python version mismatch

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
When you restart your computer and an endpoint is still running, the process will die but the `daemon.pid` file associated with it will remain. This fix allows `funcx-endpoint start` to better detect this issue, and it allows `funcx-endpoint stop` to clean up this broken scenario. `funcx-endpoint list` will now list this broken scenario as 'Inactive'.
`funcx-endpoint start` will clean up the broken `daemon.pid` file if it is broken, then start as usual:
There have also been minor improvements to how `funcx-endpoint delete` works and logs.
Fixes https://github.com/funcx-faas/funcX/issues/327
(Documentation will still need updating to indicate how `funcx-endpoint` is expected to …
> pidfile check improvements for endpoint: start, list, stop, delete

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/tests/funcx_endpoint/executors/high_throughput/test_funcx_manager.py
From the unit test of PR#462, we noticed the funcx-manager needs to be refactored to avoid code duplication and manual zmq handling. This PR refactored the funcx-manager by wrapping the functionalities of polling funcx task socket and sending task to workers. The unit test from PR#462 is also updated.
> Refactored funcx-manager, and updated unit test

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
As discussed on Slack, endpoint states should be renamed for more clarity, now that disconnected state has been added
Fixes https://github.com/funcx-faas/funcX/issues/524
> rename endpoint states to running, stopped, disconnected

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/tests/test_executor.py
Async interface doesn't currently allow setting a `results_ws_uri` due to how we set it up. We should let users set the `results_ws_uri` like this:
```
fxc = FuncXClient(funcx_service_address=service_url, asynchronous=True, results_ws_uri='wss://api.dev.funcx.org/ws/v2/')
```
And if using executor you need to swap to this:
```
fx = FuncXExecutor(FuncXClient(funcx_service_address=service_url, results_ws_uri='wss://api.dev.funcx.org/ws/v2/'))
```
Fixes #516
(Breaking change only from the recent ws API additions)
> Add small 404 error handling and move results_ws_uri option to client

- funcx_endpoint/requirements.txt
- funcx_sdk/parsl/app/errors.py
- funcx_sdk/requirements.txt
- funcx_sdk/setup.py
Running the SDK on AWS Lambda fails due to some incompatible dependencies deep inside parsl. We only the `RemoteExceptionWrapper` class from parsl. 
Fixes #528 
The endpoint will send a `parsl.app.errors.RemoteExceptionWrapper` If there is an exception in the worker. To avoid having to deploy a breaking change to the endpoint, we will install a matching class along with the SDK, without bringing in parsl
> Make a parsl.app.errors module that gets installed with SDK to avoid parsl dependency

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
Switch to correct websockets call. Followup from https://github.com/funcx-faas/funcX/pull/527 since it seems the pre commit changes were merged incorrectly.
> switch to correct websockets connect call

- LICENSE
This PR adds an Apache2 license file to the top-level of this repo. We have the same in `funcx/funcx_sdk` and `funcx/funcx_endpoint` covering the code, but it's clearer to have the license file here.
Fixes #537 
> Adding Apache2 license to top-level

- .isort.cfg
- .pre-commit-config.yaml
- docs/configs/bluewaters.py
- docs/configs/cori.py
- docs/configs/frontera.py
- docs/configs/kube.py
- docs/configs/midway.py
- docs/configs/perlmutter.py
- docs/configs/theta.py
- docs/configs/uchicago_ai_cluster.py
- funcx_sdk/funcx/tests/test_result_size.py
- funcx_sdk/setup.cfg
As found by @Loonride in #535, there's something wrong with the `isort` config. I've never seen this before, and I'm not sure what exactly is happening, but I do have a fix that should work.
Without this change, `isort` behavior could change on a branch unexpectedly. We aren't fully sure of the reason for this, but we can enforce a specific config so that the behavior cannot change.
- Explicitly set the `--settings-path` in pre-commit config so that `.isort.cfg` is always used. Otherwise, `isort` will try to deduce which config to use based on the file being fixed
- Set `funcx_endpoint` as first-party in `.isort.cfg` and `funcx_sdk/setup.cfg`. Perhaps there's a better way, but keeping both configs in sync is an easy solution for now.
- Apply the resulting fixes from `pre-commit run -a` …
> Ensure isort is applied consistently

- docs/quickstart.rst
While going through the [Quickstart section on ReadTheDocs](https://funcx.readthedocs.io/en/latest/quickstart.html) I noticed the link to mybinder.org site was 404-ing. I replaced the link so that it points to Introduction notebook in `https://github.com/funcx-faas/examples`
> Fixes broken link to intro notebook on binder

- .flake8
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/mock_broker/mock_broker.py
- funcx_endpoint/tests/integration/test_config.py
- funcx_endpoint/tests/integration/test_serialization.py
- funcx_sdk/funcx/utils/errors.py
- funcx_sdk/parsl/app/errors.py
Wildcard imports undermine the capabilities of static analyzers (namely `flake8`, but also pylint) and make it more difficult to understand code.
Once a wildcard import is done, any apparently unbound name could be taken from the wildcard import. It's not knowable without traversing more modules.
They are *always* avoidable. In the extremely rare case that names from a module or package must be rebound in another namespace, they should all be imported explicitly and the `F401` flake8 rule (unused imports) should be ignored. Given that these cases are often about re-exporting names, we can even avoid this with the inclusion of an `__all__` list or tuple.
In the case of `__init__.py` modules which exist solely for the purpose of rebinding names as package-level members, we may prefer to add …
> Remove flake8 exemption for wildcard imports

- README.rst
- docs/quickstart.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/requirements.txt
- funcx_sdk/funcx/sdk/version.py
This PR only bumps the version number to v0.3.0
> Bumping version to v0.3.0

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
A log line in the funcx_manager was dumping the raw task message for debugging. This PR removes this.
> Removing debug logline dumping raw task message

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Fix container `spin_up_workers `not passing the correct `container_cmd_options`
Fixes # Add 'self.container_cmd_options` to new worker instances.
> container_cmd fix

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
Remove process name check, and rather just simply confirm the process with the pid exists
From what I can tell, there's no easy cross-platform way to set a process name so it's better that we just check the process with pid exists
Fixes https://github.com/funcx-faas/funcX/issues/558
> Remove process name check when checking endpoint status from pid

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
Forgot to remove `match_name` from `check_pidfile` function
> remove match_name param from check_pidfile

- docs/configs/midway_singularity.py
- docs/configs/theta_singularity.py
- docs/configuring.rst
This PR adds example singularity configs to docs for midway and theta.
> Add singularity example configs to docs for midway and theta

- .github/workflows/pypi.yaml
Need to get add a GitHub Actions workflow for the pypi release. It still needs further development, but it seems like it needs to appear in master before it can be tested in a branch
> Add action to set version numbers on release

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/results_ack.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/messages.py
See https://github.com/funcx-faas/funcx-forwarder/pull/27
> Results Ack Sending

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
We do not want to be info logging endpoint status reports as results, since this will only confuse users. We should simply rely on the debug logs in the executor for EPStatusReport sending
> Log result passing to forwarder only if an actual result (Not EPStatusReport)

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/taskqueue.py
This is needed so that when `close` is called on sockets then the socket context is terminated, nothing blocks. If there are messages in the pipes, `close` will block indefinitely (default linger value is infinity).
> Add zmq linger option and set to 0 for all TaskQueues

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
Change functionality of endpoint logging such that it all appends to same file by default
> Same file by default for endpoint stdout/stderr and file logger

- docs/configs/bluewaters.py
- docs/configs/cooley.py
- docs/configs/cori.py
- docs/configs/frontera.py
- docs/configs/midway.py
- docs/configs/midway_singularity.py
- docs/configs/perlmutter.py
- docs/configs/theta.py
- docs/configs/theta_singularity.py
- docs/configs/uchicago_ai_cluster.py
Updating the configs in the docs so that they follow the same order and include similar default settings. Main focus to set scaling behavior so as to avoid provisioning nodes by default (init and min blocks = 0).
> Standardizing configs and setting init blocks to 0.

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/tests/test_executor.py
Default results websockets URI were pointed at `wss://api.funcx.org/ws/v2/`. This PR updates it to `wss://api2.funcx.org/ws/v2/`
> Updating results websocket url to wss://api2.funcx.org/ws/v2/

- .github/workflows/ci.yaml
In order to run the `publish` step, the workflow must be executing
- on the main repo
- under a 'push' event
This means that the following activities will not run the `publish`
job:
- pushing a branch to a fork
- opening or updating a PR
PRs from forks would otherwise trigger the job and fail.
> Skip publish job on forked push and PR triggers

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
Enable the endpoint retry loop
For how to test, see: https://github.com/funcx-faas/funcX/pull/576
> Endpoint disconnect retry loop

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
A better warning is needed in case a result arrives that has no corresponding future
> Better warning when WebSocket result arrives with no future

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
This PR adds additional information to the ZMQ registration message sent to the forwarder. This allows the forwarder to treat older endpoints differently for backward compatibility.
> Add additional platform info to registration message

- funcx_sdk/requirements.txt
Right now it's unspecified, which is very, very, very wrong.
If it gets updated via transitive dependency doing its updates, a bunch of code in this repo which depends on SDK v2 or lower will break.
> Pin back globus-sdk version

- docs/conf.py
- docs/index.rst
- docs/limits.rst
- docs/reference.rst
- docs/sdk.rst
* New section on limits, and some notes on how to effectively work within those limits
* Clarification on blocking behavior on batch operations
* Clarification on return values from batch ops
* Added missing throttling exceptions to references.
* Removed the bit on client throttling that tells the user how to disable client-side throttling, which IMO is a bad idea.
The limits section now covers 3 different mechanisms by which funcX limits what functions can run and how.
P.S The docs now say 30 mins is the TTL limit on results, which we don't enforce yet.
[ch10382]
[ch10725]
> Updating docs on blocking behavior, funcX service limits and exceptions

- funcx_endpoint/requirements.txt
I found that something odd happened with version solving in `pip` when I did a `cd funcx_endpoint; pip install .`
For whatever reason, the solver picked the latest SDK version.
Until the funcx-sdk package is updated to use SDKv3, this won't work.
I haven't worked very hard to isolate and reproduce the issue because I don't think it's worth it. We should just pin the version until we can update, to guarantee that the solver can't fail like this.
> Bound the `globus-sdk` version for funcx-endpoint

- funcx_endpoint/tests/smoke_tests/conftest.py
Never used.
---
See also: https://github.com/funcx-faas/funcx-web-service/pull/263
> Remove 'funcx_version' from test data

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Previously the error message claimed that the fatal error was due to
version mismatch.
This is not true: this same fatal error may occur in the case of a
BadRegistration.
This PR rephrases the error to be less misleading.
I have encountered this repeatedly during review of #909, and at
least I think Yadu was getting it while hacking on this code.
> Broaden htex interchange->executor error message phrasing

- funcx_sdk/funcx/tests/conftest.py
- funcx_sdk/funcx/tests/test_errors/test_invalid_endpoint.py
- funcx_sdk/funcx/tests/test_errors/test_invalid_function.py
- funcx_sdk/funcx/tests/test_executor.py
- funcx_sdk/funcx/tests/test_performance/test_performance.py
- funcx_sdk/funcx/tests/test_result_size.py
This is part 1 of 42 (give or take, depending on how I chunk things). I will give less explanation on subsequent PRs, but as this is the first, I should explain how I did things.
I wrote new linting config for use of black, isort, flake8, and pyupgrade in pre-commit. I then applied it to the whole codebase to get the fixers satisfied. This didn't pacify flake8 because these tools avoid making certain "unsafe" changes to the AST or CST, determined on a tool-by-tool basis.
Then I manually modifyied files and committed them in batches with `--no-verify` to avoid pre-commit failures.
Finally, there's one last commit which adds the new config -- which means that there is no commit in this series where linting is expected to fail.
Once all of the changes are merged, we can apply the new linting …
> Cleanup linting on sdk tests

- .github/workflows/daily.yaml
Originally, I meant for this PR to also add `safety` to install extras, but I've decided not to do that.
Why? Because `safety` is not meant for analysis of the `funcx[test]` extra, only the main `funcx` requirements (and likewise for the endpoint).
I want to take some more time to think about how we're going to pull in `safety` -- a dedicated extra, adding it to a `funcx[dev]` extra (and not worrying about it checking test dependencies), a tox testenv, or maybe something else.
> Expand daily build to all days

- funcx_endpoint/tests/smoke_tests/conftest.py
- funcx_endpoint/tests/smoke_tests/test_version.py
Check against the API response with a loose version comparison, not an equality check. This means that the smoke tests set a "floor" for what versions are allowed, but do not fail when a release is done.
---
Example of a failure (by modifying the config):
```
forwarder_version = response.json()["forwarder"]
min_version = funcx_test_config.get("forwarder_min_version")
if min_version:
parsed_min = LooseVersion(min_version)
parsed_forwarder = LooseVersion(forwarder_version)
>           assert (
parsed_forwarder >= parsed_min
), f"Expected Forwarder version >= {min_version}, got {forwarder_version}"
E           AssertionError: Expected Forwarder version >= 0.3.6, got 0.3.5
E           assert LooseVersion ('0.3.5') >= LooseVersion ('0.3.6')
```
> Make smoke tests check min version, not exact

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
This clarification was introduced as part of
https://github.com/Parsl/parsl/pull/980
I have not examined the rest of that PR for relevance to this fork.
I've encountered confusion due to the phrasing of this error twice during the review of PR #606 
> Port parsl BadRegistration error message clarification to funcx fork

- .github/workflows/hourly.yaml
Previously, the subject line reported a success when sending failure messages.
```
Subject: funcx-faas/funcX - Tutorial test success
```
presumably because the `job.status` substitution does not match up with the boolean value of `    if: failure()`
Also rename "tutorial" to hourly smoke test.
> Fix subject line in hourly smoke test

- .github/workflows/smoke_test.yaml
- funcx_endpoint/tests/smoke_tests/test_s3_indirect.py
Adds tests that exercise IO, and indirectly tests storage to S3.
Apparently, arg sizes aren't being limited correctly and the test for that is marked as xfail.
> Adding a minimal s3 smoke test

- .github/workflows/hourly.yaml
This PR updates the hourly test to install `funcx_endpoint`. Currently we need `MaxResultSizeExceeded` is required from `funcx_endpoint` in testing. 
> Install funcx_endpoint for smoke tests

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/tests/smoke_tests/test_s3_indirect.py
- funcx_sdk/funcx/tests/test_result_size.py
And fix `sys.getsizeof` on a bytestring to use `len` instead.
I've also updated tests which generated 550KB of data (exceeding the 512KB limit) to generate 11MB of data. This should generate the same error before and after the update. It therefore will keep smoke tests working when the tutorial endpoint is updated, for example.
> Raise result size limit to 10MB

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/tests/test_longduration.py
Our funcx-websocket-service disconnects idle connections after about 10 minutes (https://github.com/funcx-faas/funcx-websocket-service/blob/main/funcx_websocket_service/connection.py#L52). This disconnection messed with the client, since we don't have any reconnect logic. This PR adds support for identifying these remote side disconnects, cleanly closing down the websockets, and reconnecting.
This is difficult to test in CI since the test has to have an idle connection for >10mins which would slow down tests drastically. I'm working on a getting this tested atm and will add a mocked test separately.
Fixes #562 
> Reconnect on remote disconnect

- docs/endpoints.rst
Link to parsl broken due to typo. Correct typo (hhttps -> https).
> Fix broken link to parsl docs

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Context-manager lock usage is safer because it releases the lock if an exception is raised.
The name of the lock is bad because it's used by task cancel and by result sending. `task_finalization_lock` seems like an appropriate rename.
---
This is meant to address outstanding comments from #606
> Rename task_cancel lock and use as ctx manager

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
Updating the version tags on funcx-sdk and funcx-endpoint to 0.3.5-dev to indicate that builds made off of main will be close to the upcoming 0.3.5 release. This is not a complete fix for #654 but a decent interim solution until we decide on a long-term fix for reporting a build's origin from the commit tree.
Fixes #654
> Updating version to 0.3.5-dev

- funcx_sdk/funcx/sdk/_environments.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/tests/unit/test_client_init.py
- funcx_sdk/funcx/tests/unit/test_environment_lookups.py
This is the alternative to #655 I was suggesting in chat.
Environment name -> URLs, with no support for a "local dev" environment.
I like the class-based interface used by the globus-sdk better than this for the long term because it allows dynamic registration of additional environments, but it's not necessary for a first cut at something simpler than what we have today.
---
webservice and websocket service URLs are resolved by the names "production" and "dev". These values can be passed to FuncX client init as in `environment="dev"`, or by setting the `FUNCX_SDK_ENVIRONMENT` environment variable. Unknown names are treated as aliases for `production`.
Unit tests cover the helpers which resolve these names.
If explicit values are passed to `FuncXClient` for the URLs, they are used instead …
> Setup environment-based URL resolution

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_sdk/funcx/tests/test_result_size.py
- funcx_sdk/funcx/utils/errors.py
- smoke_tests/tests/test_s3_indirect.py
This PR removes the MaxResultSizeExceeded exception defined in funcx_endpoint.executors.high_throughput.funcx_worker and instead imports from funcx SDK.
Fixes #640
> Move MaxResultSizeExceeded to funcx.utils.errors

- smoke_tests/tests/test_s3_indirect.py
The exception name is changing so we want the local name for
tox -e localdeps
but we need to handle the import failing if we're running against the last endpoint/sdk release.
> Fix to smoke_tests: allow use of last release

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
Updating version numbers to reflect that the `0.3.5` release is complete and that main is now `0.3.6-dev`.
> Updating version to 0.3.6-dev

- .github/workflows/changelog.yml
- CONTRIBUTING.md
- changelog.d/README.md
- changelog.d/scriv.ini
- docs/changelog.rst
- add changelog.d/, and changelog.d/scriv.ini
- add github workflow which enforces the inclusion of changelog fragments in PRs (unless exempted by a label)
The config will pull version info from the funcx SDK package.
As there are two packages being maintained with a single changelog, the changelog.d/ dir is placed in the repo root.
---
At a later date, I'd like to rewrite the existing changelog to replace
`Bug Fixes -> Fixed`
`New Functionality -> Added`
and then remove the category config.
The default categories are less verbose and let us use the other defaults without a stylistic mismatch.
However, in case anyone is very attached to the current names, I've left that as a future issue.
> Add the use of scriv to manage the changelog

- .github/workflows/ci.yaml
- funcx_sdk/tox.ini
Test all python versions 3.6-3.10 (removal of 3.6 may be considered).
Configure tox to run only the unit tests, which can pass without external services being available.
> Setup tox + CI for testing SDK under a matrix

- funcx_sdk/funcx/tests/test_managerlost.py
This PR adds a test that uses a task that kills the manager to trigger a ManagerLost exception. The test confirms that the
task lost is reported as failed due to `ManagerLost`. The following test confirms that the endpoint is online with at least one other manager that is processing tasks.
> Test for ManagerLost exception

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/providers/kubernetes/kube.py
The interface is descended from parsl's strategy/provider status
interactions but is substantially looser, allowing more flexibility
in kubernetes strategy/provider interactions.
> Document post-parsl changes to strategy/provider status interface

- changelog.d/20220201_153610_sirosen_ensure_logdir.rst
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/logging_config.py
- setup_logging now does a `makedirs` call on the parent of the configured logfile
- any calls to `makedirs` immediately preceding `setup_logging` are removed
This resolves the immediate problem cited in #681 , although I might not close that until we're _not_ doing file logging early in the process. That will be another fix.
I tested by removing my `~/.funcx/` dir and running `funcx-endpoint start`, confirming that it fixes that issue.
I'm not sure if we need more testing than that + CI?
> `setup_logging` creates the logdir

- funcx_endpoint/tests/stress_tests/README.rst
- funcx_endpoint/tests/stress_tests/conftest.py
- funcx_endpoint/tests/stress_tests/shared.py
- funcx_endpoint/tests/stress_tests/test_batch.py
- funcx_endpoint/tests/stress_tests/test_executor.py
- funcx_endpoint/tests/stress_tests/test_executor_io.py
- funcx_endpoint/tests/stress_tests/test_io_volume.py
- funcx_endpoint/tests/stress_tests/test_multi_client_ep.py
- funcx_endpoint/tests/stress_tests/test_raw.py
This PR adds a few stress tests that test the following:
* Run ~1000 to ~10000 no-op tasks 
* Run ~10000 tasks with minimal IO for both input and output so as to only hit Redis
* Run ~1000 tasks with larger IO ~1MB for input/output to stress test S3 storage
* Use multiple endpoint and client pairs to simulate multi-user load
Please note that there's some duplication between tests.
Fixes  [sc-12026] 
Since this is not a feature that needs to user-visibility, I'm skipping a changelog update.
> Add stress tests

- docs/changelog.rst
- docs/configuring.rst
These are warnings spotted if you fix things enough to run sphinx locally (as seen in #691).
- title underline too short
- malformed code-block
In the case of the malformed code-block in the changelog, it also was never subject to review. We should not be recommending that users recreate complex logging utilities. Rather, show simple config and point at the Python Logging HOWTO doc.
---
These aren't all of the errors seen in a local build, just a start.
> Fix minor errors in docs

- funcx_endpoint/tests/stress_tests/test_batch.py
- funcx_endpoint/tests/stress_tests/test_raw.py
Add working batch stress test, and remove old stress test that relies on removed `MaxRequestsExceeded` (If we add some form of rate limiting on the web service we will need to revisit these stress tests)
> Fix stress tests

- changelog.d/20220201_134414_benc_kubernetes_pod_names.rst
- funcx_endpoint/funcx_endpoint/providers/kubernetes/kube.py
This is in line with funcx-COMPONENT naming used for other funcx pods
> Make kubernetes worker pods describe themselves as funcx-worker-*

- .github/workflows/ci.yaml
- funcx_endpoint/tox.ini
Simplifies testing by codifying what is being done by CI in something locally runnable.
Switch CI to using said config, and make sdk/endpoint jobs as uniform as possible. In order for the safety check to work, put it in a separate job that installs the funcx-endpoint directly. Put the tox run of the endpoint into a matrix config which tests the high and low python versions.
You can try this out with `cd funcx_endpoint; tox`.
> Add a tox config to test funcx-endpoint

- .github/workflows/ci.yaml
- funcx_endpoint/setup.cfg
- funcx_endpoint/tox.ini
- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/errors/api_error.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/setup.cfg
- funcx_sdk/tox.ini
This is almost all just "annotate the code as it exists today" in order to get mypy passing.
The only case of even mild complexity is the WebSocketsPollingTask. Two issues there need fixing:
1. There's a nasty issue with the type publishing from `websockets` (it has a custom importer) but the solution is simple: import from `websockets.client` rather than the top-level package. A comment on the import points at the relevant thread.
2. Wrapping `ws` in a property to narrow its type
There are at least half-a-dozen ways of handling this. It's sufficient to toss in some `assert` calls if we wanted to go really, really lightweight. However, the property strikes me as the nicest solve.
> Enable mypy (passing on SDK, setup but failing on Endpoint)

- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q_shutdown.py
I first replaced `close()` with `stop()` and tried switching all of the tests to use it. That led to test hangs, so I ended up making a few other changes in the course of clearing that up.
I think the changes are positive and worth keeping, but I'm happy to back anything out if necessary.
---
- Instead of redefining `close()`, add a new method, `stop()`, which is responsible for terminating clenaly from the parent and invoking `close()` as one of the steps
- Use a ternary enum instead of `_closing = t/f` to describe a subscriber as "parent process", "running child" or "closing child". Call this the `status` and use it to track `closing`
- Define a `_shutdown()` method which handles clean teardown, including closing the connection to the MP queue and joining the background thread to ensure …
> Cleanup TaskQueueSubscriber stop method

- .github/workflows/ci.yaml
- changelog.d/20220225_175608_yadudoc1729_add_rabbitmq_plumbing.rst
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/README.rst
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/__init__.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_subscriber.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_publisher.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/test_rabbit_mq/conftest.py
- funcx_endpoint/tests/test_rabbit_mq/test_endpoint.py
- funcx_endpoint/tests/test_rabbit_mq/test_result_q.py
- funcx_endpoint/tests/test_rabbit_mq/test_result_q_heartbeat.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q_shutdown.py
- funcx_sdk/funcx/sdk/client.py
This is the 2nd PR that should go into `rabbitmq_rearch_feature_branch`. 
This PR adds 4 classes and tests:
We have 4 new classes:
`TaskQueueSubscriber`: This is an endpoint-side component launched off-process that pipes task messages from the service over rabbit_mq into multiprocessing.Queue.
`ResultQueuePublisher`: This class enables publishing results from the endpoint to the service over rabbit_MQ
`TaskQueuePublisher`: Service side component that publishes tasks to the endpoint over rabbit_mq
`ResultQueueSubscriber`: Service side component that listens for results from the endpoint over rabbit_mq.
Key bits that are already implemented and more or less tested:
* Disconnects raise an error in TaskQueueSubsciber and ResultQueuePublisher.
* Once one TaskQueueSubscriber can be connected to …
> Add RabbitMQ plumbing [RMQ Series 2]

- changelog.d/20220131_083455_ward.logan.t_pincuda.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/worker_map.py
- funcx_endpoint/funcx_endpoint/tests/conftest.py
- funcx_endpoint/funcx_endpoint/tests/test_accelerators.py
- funcx_endpoint/funcx_endpoint/tests/test_cancel.py
- funcx_endpoint/tests/funcx_endpoint/executors/high_throughput/test_worker_map.py
Fixes #664 
While working on this issue, I also added support logging worker stdout/stderr to disk (fixes #250 ). The change stores them in files next to the log for the worker.
> Add support for pinning workers to specific accelerators

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
This replaces a relatively useless process level object ID with a global funcx task ID, which makes understanding which task this applies to easier.
> Show task uuid rather than Python object repr in pull_tasks dispatch

- changelog.d/20220315_132500_benc_benc_logfmt.rst
- funcx_endpoint/funcx_endpoint/logging_config.py
This adds:
* a unix timestamp for machine readable processing of
log lines without needing to parse timestamps or be aware of
timezones. The existing human readable timestamp is preserved.
* process and thread names and IDs, and function name
These are intended to automatically add context on every log
line to eliminate the need for [SOME_THREAD] or [SOME_COMPONENT]
manual prefixes, so that that context is available on every
line.
This will make endpoint log files more verbose. However, this
commit is part of ongoing work to rationalise and reduce the
verbosity of endpoint logging.
Other commits will introduce more human-readable names on
processes and threads and remove [THESE_PREFIXES].
An example log line is:
1647345352.583025 2022-03-15 11:55:52 INFO MainProcess-20 …
> Make endpoint logging format richer

- funcx_endpoint/setup.py
Increase the sdk dependency to >=3.6 to include the globus_sdk v3 dependency. The previous 0.3.3 requirement would cause issues when the endpoint was at 0.3.8 due to requiring the globus v3 sdk.
> Increase the sdk dependency to >=3.6 to include the globus_sdk v3 dep

- changelog.d/20220326_181852_benc_benc_exa_race_interesting_managers.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
The interchange dispatches tasks to managers based on how many tasks it thinks the manager needs.
This starts with the manager reporting how many task slots it has. However, the interchange may have already sent some tasks, so it separately tracks how many tasks have been sent, and reduces the number of tasks to be sent.
This prevents a task queue building up in a manager - such a task queue can lead to tasks building up in one manager, when another manager has free capacity.
However, at the other end of a task, when a task finishes, I have observed:
* the manager now says it has capacity
* the interchange knows there is still a task there, so does not allocate a task
* the task result arrives
* the manager sits idle until the next advertisement (which might be on the order of 30s …
> Fix a race condition in interchange->manager task dispatch

- .pre-commit-config.yaml
- changelog.d/20220329_145838_sirosen_pin_click.rst
- funcx_endpoint/setup.py
`typer==0.4.0` (current latest) is broken by `click==8.1.0`.
This is based off of #730 so that CI will pass.
> Pin click to v8.0.4 for typer

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/tests/unit/test_executor.py
- funcx_sdk/setup.py
Basically, address a crash.  The property has no setter; one could argue for a setter, but I'm not yet sold on the need.  For a future refactor, perhaps.
> Set attribute, not property

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/tests/unit/test_ws_poller.py
If it's already None, then there's no need to crash (per None if-guard in property).  Do the deed directly or do nothing.
> Avoid possible crash during ws close

- smoke_tests/tests/conftest.py
Another quick one-liner, I was confused by this
https://github.com/funcx-faas/funcX/pull/744/files#diff-2a620095e706c574ee7aa0bd1321a5b2dac605ee3134408854a736d6ae174620L82
then realized `throttling_enabled` option is gone.
> remove use of throttling_enabled in smoke_tests

- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/tests/unit/test_executor.py
Mostly for type-checking, but also this clarifies a little what this object is by giving it a nice name.
I also did some very minor cleanup to control-flow to reduce the number of lines of code.
> Convert executor internal message objects from dict to dedicated object

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/tests/unit/test_client_init.py
i.e., teach `FuncXClient.__init__` the `task_group_id` argument.
At the moment, a largely transparent change for most users, but will see increased benefit come #11102.
> Enable end-user to specify session id

- changelog.d/20220331_205242_sirosen_no_userinfo_on_init.rst
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/search.py
- funcx_sdk/funcx/tests/unit/test_client_init.py
The basic goal here is (much) faster test runs. To achieve this, three changes are made to FuncXClient:
1. Add a new argument, `do_version_check=False` to skip the version check callout
2. Avoid doing a userinfo callout to Globus Auth by removing the need for the user's ID from the SearchHelper object
3. Lazily initialize the SearchHelper object only when accessed as part of a path towards potential deprecation and removal
The tests should have mocked this functionality sufficiently for things to run very quickly, but for some reason they were slow. Perhaps the activities of the SearchHelper object were to blame, or perhaps something was amiss with the mocks. Rather than worry overmuch about exactly how the time was being spent, this "cuts through the noise" by trying to make client …
> Cleanup for faster client init

- funcx_endpoint/funcx_endpoint/__init__.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_sdk/funcx/__init__.py
- funcx_sdk/funcx/sdk/__init__.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/version.py
- funcx_sdk/setup.py
- funcx_sdk/tests/unit/test_version_parse.py
- Remove distutils (deprecated in py3.10). Write a small version parsing helper instead (can use `packaging` in the future)
- ~set do_version_check=False in the endpoint code~
- remove check_endpoint_version as a client init argument
- version_check can now accept the endpoint version as an input (instead of that being automatic from local package versioning information), removing the funcx->funcx-endpoint import path
- ~use the explicit version check in the endpoint code (only once, on start)~
---
Beyond the unit tests for the quick version-parsing helper, I'm not sure what kind of testing this deserves?
EDIT: I've reverted changes to the version check on endpoint start from the endpoint code. These are struck-out above as they are incompatible with the last release of `funcx`.
> Remove distutils and reorganize version check

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/tests/unit/test_client.py
- funcx_sdk/tests/unit/utils.py
The major update here is mostly for robustness.  In the context of reloading tasks, it's possible to request a task from upstream that doesn't exist -- and thus returned from the API as 'Failed' but without an exception.  Catch that case by refactoring logic to better understand "pending" and to always create the exception.
Reviewer suggestion: may have luck seeing what changed by toggling whitespace.
> Refactor _update_task_table.

- changelog.d/20220318_213947_sirosen_login_manager.rst
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/login_manager/__init__.py
- funcx_sdk/funcx/sdk/login_manager/globus_auth.py
- funcx_sdk/funcx/sdk/login_manager/login_flow.py
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/funcx/sdk/login_manager/protocol.py
- funcx_sdk/funcx/sdk/login_manager/tokenstore.py
- funcx_sdk/funcx/sdk/search.py
- funcx_sdk/setup.py
- funcx_sdk/tests/unit/test_client.py
- smoke_tests/tests/conftest.py
- smoke_tests/tox.ini
Instead of login happening as part of client init (and only as part of client init), login is now handled by an independent component called the LoginManager. This encapsulates token storage and globus_sdk client builders.
For the most part, the LoginManager replaces any notion that a FuncXClient consumes authorizers for various internal clients directly. Instead, it may be given an object (not necessarily a LoginManager in the future) which is answerable for building usable HTTP clients for various APIs which may be needed.
---
Particular notes:
- This will force users to login again after upgrading, as noted in the changelog. In order to reduce the cost of testing, I decided to revoke old tokens if the new storage is not visible, and otherwise take no action. There is no token …
> Replace login as a built-in part of FuncXClient

- changelog.d/20220406_192605_sirosen.rst
- funcx_sdk/funcx/sdk/search.py
Originally, I was looking at this in order to remove our dependency on `texttable` (we should not be using that in the `funcx` package), but then I found myself looking at this class.
I could try to refactor it, but there are several design issues here which make any cleanup partial at best. It mixes presentation logic ("what does it look like?") with data handling logic, which is the most major issue. That seems to be its primary purpose, so the simplest fix is to remove the whole class.
We're discussing with one user right now, so I'm marking this as a draft until we can determine whether or not this will be a problem.
> Remove search response helper class

- changelog.d/20220407_145118_benc_executor_batch_default.rst
- funcx_sdk/funcx/sdk/executor.py
Developer consensus seems to be that we should have this active by default, driving towards it being our preferred task submission path.
> Set executor batch mode active by default

- funcx_sdk/.coveragerc
- funcx_sdk/setup.py
- funcx_sdk/tox.ini
Run pytest under `coverage` and report coverage showing the exact lines which are not tested.
I've done a more sophisticated config in other projects which collects coverage data from multiple tox envs, but it's more work to set it up and the benefit would be minimal for us right now. This reports coverage on each env.
Example output:
```
py37 run-test: commands[1] | coverage run -m pytest
======================================================================================================= test session starts =======================================================================================================
platform linux -- Python 3.7.9, pytest-7.1.1, pluggy-1.0.0
cachedir: .tox/py37/.pytest_cache
rootdir: /home/sirosen/dev/funcx/funcx/funcx_sdk, configfile: setup.cfg
plugins: …
```
> Add coverage reporting to tox output for funcx

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/tests/unit/test_client.py
The previous iteration relied on task existence in the internal task table to ascertain if an update should be requested from the server.  However, d2102a3ba05366f530eb38f66c7dbff3c4c0779b changed the table to also include `pending=True` statuses; consequently, update the relevant checks to take the pending status into account.
> Ensure pending tasks are always requested

- helm/boot.sh
This broke due to work around PR #724 which changes login mechanisms.
Existing users will need to do a user-environment login
and then transcribe the new tokens into a k8s secret
like this:
kubectl delete secret funcx-sdk-tokens
kubectl create secret generic funcx-sdk-tokens --from-file /root/.funcx/storage.db
> Use new secrets file for k8s endpoint

- funcx_sdk/funcx/sdk/asynchronous/funcx_future.py
- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/executor.py
This change is mainly about refactoring `WebSocketPollingTask::set_result()` for cleanliness and to reduce the total diff for #727.
Along the way, refactor `FuncXFuture` to its own file.
> Refactor websocket poller set_result

- changelog.d/20220325_154137_kevin_ReloadTaskGroup.rst
- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/tests/unit/test_executor.py
- funcx_sdk/tests/unit/test_ws_poller.py
By default, every instance of `FuncXClient` generates a fresh Task Group ID.  In the happy-path case, the user processes their tasks and never need know about it.  But in the case of a `FuncXExecutor`, access to this allows a user to reattach to a previous session (for example, if the researcher's script dies unexpectedly).  Reattaching looks like:
```python
saved_task_group_id = '<some_UUID_from_before>'
fxc = FuncXClient(task_group_id=saved_task_group_id)
fxe = FuncXExecutor(fxc)
rehydrated_futures = fxe.reload_tasks()
```
At which point the futures are like before, and one can wait for their results and exceptions:
```python
results, exc = [], []
for fut in rehydrated_futures:
try:
results.append(fut.result())
except Exception as exc:
exceptions.append(exc)
```
Fixes # SC-11102
- New …
> SC-11102 Implement task group rehydration.

- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/setup.py
- funcx_sdk/funcx/sdk/version.py
- funcx_sdk/tests/unit/test_version_parse.py
Additionally, the version parsing code needs to be bumped to handle alpha version specifiers.
We'll start the alpha line with this. As soon as it merges, I'll release it.
> Bump versions to 0.4.0a1

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/__init__.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/base.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_subscriber.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_publisher.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange_with_rabbit.py
- funcx_endpoint/tests/test_rabbit_mq/conftest.py
- funcx_endpoint/tests/test_rabbit_mq/test_rabbit_e2e.py
- funcx_endpoint/tests/test_rabbit_mq/test_result_q.py
- funcx_endpoint/tests/test_rabbit_mq/test_result_q_heartbeat.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q_shutdown.py
This is basically the cleanup I wanted on #701 but which I agreed to forgo for the sake of expediency.
It also converts arguments to be required keyword arguments and makes some names explicit in the spirit of "general cleanup".
---
Move all publisher and subscriber instantiation into dedicated fixture functions. The fixture funcs put created objects into "teardown lists" which have their relevant cleanup run at the end of each test in the form of a finalizer function.
As a result, there is no danger of resource leaks around these tests as every object is well accounted-for. The fixture funcs also fill in numerous default values like connection parameters and the default endpoint ID, so that tests are not required or expected to redundantly define the same or similar information.
When …
> Improve test robustness for rabbitmq tests

- funcx_sdk/setup.py
All usage of this library was removed from the client package, and although it is used by `funcx-endpoint`, that package
independently lists `texttable` as a dependency. Therefore, we can remove texttable without issue.
> Remove texttable from funcx deps

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/version.py
- funcx_sdk/tests/unit/test_version_parse.py
- add a comparator helper
- allow 'dev' to match alphas, betas, and non-pre-versions as "equal"
- ensure that pre-versions are compared "trimmed" against non-pre-versions
- comprehensively test all cases of version comparison
---
I find the comparator helper a little messy because it's very "C-style" rather than making objects which can be compared with native comparators. But it's also very straightforward and readable.
If we wanted fancy objects, I'd favor pulling in `packaging` and using the version parsing code it provides.
> Improve version comparison rules

- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_publisher.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- helm/boot.sh
This PR removes and unnecessary `--endpoint-uuid` cmd line flag used in the docker boot script.
> Removing unnecessary cmd_line flag

- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
This attempt to `close()` while `self._channel == None` results in an attribute error when the "real" error is a failure to connect.
> Don't try to close channel if connection failed

- funcx_sdk/funcx/sdk/executor.py
> Fix FuncXExecutor docstring that was causing sphinx errors

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
This includes a bunch of relatively standard test infrastructure for testing a click app. A CliRunner, an invocation wrapper which defaults to asserting `exit(0)`, and an autouse mock over the Endpoint object found in the CLI.
And at the end of all of this, the single desirable test which checks that `funcx-endpoint restart foo` will work.
> Fix 'funcx-endpoint restart' and add one test

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
- `quiesce` handling in the endpoint needs to be fixed a bit: The idea here is that for graceful shutdown we should simply set the kill/quiesce events without calling anything else, then the `_main_loop` will see these events and gracefully stop
- Child processes seem to be inheriting the main process SIGTERM handler which gets messy (see: https://app.shortcut.com/funcx/story/14977/endpoint-child-processes-inheriting-main-sigterm-handler)
> Fix graceful endpoint shutdown

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Update loop to use `heartbeat_period` not `heartbeat_threshold`.  Nominally, the threshold is for "grace period" use, rather than a standard "periodic check."
> `heartbeat_threshold` -> `heartbeat_period`

- .github/workflows/ci.yaml
- .github/workflows/daily.yaml
- .github/workflows/hourly.yaml
- .github/workflows/smoke_test.yaml
Whenever we `pip install tox`, first `pip install -U pip setuptools`.
This ensures that we get the latest `tox` version and that dependency solving is done correctly.
> In workflows using tox, ensure pip is up to date

- docs/executor.rst
Spawned by [sc-12295], which appears to now be fixed
> Docs - Executor - add missing parentheses

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
- funcx_endpoint/tests/unit/test_endpointinterchange.py
The main goal is to reduce the scoping of `self.results_outgoing`.  It was set inside the main loop function but accessed outside.  Reduce the scope, then move the try-except clause closer to it's intended protectee: the `quiesce()` invocation.  Finally, back it up with a unit test.
Along the way to SC-14129.
> Refactor unsafe scoping

- funcx_endpoint/funcx_endpoint/executors/high_throughput/messages.py
On python 3.7, running `tox -e mypy` against the endpoint fails. This tweak moves the `type: ignore` annotation introduced in the recent `mypy` fixup up one line so that `mypy` runs successfully on this version.
> Mypy fix for Python 3.7

- funcx_endpoint/setup.py
This library does not offer *any* backwards compatibility guarantees. As such, we need to always pin to an exact version.
> Pin the exact version of funcx-common

- funcx_sdk/setup.py
Necessary to support Python 3.10; otherwise, will fall victim to [websockets issue #916](https://github.com/aaugustin/websockets/issues/916).
- Bug fix
> Bump websockets to v10.3.

- funcx_endpoint/tests/conftest.py
- funcx_endpoint/tests/test_rabbit_mq/conftest.py
- funcx_endpoint/tests/test_rabbit_mq/result_queue_subscriber.py
Small fix that came about as I was cleaning my dev environment. Currently if you try to run tests using a local kubernetes cluster as the rabbitmq instance for integrations, many calls to `queue_declare` result in an error due to the fact that the web-service declares the 'results' queue as `durable=true` while tests declare it as `durable=false` (the default).
> Fix mismatch that happens when web-service declares a queue as durable but tests do not

- funcx_endpoint/setup.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/setup.py
I recently introduced some shared version logging code to `funcx-common` - this PR simply removes the old SDK version logging code from the web service and changes it to use the `funcx-common` module instead.
> Common version logging

- .github/_support/github-slack-notify.py
- .github/workflows/daily.yaml
- .github/workflows/hourly.yaml
Updates the daily and hourly tests to alert of failures using slack notifications. This change includes the slack notification script and modifies the two workflows to use it rather than send an email. The default message includes a here notification and will raise an alert when the status of the job changes.
Fixes # [sc-16011]
> Slack notification for tests

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/messages.py
In service of decoupling the services from the endpoint, this removes `TaskStatusCode`, as originally defined in the HTEX, and replaces it with `TaskState`, a pre-existing enum defined in `funcx-common`.
Related to [sc-16360]
> Remove `TaskStatusCode` and replace it with `TaskState` from `funcx-common`

- funcx_sdk/funcx/sdk/client.py
Since this is going away, a trivial change to flip the default to `False` gets us an improvement to dev workflows as near-0 cost.
> Flip the default for offprocess_checker

- .pre-commit-config.yaml
Until this branch merges, having auto-update PRs against `main` is the wrong place. Once it merges, we should revert this config.
---
pre-commit.ci gives us weekly auto-update PRs like #823
This is the necessary config to point those PRs at our current mainline branch. It is read from the repo-default branch, which is `main`. As such, this is a PR against `main` rather than `rabbitmq`. As I have in the past, I will do a manual merge-back to `rabbitmq` to re-synchronize the branches after this is merged.
> Update pre-commit.ci to point at 'rabbitmq'

- smoke_tests/Makefile
- smoke_tests/tests/test_s3_indirect.py
- smoke_tests/tox.ini
- add `funcx-common` to deps because v0.3.10 of the packages do not install it and it is used in test files
- add a conditional skip to ensure that `FuncxTaskExecutionFailed` is only used when a newer (`0.4.0-dev+`) version is in use
Additionally, `make dev` should (for now) use `tox e- localdeps` to install from the local repo. This fails at the moment but does not appear to be related to the tests themselves.
> Fix smoke tests to work against prod

- changelog.d/20220705_163242_chris_funcx_client_url_mismatch.rst
- changelog.d/20220706_095230_LeiGlobus_off_process_checker_removal_sc_13659.rst
- docs/actionprovider.rst
- docs/changelog.rst
- docs/configuring.rst
- docs/debugging.rst
- docs/endpoints.rst
- docs/executor.rst
- docs/sdk.rst
Addresses the following syntactical issues in docs:
* [Big red error box](https://funcx.readthedocs.io/en/latest/endpoints.html#example-configurations)
* [Funky indentation in changelog](https://funcx.readthedocs.io/en/latest/changelog.html#added) (and potential for it to happen when current changelogs are collected)
* Consistent misuse of `` ` `` which produces italics, instead of ``` `` ``` which produces inline code blocks
* Some of the changes here will be subjective, and I intentionally left any single backticks that looked appropriately like italics instead of code. Let me know if I changed something I shouldn't have or should change something I didn't.
- Documentation maintenance/cleanup
> Docs fixes

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
`.wait(timeout)` will quit immediately when the event is set.  No sense in enforcing the wait period if it's not necessary.
> Mild status loop refactor

- changelog.d/20220715_160834_kevin_update_status_delta_per_fx_common_change.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/tests/unit/test_funcx_manager_unit.py
- funcx_endpoint/tests/unit/test_highthroughputinterchange.py
To support retrospective log analysis ("What went wrong??!?!"), ensure that each task state change includes a timestamp.
> Teach endpoint new Task state data structure

- funcx_sdk/setup.py
This is required by RemoteExceptionWrapper, and without tblib,
exceptions from an endpoint cannot be deserialized on the
client.
> Add tblib python dependency

- funcx_endpoint/funcx_endpoint/exception_handling.py
- funcx_endpoint/funcx_endpoint/exceptions.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- new modules for error handling code in the worker
- use the code for error handling (identical to the worker) for task cancel
---
I didn't test this because tests failed for me and I don't work on funcx really anymore. So watch CI and see if this works.
> Move error handling code, use for task cancel

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Now:
migrate_tasks_to_internal Received task: 9ce42865-b9b2-4ca8-8682-219cf4c2b038
Before:
migrate_tasks_to_internal Received task:<funcx_endpoint.executors.high_throughput.messages.Task object at 0x7fc1bc19daf0>
> Report task ID, not repr(), in received task message

- .github/_support/github-slack-notify.py
The slack notification condition was comparing the repo name to funcx, not funcX. This change corrects that and adds two additional print statements to aid in debugging whether the notification is sent.
> Correct smoke test slack notification condition

- changelog.d/20220803_105233_ben_working_dir_for_workers.rst
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
There is no way to specify the log directory for workers in a Kubernetes endpoint. This results in permission errors in docker images that aren't running a root user. 
Thanks to @benclifford we see that this needs to be specified in the `working_dir` property in the`HighThroughputExecutor` constructor.
Moved this value from an ignored property in the `KubernetesProvider`
> Use HighThroughputExecutor constructor arg to specify location for worker Dirs

- helm/boot.sh
The command line argument for `funcx-endpoint start` command changed. The helm chart deployment was throwing an error: 
```
Usage: funcx-endpoint start [OPTIONS] [NAME]
Error: No such option: --endpoint-id Did you mean --endpoint-uuid?
```
Updated the shell script that launches the endpoint to use the correct command line argument
> Endpoint Helm Chart Uses Correct funcx-endpoint-uuid command line arg

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
When an endpoint is restarted, it attempts to send any unsent results to RMQ.  This is a problem if the endpoint never forgets a result -- it will resend already-sent results.  In the ad-nauseum case, and endpoint with lots-o-stored-results can take an hour or two to resend these messages to RMQ.
Fixes: SC-17609
> Forget the acked results

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
The main loop morally contained two kernels: one to collect and forward tasks and one to collect and forward results.  The problem was that either we wait for a time (timeout) or don't block and have a busy loop.  In the worst case of either only tasks or only results to forward, that meant the timeout for the "nothing to forward" case puts a bottleneck on the other loop kernel.  At a `timeout=0.01`, that limits the maximum throughput to 100 iterations per second.
Address this by pulling the two kernels out into two separate threads, and hopefully keeping the intent of the heartbeat logging.
> Improve forwarding performance with threads

- smoke_tests/tests/test_version.py
The endpoint status check is broken and causing tests to fail. This is being replaced with an improved endpoint status monitoring code and can be removed until that is correctly in place.
Fixes # [sc-17574]
> Skip the broken endpoint status test

- changelog.d/20220720_141209_benc_benc_parsl_dep_master.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/setup.py
This commit removes an unnecessary dependency on a
parsl executor superclass that has been restructured
since the previously used parsl release. It turns out
that only one line from that superclass was needed,
to store the specified provider, and this PR moves
that line directly into the FuncX version of HTEX.
This allows a PBS contribution to parsl from Ryan Chard
to be used in FuncX endpoints.
This should also allow more easy updating of the
parsl dependency as/when desired.
> Switch to recent parsl master

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Nominally a thinko when transitioning the intertwined kernel to multiple threads: we want a heartbeat every period, not on the threshold of timing out.
In doing so, remove the only usage of threshold, and so also remove the threshold class variable.  It looks like the last legitimate use of this variable was removed in Apr:
commit 08eba06bc1ff365f0b932d9b09bd4c1eb01493f1
Date:   Thu Apr 7 15:29:25 2022 -0500
Integrate rabbitmq with endpoint [RMQ Series #3] (#703)
> Use correct variable: period, not threshold

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- funcx_endpoint/tests/test_rabbit_mq/conftest.py
- funcx_endpoint/tests/test_rabbit_mq/test_rabbit_e2e.py
- funcx_endpoint/tests/test_rabbit_mq/test_task_q.py
This is a slightly confusing muddling of a variable's purposes in two different contexts.  In the parent process, the `quiesce` event is utilized to signal a need to restart ("reload"; "reboot") the communication setup of the funcx endpoint.  (Shutdown the task queue watcher and result publisher, then restart them again.)  In the child process, that semantic is lost and the point is just "time to shutdown."  Meanwhile, while tracing through, the change in name from `quiesce` to `kill` has proven difficult to follow mentally.  So, choose the path of (apparent) least resistance and refactor it based on the development team's preferences.
> Refactor class variable name

- funcx_endpoint/funcx_endpoint/executors/high_throughput/mac_safe_queue.py
Fixes our import of `mac_safe_queue` to accommodate the new location in Parsl, following the Parsl upgrade.
> Update mac_safe_queue import for new Parsl version

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/setup.py
Prior to this, the code still tried to deserialise
exceptions in expectation of a RemoteExceptionWrapper,
which was changed in PR #814.
This PR makes FuncxTaskExecutionFailed exceptions
in executor mode in the same way as the allegedly
deprecated polling mode.
> Use FuncxTaskExecutionFailed in executor mode

- funcx_sdk/funcx/version.py
- funcx_sdk/setup.py
Only version updates here.
Updating funcx version to 1.0.0a0 and funcx-common from 0.0.14 to 0.0.15
> Updates to funcx for 1.0.0a0 release updates

- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/setup.py
- funcx_sdk/funcx/version.py
- funcx_sdk/setup.py
Updating versions for prepping an alpha for release testing.
Updating parsl>=1.3.0dev0, funcx-common==0.0.15 and funcx==1.0.0a0
> v1.0.0a0-release updates

- changelog.d/20220816_152320_kevin_default_to_spoa_namespace.rst
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
This constructor default argument represents a second point of authority for the eventual token namespace -- the cause of a bug on v1.0.0 release day.  Instead, default to `None`, and let the library choose the correct namespace via its internal logic.
> Default to None to let lib choose default

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
In the case of a `detach_endpoint=False` setup, a developer can now hit <kbd>Ctrl</kbd>+<kbd>\\</kbd> and have a traceback free `funcx-endpoint` quitting experience.  I do not feel comfortable replacing Python's default SIGINT handler at this time as there are some as-yet undiagnosed shutdown issues (though they may be mitigated by simply doing the same `kill_event` setting as here -- "but not today").
In short, motivated by a slightly OCD developer desire.
> A cleaner endpoint quit from the CLI

- docs/configs/polaris.py
Updates the example config for the Polaris machine. The networking issue requiring an IP address has been fixed and can be replaced with address_by_hostname(). Also, requests specifying fewer than 32 cores seem to fail. Adding in the `select='ngpus=4'` to demonstrate how that works too.
> Update the example config for Polaris

- changelog.d/20220817_134952_yadudoc1729_serialization_fixes.rst
- funcx_sdk/funcx/serialize/concretes.py
We've recently seen smoke-tests fail with serialization errors where the serialized function body refers to modules by name. 
This looks mostly like a failure in serialization where the function refers to test function it is invoked from when it really shouldn't. Why this happens definitely could use more investigation. A potential fix here is to prioritize `DillCodeSource` that serializes via copying the source over. The one caveat here used to be that `DillCodeSource` has issues with code indentation when the target function definition is in a nested context. This PR addresses these two bits:
* Update `DillCodeSource` to `lstrip=True` to adjust code indentation (affects nested fn definitions)
* Change the serialization order to use DillCodeSource before DillCode.
Choose which options …
> Fixes for serialization module

- .github/workflows/ci.yaml
Not an issue *yet*, but noting the following message on the CLI, take the opportunity to update the health checks:
$ docker run --rm -ti --health-cmd "rabbitmqctl node_health_check" ... bitnami/rabbitmq:3...
...
rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.
...
> Use non-deprecated RMQ health check

- .github/workflows/ci.yaml
After finally, *finally* tracking down the cause of failure in a recent test, it became clear that the problem could have been identified much sooner if we had access to the information the _production_ code already handles gracefully.  The test was in error, but the core issue was very elusive until the error-level logs were emitted.  Attempt to avoid that experience going forward.
For reference, this will add stanzas like these to the CI test log output:
```
tests/unit/test_funcx_worker.py::test_execute_failing_function 
----------------------------------------------------------- live log call -----------------------------------------------------------
ERROR    funcx_endpoint.executors.high_throughput.funcx_worker:funcx_worker.py:132 Caught an exception while executing user function …
```
> Show error-level logs in tests

- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- funcx_endpoint/funcx_endpoint/endpoint/register_endpoint.py
There is no need to emit the connection information here anyway as we already share all information (but properly redacted) when we register with the web services.
Relatedly, update redaction text per a loosely related verbal conversation: `***:***` is likely more recognizable as "intentionally redacted" than `u:p` which could possibly be considered a mistake by a log trawler.
> Remove credentials from logs

- changelog.d/20220819_150602_chris_fix_endpoint_status_report.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Contains frontend changes to support https://github.com/globusonline/funcx-services/pull/130. Also updates the status report loop so that EPs report their status on startup, instead of waiting `heartbeat_period` seconds.
Fixes [sc-17576]
> Fix endpoint status report

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
Philosophy: In general, code under test should have no knowledge it is under test.  #dieselgate, anyone?
> Remove test-flag in production code

- changelog.d/20220820_232432_kevin_log_to_console.rst
- changelog.d/20220824_221225_kevin_log_to_console.rst
- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/logging_config.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
For quick iteration and testing, eliminate the need to change terminals and/or reload the endpoint.log file: just spew the lines to the terminal.  Immediate feedback can often lead to different insights.
> Enable logging to console

- changelog.d/20220824_221225_kevin_log_to_console.rst
- changelog.d/20220825_211818_kevin_colorize_console_at_debug.rst
- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/logging_config.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
In order to more quickly draw attention to the relevant parts of the log lines, implement ANSI color escape codes.  The idea is not artistic perfection, but a simple approach to "syntax highlight" the console (*strictly* console, not log files).  To that end, the "header" of each line (i.e., time, runtime info, code line, method name) is the same, but the actual message is slightly different for DEBUG, INFO, WARNING, and ERROR logs.
In addition, since we are so heavily UUID based, also highlight any UUIDs.
For those who want to log to the console and do not want color, there is also a `--no-color` argument.
> Colorize console logs

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Parsl's ScalingFailed is based around the structure of parsl's
executors and providers scaling mechanism, which is not used in
funcX - that makes ScalingFailed the wrong kind of exception to
raise here.
Prior to this PR, that exception is misconstructed with a string
where a ParslExecutor is expected, which results in further exceptions
when attempting to render the exception (experienced by @ryanchard
for example).
This commit changes this to a RuntimeException, pending bikeshedding
about proper error types.
A second use of ScalingFailed, also incorrect, exists in what appears
to be dead code in funcx_endpoint/executors/high_throughput/executor.py.
Because that appears to be dead code, this commit does not attempt
to interfere there.
Choose which options apply, and delete the ones which …
> Remove inappropriate parsl ScalingFailed exception usage

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Release those resources.  This is not strictly necessary on the parent side, where the handle goes out of scope, but it never goes out of scope in the child process.
> No sense in leaving the queue open

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
If the RMQ service closes the connection, the class state is stale.  Instead, rely on the _connection_ state to determine if a close() is necessary.  Meanwhile, no need to shut down the channel -- closing the connection will take care of that automatically.
Easy recreation: close the `ep_result` connection from the RMQ admin console (_Connections_ tab).
Example traceback (that this PR avoids):
```python
[TIMESTAMP] ERROR ....endpoint.interchange:279 start Unhandled exception in main kernel.
File "VENV/endpoint/interchange.py", line 277, in start
self._start_threads_and_main()
File "VENV/endpoint/interchange.py", line 303, in _start_threads_and_main
self._main_loop()
File "VENV/endpoint/interchange.py", line 327, in _main_loop
with …
```
> Avoid traceback if RMQ closes connection

- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/tests/unit/test_login_manager.py
This does not change much for the motivating error found during development -- namely a cleaner/shorter traceback -- but it does present a more on-target error message for the fundamental problem.  More importantly, this is a general answer for this problem, no matter if it's initiated by an endpoint or some other workflow.
> Give more direct description of problem

- changelog.d/20220727_115011_rchard_client_login.rst
- funcx_sdk/funcx/sdk/login_manager/client_login.py
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/funcx/sdk/login_manager/tokenstore.py
- funcx_sdk/tests/unit/test_login_manager.py
Add's login logic to support Globus Auth client credentials. This change lets users export FUNCX_SDK_CLIENT_ID and FUNCX_SDK_CLIENT_SECRET environment variables to bypass the native app login flow and instead use the client credentials.
Fixes # [sc-17447]
> Adding client login and modifying login logic

- changelog.d/20220831_121901_LeiGlobus_funcx_endpoint_logout_sc_18074.rst
- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/conftest.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/funcx/sdk/login_manager/protocol.py
Added logout subcommand to funcx-endpoint.  See linked SC: https://app.shortcut.com/funcx/story/18074/support-funcx-endpoint-logout
There is a slight modification to funcx_sdk.funcx.sdk.login_manager.manager.logout to return bool instead, plus see the associated TODO comment.
I expect to remove the TODO in LoginManager.logout and funcx_endpoint.cli.logout_endpoint before merging (the TODOs are to ensure PR comment)
*EDIT* all the TODOs were removed along with most of the proposed (and rejected) extra logic/params.
> add logout to funcx endpoint

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
Remove the map_run() method and associated /submit_batch post as they are obsoleted (and non-functional) with the new batch run API.
> remove obsolete map_run and submit_batch

- funcx_sdk/funcx/serialize/base.py
- funcx_sdk/funcx/serialize/concretes.py
- funcx_sdk/tests/integration/test_serialization.py
We have a few ways of serializing functions.  Not all of them handle all functions (mismatching PY versions, decorated fns, indented functions etc).  Of the 3 general categories of failures:
1) Failure on serialization (previously handled by failing over to next method)
2) Failure on deserialization (this PR and with removed off_process_checker)
3) Failure on running the method (we can't do much about this type)
We have agreed that we can only assist with 1) and 2)
This is an attempt to add 2) back for a limited set of 2) failures
> Add combined payload serialization from multiple methods

- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
Not only was this misleading - stating that the default was `"prod"` when it meant that it defaulted to `None` which was converted to `"prod"` eventually - the eventual string it reported was wrong. If you trace the code all the way through, it's actually `"production"`. 
> Fix endpoint configuration docstring default

- changelog.d/20220907_150940_chris_dont_require_client_argument.rst
- funcx_sdk/funcx/sdk/executor.py
Motivated by recent work on updating the tutorial notebook.
If we want to push the executor as the default interface to use, we shouldn't muddy the waters by also requiring users to create a `FuncXClient` and pass it in, if we can assume a sensible default.
> Don't require users to pass in a `FuncXClient` when creating a `FuncXExecutor`

- funcx_endpoint/funcx_endpoint/logging_config.py
Ensure that the foreground color is *also* reset -- for example, in the case of an error message, which in the current scheme, only changes the background color.
> Reset after highlight

- docs/configs/polaris.py
- docs/configuring.rst
Includes the filesystems to mount in Polaris jobs. This is important when one is down and it needs to be removed for jobs to start.
Also removes an obsolete reference to EDTB login nodes that is no longer useful.
> Add filesystem options to the Polaris example config.

- changelog.d/20220831_210735_kevin_add_submitted_task_counter.rst
- funcx_sdk/funcx/sdk/executor.py
While developing, I have had need to know whether tasks have *actually* been sent upstream, or some bug or interruption has prevented that.  Putting on my end-user hat, there are situations where I would also would want this information.  We have it, so _share it_.
> Add `.task_count_submitted` to FuncXExecutor

- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
The update to message packing broke the management of ManagerLost exceptions. This PR changes the interchange's managerlost handling to reflect the message pack updates. We now mimic function exceptions using the two builtin get_error_string and get_error_message functions.
Fixes #890
> Update the ManagerLost error handling to mimic function exceptions

- changelog.d/20220920_114304_kevin_refactor_executor_task_future_association.rst
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_executor.py
The Tasks and associated futures are created at the same time and can always be co-located.  There's no need to artificially separate them, and then have to look up one or the other.  Keep them together through the queue, and remove the unnecessary dict.
Meanwhile, with the change to `.get(block=False)` there's no more need for the coalesce delay.  Outside of egregious limits (e.g., a *very* high batch_size or a *very* small time limit), the timeout check is useless.
> Remove unnecessary data structure

- changelog.d/20220921_161549_kevin_serialize_access_to_sqlite.rst
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/funcx/sdk/login_manager/tokenstore.py
SQLite helpfully defaults `check_same_thread` to `True`, which ensures that all access to the DB happens on the same thread that created the DB connection. But that's not *actually* the important bit.  What's important is that all transactions through that connection with the DB are *serialized*.  Serialized transaction calls are part of how SQLite guarantees that the underlying tables keep their integrity -- ensuring that all calls come from the same thread is a means to that end.  If we externally guarantee that our accesses to the DB are serialized, then we don't need SQLite to check that access are from the same thread.
Thus, we ensure that we do this for the important SQLite interactions with an access lock.
Fixes #907 ("Renewing auth token fails in multi-threaded applications") …
> Serialize access to sqlite

- changelog.d/20220908_132611_LeiGlobus_websocket_queue_flag_sc_15524.rst
- funcx_endpoint/setup.py
- funcx_sdk/funcx/sdk/batch.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_client.py
Add a flag on whether to create a websocket queue per task batch submission.
See https://app.shortcut.com/funcx/story/15524/add-flag-to-not-created-websocket-queue
Discussion needed first.  TBD after completion.
> add create_websocket_queue flag

- funcx_sdk/funcx/sdk/login_manager/manager.py
A reentrant lock might work as well, but we can also just be more judicious. Choose the latter here and only take the lock when we absolutely need to. Require less bookkeeping until we need it.
> SC-19182 Fine-tune where we take the lock

- docs/Tutorial.rst
- docs/endpoints.rst
- docs/executor.rst
- docs/index.rst
- docs/quickstart.rst
- docs/sdk.rst
Update readthedocs to mention pipx and venv instead of using pip to install funcx and funcx_endpoint
> Venv environment doc changes

- changelog.d/20220930_151519_kevin_batch_add_interface_cleanup.rst
- funcx_sdk/funcx/sdk/batch.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_client.py
`function_id` and `endpoint_id` are now enforced by being positional arguments, rather than manually enforced kwargs.  This further enables typing of them (`str`).  After implementing, also remove vararg delineation of function args and kwargs, completely isolating them from the `Batch.add()` method's signature needs.
My read is that this class is mostly used internally, so this change, while technically breaking, should affect very few users in the wild.
- Breaking change
> Refactor `Batch.add()` interface

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/tests/integration/funcx_endpoint/executors/mock_executors.py
- funcx_endpoint/tests/unit/test_highthroughputinterchange.py
The HTEX's internal interchange currently creates an endpoint for the sole purpose of querying for container information, but this was hanging on my machine. After unsuccessful investigation into why it was hanging, the decision was made to simply pass the client to the interchange whole. This also solves the issue where the interchange's client always pointed to prod.
> Pass the HTEX interchange an existing FuncXClient

- smoke_tests/tests/test_running_functions.py
Fix the broken smoke test.  We forgot to make this change in the [`Batch.add()`](https://github.com/funcx-faas/funcX/pull/940) interface change.  Had intended to make it as part of PR #942, but that is on hold for about 2-weeks.  No sense in losing confidence in our tests over the delay, so ... fix it now.
> Address recent batch.add inteface change

- smoke_tests/tests/test_running_functions.py
The `Batch.add()` interface has recently changed, but the production test won't recognize that until we release the SDK to pypi.  Dev misses this because it pulls from the local filesystem.  Hmm.
Implemented solution: skip test until SDK v1.0.5 released, which should be right around the corner.
> Fix hourly smoketest

- changelog.d/20221015_134646_kevin_refactor_executor_constructor_signature.rst
- docs/conf.py
- docs/executor.rst
- docs/index.rst
- docs/quickstart.rst
- funcx_sdk/funcx/sdk/asynchronous/funcx_future.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/sdk/utils/__init__.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/funcx/version.py
- funcx_sdk/setup.py
- funcx_sdk/tests/conftest.py
- funcx_sdk/tests/integration/test_executor_int.py
- funcx_sdk/tests/unit/test_executor.py
- funcx_sdk/tests/unit/test_web_client.py
- funcx_sdk/tests/utils.py
- funcx_sdk/tox.ini
- smoke_tests/tests/test_running_functions.py
There are two main goals of this work:
1. More closely align with the super-class' signature and descibed behaviors
Previously, to submit a function to the executor, the interface was:
```python
def submit(self, function, *args, endpoint_id=None, container_uuid=None, **kwargs):
assert endpoint_id is not None
```
In other words, endpoint_id is required, and is intermingled with the function's arguments at the submit() call.  With this commit, the endpoint is part of the executor object itself and executing a function matches the super-class' signature:
```python
fxe = FuncXExecutor(endpoint_id=ep_id)
fxe.submit(fn, *fn_args, **fn_kwargs)
```
To further match the super-class' intent, this commit also introduces `__enter__()` and `__exit__()`, and follows the `.shutdown()` semantics (e.g., …
> Heavy FuncXExecutor refactor

- changelog.d/20221106_000523_kevin_remove_monkeypatch.rst
- funcx_sdk/funcx/sdk/login_manager/tokenstore.py
- funcx_sdk/setup.py
In PR #934 (2bae1dba02), we chose to monkeypatch an internal Globus SDK object. As of Globus SDK v3.13, that monkeypatch is no longer necessary.  Increase minimum Globus SDK version, and remove monkeypatch.
[sc-19020]
> Remove monkeypatching of sqlite adapter

- smoke_tests/Makefile
- smoke_tests/README.md
- smoke_tests/tests/conftest.py
- smoke_tests/tox.ini
Add two new `make` targets:
- `local_with_published_sdk` -- test with the published-to-pypi SDK code against the 'local' environment (that is `FuncXClient(environment="local")`)
- `local_with_dev_sdk` -- test the 'local' environment with the local SDK and endpoint changes -- note that this installs the local directory and so these changes might not have even been committed yet.
Makes use of two environment variables so as to ascertain the local setup:
- `FUNCX_LOCAL_ENDPOINT_ID` -- required; the id of a local _running_ endpoint.
- `FUNCX_LOCAL_KNOWN_FUNCTION_ID` -- a "known" function that returns hello world.  (See tests for more information.)  This is optional, but if not set, then those tests will be skipped.
[sc-20002]
- Code …
> Enable smoke tests against a LOCAL setup

- docs/configs/worker_pinning.py
- docs/configuring.rst
Adding a bit of documentation with examples for pinning workers to GPUs and similar devices.
[sc-18312]
> Adding a doc entry and example config for accelerator pinning.

- smoke_tests/tests/test_s3_indirect.py
- smoke_tests/tests/test_version.py
Turns on the status check for an endpoint given it has been fixed.
> Turn endpoint status test back on

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Checks if `result` is defined before referencing it in the exception handling. It looks like `multiprocessing.queue.get()` is failing (in my case on macOS 13.0 with py3.9) from an OSError which is pretty suspect. 
Fixes #964
> Check if `result` is defined before logging.

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/register_endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/unit/test_register_endpoint.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/tests/unit/test_web_client.py
Add multi-tenant flag to local config.py and as an (currently hidden CLI) configure --multi-tenant option when creating the same.  The flag will be sent to web-service when creating/registering an endpoint.
It is expected that if an endpoint is re-registered with a different flag suibsequently, the web service will return a conflict error.
Note that one of the considerations is where to add the flag as a required parameter and where to have a False default.  This is to maximize backwards compatibility (in methods, sdk, tests) when it's appropriate.
> Sc 19617 feature flag endpoints with multi tenant

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
Auth will happen the first time _any_ endpoint is started.
[sc-20409]
> No need to auth during *configure* stage

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
Biggest pieces are:
- Move funcx configuration logic to `cli.py`
- Make many of the Endpoint management methods static
- Agree that the endpoint name *is* the configuration directory name (`ep_dir.name`)
- Remove use of `click` from the Endpoint class -- was a leaky abstraction detail
- Use pathlib.Path to improve clarity
On the way to sc-19623.
> Refactor some Endpoint management code

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
stop_endpoint needs to read config.py now when the --remote option is specified, and will use it to create a FuncXClient for the env/service, as start_endpoint does.
This refactors that creation a bit to make it easier to use, and this fixes an issue where the incorrect environment might be used as the config specifies.
Note that this is a fairly simple change - moving some pre-existing code into a method and adding a call to it in stop_endpoint, plus some changes to mocking in tests to make sure everything passes.  There isn't any 'new' logic.
> refactor funcx client creation for endpoint stop

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
We never tested this branch so missed that this would never work.  Test at least one of the branches ... but the other `except` branch is yet untested. For a future PR.
> Handle endpoint locked response correctly

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
(Note that this builds on a previous PR that included some refactoring, will be rebased to main once the other PR is merged)
Fixes an issue where checking the daemon.pid file never returns exists=True, and also handles Locked and InUse api return codes in the appropriate exception type (GlobusApiError not FuncXResponseError)
> fix endpoint start error handling and pid exist check

- changelog.d/20221212_155851_30907815+rjmello_stop_ep.rst
- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
A method is needed in `FuncXClient` to remotely stop an endpoint. The preferred way to accomplish this is to temporarily block connection attempts from the remote endpoint, ultimately causing it to stop.  Since the `lock_endpoint()` method already exists and does exactly this, it is being renamed to `stop_endpoint()` to more clearly describe what the method is accomplishing.
[sc-9584]
> Repurpose lock endpoint method to stop endpoint

- funcx_sdk/funcx/sdk/executor.py
PR #990 introduces changes that make `mypy` miss the fact that `function_id` is of type `str` and NOT `None` at this point.  Help `mypy` along ...
> Small, no-change refactor to unclutter upcoming PR

- changelog.d/20221216_103757_30907815+rjmello_invalid_grant.rst
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/login_manager/__init__.py
- funcx_sdk/funcx/sdk/login_manager/decorators.py
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/tests/unit/test_login_manager.py
Invalid refresh tokens will be handled when a `FuncXClient` object is instantiated and when an API auth error is raised by a `FuncXClient` method. The former is accomplished by directly validating the tokens against Globus Auth, and the latter by catching `AuthAPIError` exceptions. If a token is found to be invalid, a new auth flow will be initiated.
[sc-20480]
> Handle invalid refresh tokens

- .github/workflows/hourly.yaml
- .github/workflows/smoke_test.yaml
A simple solution to the tests not timing out. Add a 10 min timeout to the workflow calling the tests.
> Timeout tests after 10 mins

- funcx_endpoint/funcx_endpoint/executors/high_throughput/container_sched.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange_task_dispatch.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/worker_map.py
- funcx_endpoint/funcx_endpoint/logging_config.py
- funcx_endpoint/funcx_endpoint/strategies/kube_simple.py
- funcx_endpoint/tests/integration/funcx_endpoint/conftest.py
The initial change is to the `Interchange.start()` method signature, which then opens a number of minor items to mypy.  One of those changes is the `log.trace` method; address by subclassing the logger.  Mypy has learned a little bit since ~a year ago, so the only trickery here is in the `import`:
from funcx_endpoint.logging_config import FXLogger
log: FXLogger = logging.getLogger(__name__)  # type: ignore
`logging_config.py` tells the logging system to return FXLogger, but `mypy` doesn't infer that deeply.  So, promise it that "we know what we're doing," and then `.trace()` can exist.
The other changes are of the "while here" variety:
- don't waste time interpolating strings for messages that won't be emitted!
- cache lookups for easier reading and to simplify some mypy-isms
- use …
> Add a small amount of typing

- funcx_sdk/funcx/sdk/login_manager/login_flow.py
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/tests/unit/test_login_manager.py
For 99% of expected use-cases, there is no need to check the authorization status: the user will have already authed.  Consequently, there is no need to burden the Auth server with superfluous calls, nor is there a need to add latency to new FuncXClient instantiations: strictly and _only_ handle `AuthAPIError`s in the decorator.
[sc-20480]
> Do not pre-emptively test auth status

- changelog.d/20230106_132001_yadudoc1729_limit_interface_binding.rst
- docs/configs/bebop.py
- docs/configs/cooley.py
- docs/configs/frontera.py
- docs/configs/perlmutter.py
- docs/configs/polaris.py
- docs/configs/theta.py
- docs/configs/theta_singularity.py
- docs/configs/uchicago_ai_cluster.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/tests/unit/test_bad_endpoint_config.py
Rather than have ZMQ bind to all interfaces with `tcp://*:port` this PR uses the address specified via config to limit binding to a specific interface. The one major downside to this is that the bind requires either an IP address or an interface name, and every config example that uses `address_by_hostname()` is going to be broken following this change.
Ref: http://api.zeromq.org/2-1:zmq-tcp 
@ericmjonas, Could you give this a test run on frontera, please? 
Fixes # [sc-20670]
> Limit interface binding

- docs/quickstart.rst
This PR updates the quickstart to clarify that the binder link is to a jupyter notebook.
> Doc update to clarify that the binder link is a hosted jupyter notebook.

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/result_store.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
Following the thread that the name _is the same as_ the EP configuration directory, there's no need to pass it around.  Since we're already passing the configuration directory around, just calculate the name when/if needed.
While here, move to some more use of `pathlib`, which engenders a nice simplification in `register_endpoint` as well.
> Remove unnecessary use of EP name

- changelog.d/20230113_121808_kevin_fail_count_then_bail.rst
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/tests/unit/test_endpointinterchange.py
Rather than continuously retrying, shutdown the endpoint if a heartbeat log message iteration is not achieved after N attempts.
Arbitrarily choose N=5 as default.
> Shutdown after N failures

- docs/configs/polaris.py
An ALCF update has made it mandatory for funcX endpoints to include a new PBS command specifying -k doe. This adds it to the docs. Endpoints do not work with polaris queues without it.
> Include the -k doe flag for polaris

- funcx_sdk/funcx/errors/error_types.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_client.py
This fixes an issue where raising GlobusAPIError didn't have the correct argument, so now raising a locally defined FuncX error instead.
Also, refactored current usage a bit to centralize defaulting to 'now' for completion_time of the error in the class itself instead of all its callers.
> funcx error fix

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
Adds a method to the `web-client` and to the `client` for accessing the new `GET /endpoints/{uuid}` API endpoint introduced in https://github.com/globusonline/funcx-services/pull/211.
[sc-20196]
> Add methods for retrieving endpoint metadata

- .github/workflows/ci.yaml
Fixes [failing safety check](https://github.com/funcx-faas/funcX/actions/runs/3969447847/jobs/6803954222) ([CVE-2022-40897](https://pyup.io/v/52495/f17/)), and updates our overall usage of the `setup-python` action
> Fix safety check

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
Try to *first* collect the task_id so as to be able to be more robust in error handling: if we're not going to be able to process the task, let the end-user's waiting future  know about it, rather than silently dropping it.
> Robustify task processing

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange_with_rabbit.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
- funcx_endpoint/tests/unit/test_endpointinterchange.py
- funcx_sdk/setup.py
The last remaining use of the FuncXClient was within the *executor* interchange, to enable looking up container location information.  The required location information is now passed along with each task message, so modify the logic to look there -- the key change is in `messages_compat.py`.  Everything else is just "cleanup."
[sc-19623]
> Remove use of FuncXClient from interchanges

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
The name is entirely contained within the configuration directory -- the filesystem directory basename.  We don't use it, so completely remove `Endpoint.name` (i.e., `self.name`) and pass along the pathlib.Path endpoint config dir.
> Completely remove Endpoint.name

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
Make use of setproctitle (thank you Postgres authors!) so as to more easily discern what processes are in the process table.  Help administrators help endusers with errant processes, and help endusers find their processes with an easier grep or visual search.
Example htop output:
[sc-19623]
> More easily discern EP processes in process table

- changelog.d/20230124_175331_kevin_readd_atexit_handler_to_fxexecutor.rst
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/integration/test_executor_int.py
- funcx_sdk/tests/unit/test_executor.py
The normal `atexit` handler will not work because there are non-daemon threads still about at script end.  Consequently, use a background thread "watcher" to watch the *main* thread and signal all known executors to shutdown.
[sc-21525]
> Auto-shutdown FuncXExecutor objects at script end

- changelog.d/20230126_125531_kevin_reteach_executor_how_to_specify_containers.rst
- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_executor.py
The ability for the FuncXExecutor to use containers was not *completely* lost in the recent FuncXExecutor refactor (81811a97e0), but was not enabled in the default workflow.  In particular, the expectation from the refactor is that the `endpoint_id` and `container_id` are specified as FuncXExecutor attributes, and _not_ as part of `.submit()`.  But that implies that `.submit()` will transparently use them -- it mistakenly did not.
Previously, one would have had to use `.register_function()` manually and know to specifically specify the `container_uuid` kwarg (eww!), or manually associated the function with a container via the FuncXClient methods.  Further, the same function could only be associated with a single container.  Addressed by updating the internal function registry to also take …
> Teach FuncXExecutor to use container_id natively

- changelog.d/20230126_135722_LeiGlobus_whoami_sc_21319.rst
- funcx_endpoint/funcx_endpoint/cli.py
- funcx_sdk/funcx/sdk/login_manager/whoami.py
- funcx_sdk/funcx/sdk/utils/printing.py
- funcx_sdk/setup.py
- funcx_sdk/tests/unit/test_printing.py
- funcx_sdk/tests/unit/test_whoami.py
Adding the 'whoami' command to the cli.
Has a '--linked-identities' option to show all identities in "identity_set".  Includes a think wrapper around texttable to print the output, modeled after the endpoint printing, but put in the SDK side.  TODO in another PR is to consider merging the two, if it makes sense.
The key business logic is in login_manager.whoami.py, parsing the responses from auth_client.oauth2_userinfo() and  auth_client.get_identities(ids=user_id), with some minor caching of id:profile_info in a local dict named user_info.
An example usage is as follows:
```
$ funcx-endpoint whoami
+----------------+----------+--------------------------------------+---------------------------+
|    Username    |   Name   |                  ID                  |         Auth Time …
```
> Whoami sc 21319

- changelog.d/20230126_135722_LeiGlobus_whoami_sc_21319.rst
- funcx_sdk/funcx/sdk/login_manager/whoami.py
- funcx_sdk/funcx/sdk/utils/printing.py
- funcx_sdk/tests/unit/test_whoami.py
> Just thinking "out loud" ... would an example invocation be in order? Or a link to the appropriate documentation page/section?
Added example in changelog
> Is there in sharing the underlying exception in .debug()? Just thinking about the "unexpected" failure. (As opposed to the expected failure, right? ;-) ) Perhaps something like:
Didn't use logger at all in this file, so didn't do that, but sure, why not.
> Would a (Hint: use the --logout flag) pointer be of use to the end-user? I'm thinking of something like:
Added
> The funcx-endpoint list functionality puts the static-width fields first and the variable-width fields on the right. 
I used the order as globus-cli did username, name, ID.  On Josh's suggestion to keep to that, I added 'email' and removed Auth Time.
> And then this …
> Whoami PR comments

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
Enable a parent process to securely pass credentials to the endpoint, removing the need for the endpoint to instantiate a FuncXClient (and thereby removing the need for user credentials).
[sc-19623]
> Teach endpoint to read credentials via stdin

- changelog.d/20230202_002915_kevin_htex_interchange_bad_manager_iteration_fix.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Broken in `fadc76b2be`&nbsp;&mdash;&nbsp;an Executor unused for too long will trigger cleanup of the Interchange data structures.  The refactor in the ancestor commit inappropriately modified the data structure traversal.  Fix the traversal.
[sc-21819]
> Correct data structure traversal

- funcx_endpoint/funcx_endpoint/strategies/simple.py
This basically converts numerous log lines like:
....ple:82 _strategize Provider status: [<parsl.providers.base.JobStatus object at 0x7f579e736f50, state=2>]
....ple:82 _strategize Provider status: [<parsl.providers.base.JobStatus object at 0x7f579e737730, state=2>]
....ple:82 _strategize Provider status: [<parsl.providers.base.JobStatus object at 0x7f579e737010, state=2>]
....ple:82 _strategize Provider status: [<parsl.providers.base.JobStatus object at 0x7f579e736ec0, state=2>]
[etc.]
To a singular:
....ple:82 _strategize Provider states: 2
And it won't repeat again until the state *changes* -- the insight being that we care about the underlying *state*, not the JobStatus object.  :grimace:
> Reduce log noise from JobStatus updates

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
We want to be able to force&nbsp;&mdash;&nbsp;despite a misconfiguration&nbsp;&mdash;&nbsp;that an administrator can see a hierarchical view of all Globus Compute endpoints.  In particular, if the parent process crashes, the child processes should gracefully shutdown rather than hang around as orphans.  Thus, implement `--die-with-parent` as a flag to the cli to indicate that if the parent PID changes&nbsp;&mdash;&nbsp;so the child process was reparented or the parent process died&nbsp;&mdash;&nbsp;then it is time to shutdown.
[sc-19623]
> Implement flag to maintain process tree

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/tests/unit/test_client.py
While testing related to https://github.com/globusonline/funcx-services/pull/270 the 'reason' may not be returned from the web client as part of batch results.  This was causing some issues with FuncxTaskExecutionFailed requiring a str as reason instead of None, and also FuncxTaskExecutionFailed(None) isn't ideal to show to the user.
Added a string in place in case 'reason' is missing.
> Add logic in case error reason non existent

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
ALCF's PBS cluster requires that stdin be open when engaging with it. To that end, we dup2 stdin to /dev/null and set it in the daemon context. This allows funcx endpoints to perform qstat and qdel operations without error.
Fixes # [sc-21508]
> Add stdin to the daemon context

- changelog.d/20230221_104931_30907815+rjmello_delete_ep.rst
- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
The `funcx-endpoint delete` command now deletes the endpoint both locally and from the web service. This includes the `--force` flag, which ensures the endpoint is deleted locally even if the web service returns an error or is unreachable.
Also, if a user attempts to start an endpoint that has already been marked as deleted in the web service, the process will exit with an error.
[sc-20468]
> Delete endpoints from web service via CLI

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
This is mostly to address test cleanup, but also going for "first user experience" despite a malformed setup (i.e., "weird umask").
The item of note for local-dev tests is that pytest was unable to cleanup after itself, resulting in messages like:
```
[...]/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-kevin/garbage-00f00fd5-4e73-469f-9354-5a5e492ee7d1
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-kevin/garbage-00f00fd5-4e73-469f-9354-5a5e492ee7d1'
warnings.warn(
```
[sc-22042]
> Also include config.py in umask handling

- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/messages.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
- funcx_sdk/setup.py
Incorporates the change from https://github.com/funcx-faas/funcx-common/pull/78, and mirrors that change in endpoint-internal message structures.
[sc-22365]
> Rename `EPStatusReport.ep_status_report` to `global_state`

- funcx_endpoint/tests/unit/test_endpoint_unit.py
The weird permission test plays havoc with pathlib's assumptions.  Help it along.
With or without this PR, the tests don't fail.  However, Pytest fails to cleanup the detritus, reporting:
```
.../.tox/py/lib/python3.10/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-USER/garbage-53fc2dc1-949f-457e-9fd1-6cee6eb1c32e/test_endpoint_config_handles_u0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_endpoint_config_handles_u0'
warnings.warn(
```
That message is repeated for each "garbage-" directory, so for as many times as one has run pytest.
> Help test clean up after itself

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/tests/unit/test_endpointinterchange.py
And refactor the logging case to a single-branch&nbsp;&mdash;&nbsp;always do it!
The traceback in question:
```python
1678414266.450186 2023-03-09 21:11:06 ERROR MainProcess-3390136 MainThread-139902600003584 funcx_endpoint.endpoint.interchange:303 start Unhandled
exception in main kernel.
File "funcx_endpoint/endpoint/interchange.py", line 291, in start
self._start_threads_and_main()
File "funcx_endpoint/endpoint/interchange.py", line 323, in _start_threads_and_main
self._main_loop()
File "funcx_endpoint/endpoint/interchange.py", line 347, in _main_loop
with results_publisher:
File "funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py", line 49, in __exit__
self.close()
File "funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py", line 88, …
```
> Remove an unnecessary traceback

- funcx_endpoint/funcx_endpoint/logging_config.py
`--log-to-console`&nbsp;&mdash;&nbsp;together with `--debug`&nbsp;&mdash;&nbsp;colorizes the log messages before emitting them to stdout.  However, in searching for uuid strings, it inadvertently changed the data _within passed data structures_.  Address this by copying before munging the strings.
> Avoid modifying data in structures

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/command_queue_subscriber.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/__init__.py
- funcx_endpoint/tests/conftest.py
- funcx_endpoint/tests/unit/test_command_queue_subscriber.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
- funcx_endpoint/tests/unit/test_endpointmanager_unit.py
- funcx_endpoint/tests/unit/test_utils.py
- funcx_endpoint/tests/utils.py
The `EndpointManager` connects to the Globus Compute web services to register as a multi-tenant endpoint, and then listens for commands from upstream via an AMQP queue.
Commands are verified via:
- Command names must follow the regex `^[A-Za-z][0-9A-Za-z_]{0,99}$`
- Roughly, a valid, non-private Python method name
- Commands must have an implemented class method on `EndpointManager`
- Commands must be associated with a Globus username
- The local machine must have a mapping of the Globus username to the local username
After validation (the above 4 bullet points), the command is then forked to a child process, and that child process drops all privileges by becoming the local user (i.e., `os.setres*id()`)
After forking, child processes are not double-forked before execing, with the intent …
> Implement EndpointManager

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
Ensure that the endpoint uuid is always printed to the TTY.  This was never tested, and worked by chance until a few months ago.  Turns out that folks largely rely on this as a shortcut over delving into the logs, so ensure that it is printed to the console.
[sc-22869]
> Move print statement to before daemonization

- funcx_endpoint/funcx_endpoint/cli.py
No need to duplicate the `--endpoint-uuid` definition, and now allow `--die-with-parent` to be an argument for `funcx-endpoint restart`.
I haven't learned `click` well enough to further DRY it out -- in particular, I don't like that the method arguments are duplicated between `start()` and `restart()`.  Not a task for today.
- Bug fix
> Teach `restart` the same CLI args as `start`

- helm/README.md
- helm/boot.sh
- helm/funcx_endpoint/templates/endpoint-deployment.yaml
Set the `endpointName` to the desired name.
N.B., funcX uses the configuration directory name as the endpoint name; unfortunately, spaces are not handled robustly throughout.  For the time being then, an endpoint name with spaces will very likely fail.
[sc-22872]
> Enable overriding of kubelet endpoint name

- docs/sdk.rst
Adding documentation about the funcX scope re: https://app.shortcut.com/funcx/story/22600/add-required-scope-to-api-documentation
Is there a better page to put this?
[sc-22600]
> add note about scope for globus auth

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/tests/unit/test_endpointmanager_unit.py
Coming out of a post-merge review and walk-through, there was some fear that just ensuring the method existed on the class and was not private was not enough of a safe-guard, API wise.  An additional clue to the next dev when creating new functions is that they must now be prefixed with `cmd_`, which means the dev is aware of what they're implementing, and it will be much, much more difficult for a rogue execution to slip through.
Note that this is *in addition* to the web-side validation, which includes a specific allow-list (rather than a catch-all, like a regular expression).
[sc-19623]
> Prefix commands methods with `cmd_`

- funcx_sdk/funcx/sdk/login_manager/client_login.py
The `client_id` is not confidential, and, given our learned experience yesterday, would have been a helpful indicator as to what was mis-copied and where.
> Give more information in error message

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
As of https://github.com/globusonline/funcx-services/pull/318, we no longer use `function_source` on the service side. This cleans that up.
[sc-10168]
> Stop sending function source code on registration

- docs/index.rst
Put back the navigation sidebar, which was unintentionally removed in #1071.
> Put docs sidebar navigation back

- changelog.d/20230403_125849_kevin_broken_endpoint_for_new_users.rst
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- smoke_tests/README.md
- smoke_tests/tests/sh/runner.sh
- smoke_tests/tests/sh/test_endpoint.sh
- smoke_tests/tox.ini
The fix is simple: remove the errantly added five lines in `endpoint.py`. However, testing this particular scenario proved difficult in standard pytest, so instead, opt for an outside-of-pytest approach: simple shell scripts.
This is not a complete solution for non-Pytest tests&nbsp;&mdash;&nbsp;in particular, there's currently no distinction between prod and dev or local&nbsp;&mdash;&nbsp;but there's also not a current need for it.  Assume we'll update the `runner.sh` (and specific tests) as/when the need is obviated.
[sc-23429]
> Re-allow endpoints to instantiate credentials

- changelog.d/20230327_121223_chris_remove_sdk_support_for_function_search.rst
- changelog.d/20230330_005243_kevin_max_idle_s_after_work.rst
- changelog.d/20230403_125849_kevin_broken_endpoint_for_new_users.rst
- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/version.py
Preparing release; includes changes since v1.0.12.  Most notable: a stdin issue preventing the native login flow when initiated by the endpoint.
> Bump versions for release

- release.sh
The new compute release.sh references an earlier directory structure, and needs to be updated from globus_compute_sdk and globus_compute_endpoint to compute_*
> Fix release version check

- .github/ISSUE_TEMPLATE/bug_report.md
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
- compute_sdk/setup.py
- compute_sdk/tests/unit/test_login_manager.py
- docs/funcx_upgrade.rst
- helm/README.md
- helm/boot.sh
- smoke_tests/tests/conftest.py
- smoke_tests/tests/sh/test_endpoint.sh
The `.funcx` directory is now `.globus_compute`. If `.funcx`  is present when `globus-compute-sdk` is installed and used, we rename it and create a symlink to avoid breaking existing workflows. Otherwise, we create a fresh `.globus_compute` directory.
> Note:  The changelog for this work and #1067 will be created in a separate PR.
[sc-22439]
> Rename .funcx dir to .globus_compute

- docs/configs/midway.py
- docs/configs/midway_singularity.py
Updates the two midway example configs in the docs to use address_by_interface.
> Change to address by interface for midway config examples.

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
- compute_sdk/tests/unit/test_login_manager.py
To ensure we properly handle the endpoint configuration directory when using the endpoint CLI (see #1086), we call the relevant SDK function when initializing a `CommandState` object. 
[sc-22439]
> Use util from SDK to initialize endpoint config dir

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
This PR removes an obsolete class var that HTEX no longer needs the funcx_service_address with changes from PR #1022
I'm breaking up PR#1057 into smaller bits on @khk-globus 's recommendation.
> Removing obsolete classvar

- compute_funcx/endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
The old funcx_endpoint package used Manager, not FuncXManager.  (Confusing because FuncXWorker has the prefix).
[Old funcx_manager.py: ](https://github.com/funcx-faas/funcX/blob/3c30f16ad0c6a9f05b21262d7e2def784995fd19/funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py)
[Old funcx_worker.py:](https://github.com/funcx-faas/funcX/blob/3c30f16ad0c6a9f05b21262d7e2def784995fd19/funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py)
When adding backwards compatibility we need to match what we used before.  This was a typo in the rebranding PR.
> Fix typo in class name from funcx_endpoint

- helm/boot.sh
The rebrand (9706b5f5ca2e84581b007c6c38036709eb674b06), mistakenly put back the *old* line.  Undo the undo!
> Undo rebrand-lost change

- compute_endpoint/tox.ini
- compute_funcx/endpoint/tox.ini
- compute_funcx/sdk/tox.ini
- compute_sdk/tox.ini
While rebuilding my local dev env following the compte rebranding, I installed the latest `tox`, which seems to completely ignore the old `whitelist_externals` field in favor of `allowlist_externals`.
This update fixes the issue by adding an additional field.
> Add `allowlist_externals` in addition to `whitelist_externals` in `tox.ini`s

- compute_endpoint/globus_compute_endpoint/executors/high_throughput/executor.py
They key detail of interest here is that these arguments (e.g., endpoint_id) are not nominally available when the Executor is initially configured&nbsp;&mdash;&nbsp;that is, in `config.py`, well before the Interchange has been initialized or started.
Note: this is precursor work to ease review of upcoming PRs.
[sc-17278]
- New feature (non-breaking change that adds functionality, but currently WIP)
> Update HTEX .start() with add'l params

- compute_endpoint/setup.py
This PR updates the parsl requirements for funcx_endpoint to parsl#2629. This brings in much better cleanup behavior in tests due to proper handling of signal handler inheritance in the `parsl.htex.interchange`.
This is pulled from the stack of changes in #1057 
> Updating parsl req to 2023.03.27 

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
The code previously thought it _might_, one day, have support for multiple executors.  That has not happened in practice, so now remove some unnecessary logic.
[sc-17278]
> EPInterchange uses exactly one executor

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/executor.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
No sense in shunting the messages out of process only to return again.  Just use a `queue.Queue`.
While here, add some typing.  (Mypy demanded it, actually.)
[sc-17278]
> Refactor to queue.Queue from mp.Queue

- changelog.d/20230420_045259_30907815+rjmello.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Required fields were missing from the final endpoint status update that is sent when an endpoint is gracefully shutting down, causing issues when getting the status of an endpoint.
> Add required fields to final EP status report

- changelog.d/20230418_150208_yadudoc1729_app_timeout.rst
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/worker.py
- compute_endpoint/tests/unit/test_worker.py
This PR adds support for timing out tasks that exceed a configurable task timeout set globally at the endpoint.
The timeout is set using `GC_TASK_TIMEOUT` env var to be set on the endpoint. When a task exceeds the timeout
an exception is injected into it and this results in the task showing up as failed on the client side like this:
```
File "/Users/yadu/.globus_compute/gc_1/tester.py", line 15, in <module>
print(f"Result : {x.result()}")
File "/Users/yadu/opt/anaconda3/envs/funcx_py3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
return self.__get_result()
File "/Users/yadu/opt/anaconda3/envs/funcx_py3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
raise self._exception …
```
> Support for timing out tasks at the worker 

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
The change in 7c93e631dad9ec5a1eeaece1cac73539d66dad5c forgot that non-Results also come through the `results_passthrough` queue, and blithely ignored messages with no task_ids.  This is incorrect, and temporarily disabled the endpoint's ability to pass EPStatusReports.  Addressed, and added an expected-case automated test.
> Fix recently introduced bug

- docs/actionprovider.rst
This PR updates the Action Provider input/output schema to add what the new AP does.
You can see a version of the doc at https://globus-compute.readthedocs.io/en/latest/actionprovider.html  (currently linked to a doc branch)
See story https://app.shortcut.com/funcx/story/23537/document-the-new-action-provider-s-input-and-output-schemas
*NOTE* After approval, I'll wait to merge this until compute.actions.globus.org is live, after the ingress modification.
> action provider schema input output update

- docs/funcx_upgrade.rst
Didn't realize that auto-generated links are auto lower cased.
> change capitalization for link in upgrade doc

- Dockerfile-endpoint
- helm/bashrc
Main motivation: muscle memory with `ll`, but also enable color prompt&nbsp;&mdash;&nbsp;a minor editing of the default skeleton bashrc file.
While here, also slightly streamline the Dockerfile and cleanup after the install.
- Developer nicety
> Add bashrc to Docker image

- changelog.d/20230421_111659_kevin_address_concurrent_data_structure_modification.rst
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
Without this lock in place, was getting the following traceback while attempting to run a large number of noop tasks (e.g., 100k):
```python
Process Executor-Interchange:
File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/.../globus_compute_endpoint/executors/high_throughput/interchange.py", line 1161, in starter
ic.start()
File "/.../globus_compute_endpoint/executors/high_throughput/interchange.py", line 958, in start
del self.task_status_deltas[r["task_id"]]
KeyError: '388a6642-2086-4d04-92dd-ed3a5396f77e'
Exception in thread STATUS_THREAD:
File …
```
> Lock-prevent concurrent modification

- compute_funcx/sdk/funcx/sdk/client.py
- compute_funcx/sdk/funcx/sdk/executor.py
- docs/changelog_funcx.rst
For some users who import FuncXClient and FuncXExecutor from the package paths directly instead of 'from funcx import X', we should add convenient import as shortcuts as well.
See slack thread https://funcx.slack.com/archives/C017637NZFA/p1682438637004849 for details.
``from funcx.sdk.client import FuncXClient`` and ``from funcx.sdk.executor import FuncXExecutor`` should both work using the wrappers.
> add import as for FuncXClient and FuncXExecutor

- compute_endpoint/globus_compute_endpoint/providers/kubernetes/kube.py
The helm chart faithfully exports the `GC_TASK_TIMEOUT` variable to the endpoint's environment, but the workers weren't receiving that variable.
The implemented fix is a hard-coded list of environment variables (okay, a list of length 1) to check.  If passing information from the parent pod (the endpoint) to the child pods (the workers) becomes an issue in the future, the intended approach is to "deal with it then" in a more complete way.  For now, then, though not ideal, this commit is "good enough."
[sc-23725]
> Pass GC_TASK_TIMEOUT to instantianted pod

- helm/README.dlhub
- helm/dlhub_values.yaml
The former DLHub endpoint deployment workerInit was not playing well with the funcX 2.0.x compatibility library.  This pegs it at 1.0.13.
This is, essentially, a documentation change, as it adds a small README and changes the dlhub_values.yaml used to deploy the DLHub funcx endpoint.
> Dlhub deployment version 0.3

- changelog.d/20230421_102543_30907815+rjmello_custom_compute_dir.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
- compute_sdk/tests/unit/test_login_manager.py
Enable users to specify a custom Globus Compute directory (i.e., ``.globus_compute/``) via the environment variable ``GLOBUS_COMPUTE_USER_DIR``.
[sc-23683]
Fixes [#1089](https://github.com/funcx-faas/funcX/issues/1089)
> Support user-definable compute directory via env var

- changelog.d/20230503_101434_yadudoc1729_unfork_htex_2.rst
- compute_endpoint/globus_compute_endpoint/engines/__init__.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/unit/test_htex.py
- compute_endpoint/tests/unit/test_reporting_thread.py
- compute_endpoint/tests/unit/test_status_reporting.py
- compute_endpoint/tests/utils.py
This PR add a new base class `GlobusComputeEngineBase` that describes a common interface for all `engines` that can be plugged into a `globus_compute_endpoint`. The helper module implements a new adapter/wrapper function `execute_task` that takes a task that's wrapped as a `messagepack`ed object as input, executes the function inside it, and returns a `messagepack`ed result. 
This PR also provides 3 engine implementations of which the main contribution is the `parsl.executors.HighThroughputExecutor` which is wrapped as `GlobusComputeEngine` which is slated to replace the forked version in `globus_compute_endpoint.executors.HighThroughputExecutor`.
> Support for GlobusComputeEngines

- README.rst
- docs/quickstart.rst
Documentation update to reflect our move to Globus' jupyter hub. This removes the Binder badge from the README and updates the quickstart reference to binder.
Fixes # [sc-24212]
> Remove binder badge and replace quickstart reference

- README.rst
Fix a small mistake that leaves the `launch` tag on the README.
> Remove launch tag on README

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
The alias `ep_status_report` only remains so that older versions of the EP/SDK can still send heartbeats without issues - new code should use the actual field name `global_state`.
Related to https://github.com/funcx-faas/funcx-common/pull/87
> Use `global_state` instead of `ep_status_report` when constructing `EPStatusReport` objects

- changelog.d/20230523_125601_kevin_no_spaces_in_ep_name.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
We recently implemented provisions for users to have alternate _display names_ (via `--display-name` to the `configure` subcommand, or to manually alter the `config.py` top-level configuration item `display_name="some name"`), but didn't go the next step and enforce that users can't do something silly (but natural!) like adding spaces to the name.  This has repercussions later on in that Parsl is not very robust with it's path handling.  So, assume the better part of valor is to die early with an explanation for the user rather than cryptically failing later on with a traceback.
[sc-24521]
> Add user-facing EP name validation

- docs/configs/polaris.py
As part of some PR spring cleaning, addressing #951 by including the suggested update from `SingleNodeLauncher` to `MpiExecLauncher`, and showing off the ability to pin workers to GPUs via an optional user-opt.
> Update Polaris example config

- Dockerfile-endpoint
Since we no longer use CurveZMQ, the fix implemented in #610 is no longer required.
> Remove command to install pyzmq in EP Dockerfile

- changelog.d/20230531_120415_chris_remove_entry_point.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
Per [this Slack conversation](https://funcx.slack.com/archives/G016JMYST9C/p1683561274668059), this is an old, unused concept.
[sc-24274]
> Stop sending `entry_point` when registering functions

- changelog.d/20230522_134306_chris_user_selectable_serialization.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/serialize/__init__.py
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/integration/test_serialization.py
- smoke_tests/tests/conftest.py
Allow users to specify what serializer to use when constructing a client, and, by extension, an executor.
[sc-23912]
Note for reviewers - the meat of the changes are in two commits, c3d45e3e4ea2513824f0ff015bb0256073d1a44f and 7c9a8e11534d85984b2209c3147dd90a1515ea54. Suggest reviewing those individually, and then the PR as a whole.
> User selectable serialization

- changelog.d/20230531_120415_chris_remove_entry_point.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
Revert #1160 to fix smoke tests
> Revert "Stop sending `entry_point` when registering functions"

- changelog.d/20230518_130845_LeiGlobus_endpoint_uuid_argument_sc_24353.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
Before we support specifying the UUID in CLI commands, we should more explicitly prevent users from using an UUID as the endpoint name (which would generate a different actual UUID), as this is very confusing.
This PR changes the language on the configure command to emphasize that we are looking for a name, and also detects and prevents an UUID from being used as the endpoint name.
Linked story is a precursor to possible future feature allowing UUID or name (or display_name) to be used in commands.
Additionally, fix an issue when deleting endpoints that have been configured but not yet initialized, and skip going to the web-service when it isn't necessary.
Example sample output:
```
$ globus-compute-endpoint configure 9483834a-1633-4447-9ce6-f345fbb1ce7d
Usage: globus-compute-endpoint …
```
> change language for endpoint name errors and disallow UUID

- changelog.d/20230522_134306_chris_user_selectable_serialization.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/serialize/__init__.py
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/integration/test_serialization.py
- smoke_tests/tests/conftest.py
In anticipation of writing documentation for the new selectable serializer feature, it occurred to me that because of the way we use `ComputeSerializer` to wrap instances of `SerializeBase` - but not subclass it - there is some potential for confusion. I also don't love the usage of `method` to refer to the `SerializeBase` subclasses which are used to serialize/deserialize data within `ComputeSerializer`, since `method` is such an overloaded term in programming.
Instead, I propose the following:
* Rename `SerializeBase` to `SerializationStrategy`
* Refer to instances of `SerializationStrategy` as `strategies` (previously called `method`s)
This PR also renames `SerializerError` to `SerializationError`, which is more precise and mirrors the name of `DeserializationError`.
[sc-23912]
- Code …
> Standardize and disambiguate serialization class names

- compute_endpoint/setup.py
The **PyYAML** dependency should have been added to **compute_endpoint/setup.py** via #1151 but was missed.
> Add missing pyyaml dependency

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_sdk/setup.py
- compute_sdk/tests/integration/test_web_client_exceptions.py
Globus SDK v3.20.0 [modified](https://github.com/globus/globus-sdk-python/commit/23d7f1ce742e4d5231798cd56894a58a9ce0c977) the default value returned for `GlobusAPIError.message`, which we use in a few places. We will now use the `text` attribute to directly access response messages and bump the minimum required version for `globus-sdk` to v3.20.1.
> Sync code with Globus SDK v3.20.1 and bump min. version

- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/messages.py
[log_line_header ...] Received EPStatusReport <globus_compute_endpoint.engines.high_throughput.messages.EPStatusReport object at 0x7f2827bd77f0>
[log_line_header ...] Received EPStatusReport(ep:48ceb6a0-876b-3d31-6084-49dd7edb89d7; task count:0)
> Nicer EPStatusReport .debug() log line

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
This PR adds support for multi-tenant user configuration templates with Jinja syntax. As currently implemented, each multi-tenant endpoint must have one user config template named `config_user.yaml` in its endpoint directory.
1. Pass user options in a command payload to the `EndpointManager`
2. Call `fork`
3. Render the user config template (`config_user.yaml`) with the user options
4. Write the user config to `stdin`
5. Call `exec`
6. Read the user config from `stdin`
7. Generate a `Config` object for the user endpoint
I also included a small but relevant modification to ensure that an endpoint is not detached when started with the `--die-with-parent` flag.
[sc-21024]
> Add support for multi-tenant config templates

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
Support for `Engines` added in #1046 allow a cleaner interface to execution backend which now support our own fork of HTEX, Parsl's HTEX (now called `GlobusComputeEngine`), thread pools and process pools.
This PR switches over the Endpoint to use `Engines` instead of `Executors`. For backward compatibility of configs and to prevent older configs from breaking, we retain this pointer `globus_compute_endpoint.executors.HighThroughputExecutor` -> `globus_compute_endpoint.engines.HighThroughputEngine`
Test this functionality with the following configs:
This is primarily targetted at MacOS users for whom `ProcessPoolEngine` doesn't work.
```
from globus_compute_endpoint.endpoint.utils.config import Config
from globus_compute_endpoint.engines import ThreadPoolEngine
from parsl.providers import …
```
> Integrate Engines into the Endpoint

- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- docs/configs/bebop.yaml
- docs/configs/bluewaters.yaml
- docs/configs/cooley.yaml
- docs/configs/cori.yaml
- docs/configs/frontera.yaml
- docs/configs/kube.yaml
- docs/configs/midway.yaml
- docs/configs/midway_singularity.yaml
- docs/configs/perlmutter.yaml
- docs/configs/polaris.yaml
- docs/configs/theta.yaml
- docs/configs/theta_singularity.yaml
- docs/configs/uchicago_ai_cluster.yaml
- docs/configs/worker_pinning.yaml
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
- smoke_tests/tests/sh/test_endpoint.sh
Our YAML config schema should reflect the impending change to replace executors with engines.
[sc-24805]
> Rename `executor` to `engine` in YAML config

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_funcx/endpoint/funcx_endpoint/version.py
- compute_funcx/endpoint/setup.py
- compute_funcx/sdk/funcx/version.py
- compute_funcx/sdk/setup.py
- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/globus_compute_sdk/version.py
- compute_sdk/tests/unit/test_environment_lookups.py
- docs/changelog.rst
- docs/changelog_funcx.rst
This adds the various internal test environments to the allowed env list (staging, test, integration, preview, sandbox).
Getting the env now also uses GLOBUS_SDK_ENVIRONMENT (but falls back to FUNC_SDK_ENVIRONMENT if the former is not present).  
Also, includes alpha release version bump for the release earlier today.
Intentionally left the changelog unmodified
> Globuscs environments

- docs/endpoints.rst
Minor docs update to reference compute.api.globus.org rather than funcx.org
> Change funcx.org to compute.globus.org in docs

- compute_endpoint/MANIFEST.in
The path to `default_config.yaml` must be present in our `MANIFEST.in` file for it to be included in our package.
> Add default_config.yaml to MANIFEST.in

- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
A small typo in a validator name made the `strategy` config stanza unusable.
> Fix duplicate validator name

- changelog.d/20230622_214149_30907815+rjmello_bugfix_strategy.rst
Add missing changelog for bug in which adding a `strategy` stanza to a YAML config prohibits an endpoint from starting (see #1192).
> Add changelog for YAML config bugfix

- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- smoke_tests/tests/test_running_functions.py
- smoke_tests/tests/test_version.py
Our smoke tests are failing because existing SDK versions include the API version in their service address, but as of #1200, we specify the API version for each request. To support both scenarios in our smoke tests, we use the `WebClient.get_version()` method, which constructs the appropriate URL.
> Fix smoke test version checks

- changelog.d/20230630_110417_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- docs/configs/bebop.yaml
- docs/configs/bluewaters.yaml
- docs/configs/bridges-2.yaml
- docs/configs/cooley.yaml
- docs/configs/cori.yaml
- docs/configs/frontera.yaml
- docs/configs/kube.yaml
- docs/configs/midway.yaml
- docs/configs/midway_singularity.yaml
- docs/configs/perlmutter.yaml
- docs/configs/polaris.yaml
- docs/configs/theta.yaml
- docs/configs/theta_singularity.yaml
- docs/configs/uchicago_ai_cluster.yaml
- docs/configs/worker_pinning.yaml
- docs/configuring.rst
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
- smoke_tests/tests/sh/test_endpoint.sh
The engine `type` field is now supported in `config.yaml` and can be defined as any engine class. The default is `HighThroughputEngine` for backward compatibility.
I also replaced `HighThroughputExecutor` with `HighThroughputEngine` in `config.py` to avoid the deprecation warning when importing the former.
[sc-24805]
> Support engine type specification in config

- compute_endpoint/setup.py
This PR pins mypy to `<=8.1.3`
With mypy==8.1.4 we are seeing these errors in testing:
```
globus_compute_endpoint/cli.py:28: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
globus_compute_endpoint/cli.py:152: error: Argument 1 has incompatible type "Callable[[], Any]"; expected <nothing>  [arg-type]
globus_compute_endpoint/cli.py:244: error: Argument 1 has incompatible type "Callable[[bool], Any]"; expected <nothing>  [arg-type]
globus_compute_endpoint/cli.py:262: error: Argument 1 has incompatible type "Callable[[bool], None]"; expected <nothing>  [arg-type]
globus_compute_endpoint/cli.py:468: error: Argument 1 has incompatible type "Callable[[NamedArg(str, 'name'), NamedArg(bool, 'force')], Any]"; expected …
```
> Pin click to <= 8.1.3 due to mypy issues with 8.1.4

- docs/configs/delta.yaml
- docs/configs/stampede2.yaml
A couple example configs do not explicitly define an engine type, thus are using the default `HighThroughputEngine` type. In order to match our other example configs and increase clarity, I've added the explicit definition.
> Explicitly define engine type in example configs

- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/tests/unit/test_environment_lookups.py
Preview environment domain is actually on globus.org ie. [app.preview.globus.org](https://app.preview.globus.org/compute), not globuscs.info like sandbox, integration etc.  Make correction and update test.
> Update preview domain from globuscs.info to globus.org

- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
The `ThreadPoolEngine` does not accept a provider argument, so the related config field must be made optional.
> Make the provider config field optional

- changelog.d/20230716_122638_30907815+rjmello_process_pool_engine.rst
- compute_endpoint/globus_compute_endpoint/engines/__init__.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_status_reporting.py
Reimplemented ``ProcessPoolEngine`` for concurrent local execution.
The root issue with the former implementation was that we called the `concurrent.futures.ProcessPoolExecutor` constructor, which creates pipes for inter-process communication, in the `ProcessPoolEngine` constructor, which we call before we enter the daemon context. By default, the daemon process will close all existing file descriptors and break the existing pipes.
To fix this, we can either specify file descriptors for the daemon process to preserve or, more simply, ensure that we call the `ProcessPoolExecutor` constructor within the daemon context. I've implemented the latter by instantiating the `ProcessPoolExecutor` object in the `ProcessPoolEngine.start()` method.
[sc-25115]
- Bug fix (non-breaking change that fixes …
> Reimplement ProcessPoolEngine

- changelog.d/20230718_115634_30907815+rjmello_del_func.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_web_client.py
Added support for deleting functions via the ``Client.delete_function`` method.
[sc-25810]
> Add Client method to delete a function

- changelog.d/20230710_144242_yadudoc1729_strategy_for_gce.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/strategies/base.py
- compute_endpoint/globus_compute_endpoint/strategies/simple.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
- compute_endpoint/tests/unit/test_engines.py
This PR adds support for auto-scaling in `GlobusComputeEngine`.
* Each `GlobusComputeEngine` now starts with a strategy.
* `GlobusComputeEngine` now has these methods to determine task pressure and available capacity:
* get_total_tasks_outstanding
* get_outstanding_breakdown
* provider_status
* get_total_live_workers
* `GlobusComputeEngine` now has these methods to provision and drop resources: 
* scale_out
* scale_in  
[sc-23907]
> Support for scaling strategies in GlobusComputeEngine 

- docs/configs/perlmutter.yaml
`nmn0` is now configured as a member of a bond interface named `nmnb0`. See [Slack thread](https://funcx.slack.com/archives/C017637NZFA/p1689884026927839?thread_ts=1689879908.266379&cid=C017637NZFA) for reference.
> Update interface used in Perlmutter example config

- changelog.d/20230720_143409_30907815+rjmello_self_diagnostic.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
- compute_endpoint/tests/unit/test_cli_behavior.py
Added a `globus-compute-endpoint self-diagnostic` command, which runs several diagnostic commands to help users and Globus Support troubleshoot issues.
By default, all output prints to the terminal. The `--gzip` (or `-z`) flag redirects the output to a Gzip-compressed file that the user can easily share with Globus Support.
Endpoint log files can be quite large, so we cap the data taken from each file at 5,120 KB (5 MB). A user can modify this with the `--log-size` option. For example, if a user wants to include 1,024 KB (1 MB) of data per log file, they would use `--log-size 1024`.
[sc-25643]
> Add self-diagnostic endpoint command

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
Add an aid for quickly observing the end of one run and beginning of another in the endpoint logs:
<blank line>
========== Endpoint begins: 48ceb6a0-876b-3d31-6084-49dd7edb89d7
<timestamp> [...] Initializing EndpointInterchange process with Endpoint ID: 48ceb6a0-876b-3d31-6084-49dd7edb89d7
... Lots of log lines
... Lots of log lines
... Lots of log lines
---------- Endpoint shutdown: 48ceb6a0-876b-3d31-6084-49dd7edb89d7
<blank line>
> Add bookend sentinels to log

- smoke_tests/tests/test_running_functions.py
Address currently broken hourly smoke tests.  The borked test is because we just updated the `.add()` method of the Batch class.  Tests pass locally with the yet-unpublished SDK -- will be fixed once we publish.
> Skip test until published SDK catches up

- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
Using the `which` command in bash is less robust because of terminal differences, custom binary names, etc.
> Use Python to get path of binary for interpreter

- changelog.d/20230718_143645_chris_batchv3.rst
The sub-bullets were over-indented
> Fix changelog formatting

- changelog.d/20230724_145257_LeiGlobus_registration_blocked_msg_sc_25245.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
Add console print message when trying to register an endpoint, instead of just log messages in endpoint.log.
ie. Previously running globus-compute-endpoint start will just exit silently if the endpoint is locked or already active.  Now the console message is added (and in the already active case, no log message is emitted as it's a no-op)
> Add console message for locked/conflict messages

- changelog.d/20230718_143645_chris_batchv3.rst
- compute_sdk/globus_compute_sdk/sdk/batch.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_executor.py
The API route has moved to encompass the endpoint uuid in the path.  Update the SDK to match the updated endpoint, and surrounding semantics.  (For example, the Batch API.)
[sc-26022]
> Update API route to v3 submit

- docs/endpoints.rst
Our docs currently recommend running `globus-compute-endpoint stop` **twice**. This recommendation is obsolete.
> Remove obsolete recommendation to run  endpoint stop twice

- changelog.d/20230731_100321_kevin_avoid_possible_tg_race_condition.rst
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
Prior to this commit, tasks were not associated with a taskgroup.  In the case that a user wanted to switch task groups mid-run this created a race condition:
```python
with Executor(...) as ex:
ex.task_group_id = "some-task-group-id"
ex.submit(some_func_01)
ex.task_group_id = "some-other-task-group-id"
ex.submit(some_func_02)
```
Until this commit, `.submit()` calls did not associate tasks with a task group id, instead creating the association _with the currently assigned Executor `task_group_id`_ when the internal thread pulled the tasks for upstream submission.  Thus, from the above code, there was no guarantee that `some_func_01` would be associated with `some-task-group-id`.
Address by associating each task with the current task_group_id before returning the future to the calling …
> Address race-condition w/ Executor task submission

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
(Redo of previous PR for more clarity)
As per https://app.shortcut.com/funcx/story/24211/allow-list-functions-by-uuid-in-endpoint
Add checking locally on endpoint for allowed functions.  This involves adding a check for the function_id in the RMQ properties.headers which was recently added.
See [PR on service side](https://github.com/globusonline/funcx-services/pull/388).
TL;DR the config.yaml should include a section like the below with a list. 
```yaml
display_name: ...
allowed_functions:
- 94c7ce20-7a5a-4eb3-ac07-6fc0aabcd50c
- aab66753-4b02-4162-a9d3-47374dabcdc4
executors:
...
```
> Enforce allowed_functions locally on endpoint as redundancy to web_service checking

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_htex_regression.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_status_reporting.py
One of the main goals of the recent Engine work and the addition of the task identifying information to the AMQP messages was to remove the need to deserialize in the main endpoint interchange.  More recently,[1] we removed the `unpack()` call from the Task forwarding thread loop.  Follow-through and remove the same from the Result forwarding thread loop as well.
[1] 1ee3fd54906895393a78a6916f19edef70a31c76 "check rmq message header for allowlist and add header to queue (#1241)"
> Remove unpack() in endpoint/interchange

- changelog.d/20230802_150602_yadudoc1729_fix_missing_script_dir.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
This PR sets the `provider.channel.script_dir` attribute at `Engine.start(...)` if that option is not supplied.
Without this option, the script paths were getting messed up when cast to str:
```
- Before -
#SBATCH --output=None/parsl.HighThroughputExecutor.block-0.XXXXXXXX.submit.stdout
-  After -
#SBATCH --output=/home1/02551/yadunand/.globus_compute/gce_batch/submit_scripts/parsl.HighThroughputExecutor.block-0.1690574273.29589.submit.stdout
```
This fix was tested on Frontera. Ideally we'd have confirmation from Polaris (maybe @ryanchard can help), but ALCF machines are down now.
[sc-26051]
> Fix missing channel.script_dir 

- compute_sdk/setup.py
See discussion in :  https://funcx.slack.com/archives/C016JMYST9C/p1691005981657089
SDK using dill version 0.3.6 does not decode properly in 0.3.5.1, which was the version used in older endpoint versions.
Reverting until we figure out a long term solution.
Fixes the stack trace:
```
File "/home/ubuntu/.local/lib/python3.10/site-packages/globus_compute_sdk/serialize/facade.py", line 125, in unpack_and_deserialize
deserialized = self.deserialize(current)
File "/home/ubuntu/.local/lib/python3.10/site-packages/globus_compute_sdk/serialize/facade.py", line 82, in deserialize
return strategy.deserialize(payload)
File "/home/ubuntu/.local/lib/python3.10/site-packages/globus_compute_sdk/serialize/concretes.py", line 146, in deserialize
function = …
```
> Revert dill version to make it compatible with 2.2.3

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
We avoid YAML injection attacks by applying `json.dumps()` to all string values in user config options. Note that this will enforce double-quoted YAML strings.
```yaml
endpoint_setup: {{ setup }}
```
```python
user_opts = {
"setup": "my-setup\nallowed_functions:\n\t- b9703f9d-2e97-49ee-9dea-3f67ed13a0ad"
}
```
[sc-26181]
> Escape user option strings to avoid YAML injection

- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/config/user_environment.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
For new MT configurations, ensure there's a default user_endpoint configuration template.  This provides a scaffolding for admins to modify, rather than requiring a whole-cloth creation, with some low-hanging fruit defaults (e.g., `max_blocks: 1`, `idle_heartbeats_soft`, etc.)
> Create default templates for MT endpoints

- docs/Tutorial.rst
Updates the readthedocs tutorial page to the latest example notebook. This version demonstrates using the executor and futures interface, rather than polling.
> Switch to the latest tutorial notebook as the example.

- smoke_tests/tests/test_running_functions.py
* Updated the arguments for `Client.create_batch` and `Client.batch_run` in our smoke tests to match recent changes.
* Modified `Executor.reload_tasks` to ensure that we use the matching types (`str`) when comparing the task group UUID associated with the `Executor` with what is sent back from the web service.
> Fix smoke tests and `Executor.reload_tasks`

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_utils.py
For administrators running a multi-tenant endpoint, the parent process&nbsp;&mdash;&nbsp;the endpoint manager&nbsp;&mdash;&nbsp;is expected to lookup local user ids (UID) and then drop privileges to that UID before `exec()`ing.  On the other hand, for non-power users (e.g., not `root`) running the multi-tenant endpoint, the process won't have the privileges to change users anyway.  Consequently, implement a check that only allows the parent endpoint process to create child endpoint processes ("user endpoints") with the same process UID if the UID is not otherwise privileged.
This is implemented with 2 checks:
- Is the parent process owned by UID 0?
- Does the parent process have any admin-like capabilities (via `pyprctl`)
If either are true, then set a flag to prevent any attempts to …
> Prevent same-user child-processes

- docs/sdk.rst
Add a note that lists our available serialization strategies and a heading that will make it easier for us to link to for users in the future.
> Add note to method serialization strategies

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
The web service expects `allowed_functions` to be a top-level field in the endpoint registration API request.
[sc-25261]
> Add allowed functions to EP registration request

- changelog.d/20230824_124226_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
An informative error message will print to stdout when attempting to start or delete an endpoint while the Globus Compute web service is unreachable.
[sc-26628]
> Print message to stdout when network error occurs

- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_schema.json
- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/setup.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The `EndpointManager` now validates user config options against the JSON schema defined in `~/.globus_compute/<ep_name>/user_config_schema.json`. Validation will occur before the user config template is rendered. If no schema is defined, we skip validation.
We also provide a permissive default that matches the default user config template. This schema can be modified or removed as needed.
[sc-26049]
> Validate user config options against JSON schema

- changelog.d/20230830_153211_30907815+rjmello_self_diagnostic_env.rst
- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/tests/unit/test_environment_lookups.py
The `self-diagnostic` endpoint command is now aware of the `GLOBUS_SDK_ENVIRONMENT` environment variable and will test connectivity to the relevant services.
I also added the `/version` API endpoint response to the `self-diagnostic` output.
[sc-26629]
> Make self-diagnostic GLOBUS_SDK_ENVIRONMENT aware 

- changelog.d/20230906_131715_30907815+rjmello_auth_errors.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/exception_handling.py
- compute_endpoint/tests/unit/test_cli_behavior.py
Created a decorator that will capture any `globus_sdk.AuthAPIError` exceptions then print a helpful message to the terminal. I've applied the decorator to all commands that use an SDK method in which auth is required.
[sc-25677]
> Create decorator to handle Auth API errors

- changelog.d/20230822_132114_LeiGlobus_report_worker_sdk_version_sc_25606.rst
- compute_endpoint/globus_compute_endpoint/endpoint/messages_compat.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/worker.py
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_messages_compat.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_funcx/endpoint/funcx_endpoint/version.py
- compute_funcx/endpoint/setup.py
- compute_funcx/sdk/funcx/version.py
- compute_funcx/sdk/setup.py
- compute_sdk/globus_compute_sdk/errors/error_types.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/globus_compute_sdk/version.py
- compute_sdk/setup.py
- compute_sdk/tests/unit/conftest.py
- compute_sdk/tests/unit/test_client.py
This is the largest of the 3 PR necessary to report differing python versions between the client and worker if task execution fails.  It involves adding metadata in the 'details' field of all results.  
Now SerializationError and TaskExecutionError will add such info to the stack trace.  
See story https://app.shortcut.com/funcx/story/25606/report-warning-error-message-if-sdk-and-worker-python-version-mismatch
An import requirement is that the web-service and associated storage classes handle older endpoints that supplies results without the new field.
Currently, the info is stored in RedisTask (AsyncRedisTask).  This is ephemeral, so a followup PR will add a column to the task in psql to keep a more permanent record.
2.3.1a1 SDK and EP have already been pushed to PyPI for testing …
> Report worker info in Result messages (python, sdk, os, dill, etc)

- changelog.d/20230907_141555_30907815+rjmello_self_diag_ssl_conn.rst
- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
- compute_endpoint/tests/unit/test_cli_behavior.py
Added steps to the `self-diagnostic` endpoint command that print the local system's OpenSSL version and attempt to establish SSL connections with the Globus Compute web services.
[sc-26966]
> Add SSL checks to self-diagnostic command

- changelog.d/20230911_113153_30907815+rjmello_HEAD.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_executor.py
To assist with debugging and error handling related to serialization, we record the Python and SDK version that are used when serializing a function.
[sc-25861]
> Include Python and SDK versions in function reg.

- changelog.d/20230913_094159_30907815+rjmello.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_web_client.py
Added a `Client.get_function` method to submit a request for details about a registered function, such as name, description, serialized source code, python version, etc.
[sc-25861]
> Create `Client.get_function` method

- compute_endpoint/tests/unit/test_cli_behavior.py
Due to `click.CliRunner`'s implementation for testing sys.stdin, and our use of sys.stdin for credentials, we're hitting the early `log.debug()` call and getting:
... Invalid info on stdin -- (JSONDecodeError) Expecting value: line 1 column 1 (char 0)
when showing the verbose debugging output.  This is noise that is unrelated to the tests, so opt instead to give a default value that avoids that log call.
> Remove noisy log during test

- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_status_reporting.py
Motivated by an upcoming change, remove instantiation of unused engines for parameterized tests.  Instead, only instantiate each class under test for its specific test parameter.  As a bonus win, there's now only a single fixture ("single path") for engine starting and stopping.
For the reviewer: the change of consequence is removing from `tests/conftest.py` the three fixtures:
- `proc_pool_engine`
- `thread_pool_engine`
- `gc_engine`
and replacing them with `engine_runner`.  The rest of the changes are "just" flushing that change to all uses.
> Refactor engine test fixtures

- changelog.d/20230918_120556_kevin_address_gc_engine_shutdown_bug.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/conftest.py
Commit 8effb2a1b56397ae4e6873aa1f67ce51ccf9adaf assumed an interface for `EngineBase.shutdown()` that accepted `block` as an argument.  Unfortunately, not all engines implement this keyword; those using the `GlobusComputeEngine` would receive a traceback after shutdown (during cleanup) like:
```python
File "VENVBIN/bin/globus-compute-endpoint", line 33, in <module>
sys.exit(load_entry_point('globus-compute-endpoint', 'console_scripts', 'globus-compute-endpoint')())
...
File "VENV/globus_compute_endpoint/endpoint/interchange.py", line 302, in start
self.cleanup()
File "VENV/globus_compute_endpoint/endpoint/interchange.py", line 206, in cleanup
self.executor.shutdown(block=True)
TypeError: GlobusComputeEngine.shutdown() got an unexpected keyword argument …
```
> Add Engine .shutdown() expected interface

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
These two entries currently allow a motivated personality (perhaps a dev?) to override what the API automatically discerns regarding the SDK version.  This has so far not been utilized and has no backing customer need.  So, under YAGNI, removing until a more-specific need arises.
Meanwhile, refactor the dict creation to placate the IDE warning ...
> Remove unused metadata entries

- compute_endpoint/tox.ini
- compute_sdk/tox.ini
Motivated by a (slow) progression of tests beginning to take longer, help to identify the culprits on a regular basis.
After the tests complete, we should now see output resembling:
```
========================= slowest 5 durations ==========================
0.16s call     tests/integration/test_executor_int.py::test_executor_atexit_handler_catches_all_instances
0.12s call     tests/unit/test_executor.py::test_task_submitter_stops_executor_on_upstream_error_response
0.10s call     tests/unit/test_executor.py::test_task_submitter_respects_batch_size[10]
0.10s teardown tests/unit/test_executor.py::test_user_endpoint_config_added_to_batch
0.10s call     tests/unit/test_executor.py::test_task_submitter_stops_executor_on_exception
```
> Show 5 slowest test durations

- docs/quickstart.rst
Motivated by a user email, fix the code-block formatting and highlighting on the QuickStart page.
-----
-----
While here, take the opportunity to update the requirement to Python 3.8+, and make code-block indenting a uniform 2-spaces.
> Address formatting on QuickStart page

- compute_endpoint/globus_compute_endpoint/cli.py
Save a couple of minutes of the next dev's head scratching when a known-working module mysteriously "doesn't exist."
> Show precise import error if debugging

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
This is analogous to [PR #1026](https://github.com/funcx-faas/funcX/pull/1026) / dba68f32547d2655817f3f00e0a39abb17a2cfe6 (but for the MT endpoint manager), enabling a dev (the only expected user) to pass in credentials via stdin.  (i.e., `$ gce start mt < some_local_only_creds`)
- New (dev-specific) feature (non-breaking change that adds functionality)
> Allow passing in MT creds on stdin

- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
- compute_endpoint/tests/unit/test_self_diagnostic.py
Rather than trying to decode the binary stream (`open(f, "rb")`), instead just work in binary-land and perform our own line indenting.
While here, add a little more window-dressing to delineate each file, and some specific unit tests:
- Add `===` horizontal line below each `cat <file>` command
- Add `---` horizontal line at end of each `cat` command
- Indent with the pipe to make each file visually standout in log (`<sp>|<sp>`)
- Unit test the `cat` diagnostic command
Prior to this commit, would fail on (errant, but "there") binary files:
...
File "VENV/globus_compute_endpoint/self_diagnostic.py", line 39, in kernel
content = f.read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 8-9: invalid continuation byte
[sc-27488]
- Bug fix (non-breaking change …
> Handle binary files gracefully in diagnostic

- .github/dependabot.yml
- changelog.d/20231004_112352_kurtmckee_add_dependabot_for_github_actions.rst
GitHub actions are currently throwing deprecation warnings due to the age of the action versions and compatibility with Node 16 ([recent example](https://github.com/funcx-faas/funcX/actions/runs/6408656739)).
Rather than update the versions with a one-off PR, this PR introduces a Dependabot configuration that will regularly submit PRs to update the action versions.
If this merges, you can expect Dependabot to immediately submit multiple PRs to update the out-of-date action versions. For example, `actions/setup-python@v1` will be updated to `actions/setup-python@v4`.
> Add a Dependabot config to keep GitHub action versions updated

- changelog.d/20230928_123020_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/tests/unit/test_endpoint_config.py
The `yaml.safe_load()` method only supports simple Python objects like integers and lists, but Parsl's `HighThroughputEngine` requires tuples for certain fields. To address this, we leverage Pydantic to convert the relevant field values.
> Convert certain config fields to tuples

- changelog.d/20231002_152607_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
Endpoint admins can now define a Globus authentication policy directly in an endpoint's configuration or by using the `--auth-policy` flag when running the `globus-compute-endpoint configure` command.
Users are evaluated against the policy when submitting tasks, retrieving endpoint information, etc. The Globus Compute web service handles both evaluation and enforcement (see https://github.com/globusonline/funcx-services/pull/501).
[sc-26335]
> Support Globus auth policies on endpoints

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
> Restart user endpoint if it dies soon after start command

- compute_endpoint/tests/unit/test_self_diagnostic.py
When working with arbitrary data, don't forget that "newline" is context-dependent.  `bytes.splitlines()` splits over `\n` and `\r`.  From the Python source code:
```c
#define STRINGLIB_ISLINEBREAK(x) ((x == '\n') || (x == '\r'))
```
And clearly defined in the documentation as well.[1]
[1] https://docs.python.org/3/glossary.html#term-universal-newlines
- Bug fix (non-breaking change that fixes an issue)  [in the tests!]
> Address flaky test.

- changelog.d/20231023_121708_30907815+rjmello_ep_reg_errors.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Expand cases in which we return a meaningful exit code and message after endpoint registration failures when calling ``globus-compute-endpoint start``.
Formerly, we only did this for `LOCKED` and `CONFLICT` HTTP responses.
[sc-27805]
> Expand handling of blocked EP registration

- compute_endpoint/globus_compute_endpoint/exception_handling.py
- compute_endpoint/tests/unit/test_cli_behavior.py
When an user runs an endpoint command and the refresh token is expired (> 6 months old), the CLI exists with a cryptic invalid_grant error message which is confusing.  See Story https://app.shortcut.com/funcx/story/27972/display-better-error-message-when-refresh-token-is-expired-on-endpoint-commands
We catch these errors in normal auth pathways when registering endpoints, but the crux is that GET /v2/version fails auth, even though the token isn't required.  The Globus SDK always verifies the token if it exists, before the request is sent to the endpoint(which may be a public endpoint that does not care about tokens).
Slack discussion: https://funcx.slack.com/archives/C016JMYST9C/p1697729426325119
Ideally, we want to give more clear information to the user.  But in this PR I stopped short …
> Add auth exception handling for expired token

- changelog.d/20231023_170403_30907815+rjmello_gcengine_heartbeat_period.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
- compute_endpoint/tests/unit/test_engines.py
The `GlobusComputeEngine`, `ProcessPoolEngine`, and `ThreadPoolEngine` now respect the ``heartbeat_period`` variable, as defined in `config.yaml` and validated via `ConfigModel` (Pydantic). 
The fix involved renaming the `heartbeat_period_s` attribute to `heartbeat_period`, which also improves parity between the Compute engines and Parsl's `HighThroughputExecutor`.
- Bug fix
> Rename `heartbeat_period_s` to `heartbeat_period`

- changelog.d/20231024_175842_30907815+rjmello_engine_heartbeat_period_int.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Changed `heartbeat_period` type from float to int for `GlobusComputeEngine`, `ProcessPoolEngine`, and `ThreadPoolEngine` to maintain parity with the `HighThroughputEngine` and Parsl's `HighThroughputExecutor`.
> Change `heartbeat_period` type from float to int

- changelog.d/20231024_183134_30907815+rjmello_gcengine_executor_heartbeat.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_status_reporting.py
The `GlobusComputeEngine` now passes the `heartbeat_period` argument to its Parsl `HighThroughputExecutor`.
> Pass `heartbeat_period` to Parsl HTEX

- changelog.d/20230902_101610_rchard_add_token_login_manager.rst
- compute_sdk/globus_compute_sdk/sdk/login_manager/__init__.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/authorizer_login_manager.py
- compute_sdk/tests/unit/test_authorizer_login_manager.py
- docs/sdk.rst
This PR introduces an AuthorizerLoginManager to create clients from existing tokens.
Previously, if one wanted to create a client from existing tokens they had to implement a custom login manager to serve authorizers as needed. 
> Add AuthorizerLoginManager

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
`GlobusComputeEngine.scale_in(blocks:int)` picks the first `blocks` number of blocks to cancel. Instead we should be
using the `HighThroughputExecutor`'s `scale_in` method that has handling for tracking and placing `blocks` on hold
when they are mostly idle.
> Fix GlobusComputeEngine's scale_in method

- changelog.d/20231020_110321_chris_443_ampqs.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_utils.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
> Support alternative AMQP ports

- changelog.d/20231025_205335_30907815+rjmello_gcengine_status.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_status_reporting.py
Added and refactored `GlobusComputeEngine` methods to populate the endpoint status report.
[sc-27810]
> Populate `GlobusComputeEngine` status report

- compute_endpoint/tests/unit/test_worker.py
CPython's `time.sleep()` holds the thread in C-land, making it, for most usages, uninterruptible.  Sleeping in small increments for the total duration allows the thread to be interrupted, which allows us to shave about 1 second off the run-time.
> Speed-up test by slicing time.sleep

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Rather than mocking the functional call, inject a fake API response&nbsp;&mdash;&nbsp;this is a little more "honest" about testing what _actually_ gets sent to the API.  Additionally, verify the expected exit code.
> Refactor test

- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The test is named `test_no_cached_args_means_no_restart`, but the code of interest was not executed.  Exploit co-located log to verify that the "happy path" is traversed, _then_ make the assertion.
> Correct test path of interest

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_manager.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
- compute_endpoint/tests/unit/test_bad_endpoint_config.py
- compute_endpoint/tests/unit/test_command_queue_subscriber.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/unit/test_worker.py
- compute_endpoint/tox.ini
While en route to tracking down a test failure in another branch (only occurring in CI&nbsp;&mdash;&nbsp;doh!), was overwhelmed with a number of superfluous output generated by some tests.  Realized that we don't see this locally because we have not had parity with CI `--log-cli-level=ERROR` flag to `pytest`.  Changing that (`tox.ini`), and then clearing up the then-apparent noisy tests.
As a side-benefit, some of these noisy tests weren't actually testing what they were supposed to, and the error messages were, in fact, telling us so.  So ... "fixed."
Take the opportunity to update mypy
> Quiet some test output

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/example_identity_mapping_config.json
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
- compute_endpoint/setup.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_identity_mapper.py
The main addition in this commit is the implementation and utilization of `PosixIdentityMapper`, which wraps the Globus Identity Mapper tool.  Basic use looks like:
```python
im = PosixIdentityMapper("path/some/conf.json", "some uuid or other id")
local_user_id = im.map_identity([{"some": "list"}, {"of": "globus ids"}])
```
The `im` object will watch the configuration file for changes (stat every few seconds), and atomically update the configuration accordingly.
The previous route of a simple JSON file (dictionary mapping) is no more.
Also:
- update the default configuration to point to an example configuration document
- disallow specification of an engine for a multi-user config (where it doesn't make any sense)
Note: Not adding a changelog at this time, as we aren't prepared to …
> Implement identity mapping

- compute_sdk/tests/unit/test_client.py
The `assert` statement merely checks the truthiness of its operand. Unfornately, that's a problem when there's a typo, as was the case here. `MagicMock().called` returns a boolean of whether that attribute was called as a function, but `MagicMock().called_with(...)` is not defined specially by `unittest.mock`.  Thus, it is magically being created by that very statement, and just passing.
What _does_ exist is `.assert_called_with(...)`, so alter tests accordingly.
> Fix two assertions

- changelog.d/20231106_152114_30907815+rjmello_gcengine_label_passthrough.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_engines.py
We now pass the `label` argument for the `GlobusComputeEngine` to the Parsl `HighThroughputExecutor`.
> Pass `label` to Parsl HTEX

- changelog.d/20231106_203334_30907815+rjmello.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_engines.py
The `GlobusComputeEngine` worker logs will appear in the `~/.globus_compute` directory rather than the current working directory.
> Pass `run_dir` to Parsl HTEX when starting engine

- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/tests/unit/test_htex.py
I've reimplemented the code that we mistakenly broke in PR #1140. The main difference is that we now unpack the task message in the `submit()` method of the `HighThroughputEngine` rather than the `EndpointManager` since the former will be deprecated.
[sc-27595]
> Add container location to internal `Task` object

- changelog.d/20231108_133632_yadudoc1729_heartbeats_and_reporting_sc_28343.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_reporting_period.py
- compute_endpoint/tests/unit/test_status_reporting.py
The `GlobusComputeEngine` has a notion of `hearbeat_period` and `heartbeat_threshold` used internally to track worker liveness. This is separate from the status reporting logic implemented in the `GlobusComputeEngineBase` that sends `EPStatusReports`.
This PR sets the `reporting period` to a constant. Users should not be able to tweak this, and we should not be supporting cases where there's any functionality built on faster updates.
> Separate heartbeat_periods and reporting_period

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
The error was in attempting to read a file to which the dropped-privileges process did not have access:
/root/
`root`'s home directory is (very correctly) set to 0o40700, meaning that only `root` can access anything inside of `/root/`.  This is a problem for the user endpoint as it is unable to read the `user_config_template.yaml` file that is located at
/root/.globus_compute/<multi_user_endpoint>/user_config_template.yaml
Addressed by reading the file into a string *before* dropping privileges.
[sc-28360]
> Read template before dropping privs

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
We can pass the `address` arg to the Parsl HTEX via the `kwargs` catch-all since we aren't doing anything special with it.
> Pass `address` to Parsl HTEX via `kwargs` catch-all

- docs/endpoints.rst
- docs/executor.rst
- docs/quickstart.rst
- docs/sdk.rst
- docs/tutorial.rst
Remove references to the sharing of endpoints, and make it more clear that only the single authorized user can access the endpoint.
> remove references to sharing endpoints

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_web_client.py
Utilize the v3 POST/PUT routes for endpoint registration and rely on the web service to generate endpoint UUIDs.
[sc-28410]
> Utilize v3 POST/PUT routes for EP registration

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
We missed including the schema file in the initial output on the command line when the user creates a multi-user endpoint.
> Add missing schema file to configure output

- compute_endpoint/globus_compute_endpoint/MULTIUSER_SETUP.md
This documentation is mostly oriented around a "tl;dnr" section to get a multi-user endpoint admin up and running quickly.  For the identity mapping logic, however, I have not yet figured out how to succinctly put that, so that points to the GCS documentation, and then directs folks to reach-out in help.
Finally, this includes some background information, including the rough flow of a task from the SDK to the UEP, and where the MEP sits.
[sc-28145]
> First go-round at MU instructions

- compute_sdk/globus_compute_sdk/errors/__init__.py
- compute_sdk/globus_compute_sdk/errors/error_types.py
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/integration/test_serialization.py
When implementing user-definable serialization, we were still using our original forked HighThroughputExecutor. That executor relied on globus_compute_sdk.errors.SerializationError. At the same time, the serialization module relied on its own SerializationError. To avoid mixing their semantics up, I left them in place. Now that we've moved away from HighThroughputExecutor, we no longer need that differentiation, so for consistency's sake, this moves the ser/de errors into the SDK's common errors module.
At the same time, introduce a base class to catch both serialization and deserialization errors, and ensure that all three error classes are also ComputeErrors.
> Centralize location of serialization/deserialization errors

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
For the time being, YAGNI, and recognize that we never do anything different; we *always* ACK the message, regardless of the processing outcome.  No need to worry about "proper handling" later, if it's already done.
> Simplify command ACK

- docs/quickstart.rst
I changed "endopint" --> "endpoint." Literally nothing else :)
> Fix typo in quickstart guide

- .github/workflows/ci.yaml
Minor update to safety checks to upgrade pip. This addresses recent safety check failures:
```
-> Vulnerability found in pip version 23.2.1
Vulnerability ID: 62044
Affected spec: <23.3
ADVISORY: Pip 23.3 includes a fix for CVE-2023-57[52](https://github.com/funcx-faas/funcX/actions/runs/7009364373/job/19067627381?pr=1342#step:5:53): When installing
a package from a Mercurial VCS URL (ie "pip install hg+...") with pip...
CVE-2023-5752
For more information, please visit
https://data.safetycli.com/v/62044/f17
Scan was completed. 1 vulnerability was found.
```
> Upgrade pip before running safety checks

- changelog.d/20231031_230517_yadudoc1729_task_retries_1.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/utils.py
This PR adds support for automatically retrying tasks that fail due to infrastructure failures. Here's how we present this to users:
1. Set `GlobusComputeEngine(max_retries_on_system_failure: int = N)`
2. If a task fails due to `ManagerLost`, GCE retries task and produces a traceback like this:
```
++++++++++++++++++++ Traceback from attempt:0 ++++++++++++++++++++
File "/Users/yadu/src/funcx/compute_endpoint/.tox/py/lib/python3.10/site-packages/six.py", line 719, in reraise
raise value
File "/Users/yadu/src/funcx/compute_endpoint/.tox/py/lib/python3.10/site-packages/parsl/executors/high_throughput/interchange.py", line 572, in expire_bad_managers
raise ManagerLost(manager_id, m['hostname'])
parsl.executors.high_throughput.interchange.ManagerLost: Task …
```
> Support for automatic task retries on the endpoint

- smoke_tests/tests/test_running_functions.py
> Fix smoke test

- .github/workflows/ci.yaml
Safety is pedantically correct, if overzealous, and the provided image in ubuntu-latest contains some extra pre-installed packages.  This appears to amount to a situation where pip does not properly remove an old version of an updated package.  In this case, `pip` itself.  So ... help it along by manually removing the offending package.
Hopefully, this will become a non-issue shortly once the image is updated again -- a transient error.  Meanwhile, we have a new CI cruft of our own (`rm -rf ...`)
(With thanks to @kurtmckee for the pointer!)
> Remove detritus from CI image

- compute_sdk/globus_compute_sdk/errors/error_types.py
- compute_sdk/tests/unit/test_error_types.py
Motivated by some requests in #help and by the fact that diagnosing and fixing serialization-related errors is currently a rather arcane task.
[sc-28690]
> Give some helpful info on a suspected serialization error

- changelog.d/20231212_095641_yadudoc1729_update_to_parsl_2023_12_4.rst
- compute_endpoint/globus_compute_endpoint/strategies/simple.py
- compute_endpoint/setup.py
There are a bunch of fixes and updates to the `HighThroughputExecutor` on the Parsl side that we are not using because the endpoint is pinned to `parsl==2023.7.3`. This PR updates the Parsl version requirements to `parsl==2023.12.4`, and makes adds a minor fix to an updated import path on the parsl side.
> Update to parsl 2023.12.4

- compute_sdk/globus_compute_sdk/sdk/executor.py
Be precise about intention to use `repr()` in the message/exception formats.  These are NFC statement changes because `__str__` is not currently defined.  (Should it ever become so, "now we're prepared.")
While here, more fully match the [Executor specification to raise a `RuntimeError` for `.map()`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown) as well, if called after shutdown.
> Be precise about repr() in exceptions

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_schema.json
- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
As identified in the associated ticket, there is no `endpoint_init`, and the `endpoint_setup` item should be top-level.
However, debugging this shouldn't have been quite as arcane as it was: there were no logs.  In lieu of an upcoming commit to more robustly communicate UEP errors via the already-instantiated AMQP credentials, this commit ensures that at least something gets written to the logs in the identified case.
For the reviewer, the main changes are the try-except in `cli.py` (for logging) and the template fixes in `user_config_template.yaml` and `user_config_schema.json`.  There's also a smattering of other "make sure we've logged before dying" in `endpoint.py`.
[sc-28607]
> Fix flubbed default user template

- .github/workflows/daily.yaml
- changelog.d/20231216_131520_kurtmckee_fix_daily_workflow.rst
The daily workflow's Safety checks are failing due to what appear to be pre-installed Python packages. These are not getting overwritten/updated because pip is defaulting to user installation.
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyjwt<3.0.0,>=2.0.0 in /usr/lib/python3/dist-packages
Requirement already satisfied: cryptography!=3.4.0,>=3.3.1 in /usr/lib/python3/dist-packages
```
```
Safety v2.3.5 is scanning for Vulnerabilities...
Scanning dependencies in your environment:
-> /usr/local/lib/python3.10/dist-packages
-> /usr/lib/python3/dist-packages
-> /home/runner/.local/lib/python3.10/site-packages
...
-> Vulnerability found in pyjwt version 2.3.0
-> Vulnerability found in cryptography version 3.4.8
```
The Safety …
> Isolate the Python environment that Safety is checking

- compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
- compute_endpoint/tests/unit/test_identity_mapper.py
If an identity fails to map with a particular mapper, the log output can by slightly confusing.  In particular, there's no indication of which mapper is failing with which identity.  Improve that situation with the index of each mapper, the mapper class, the index of the identity (which is, admittedly, arbitrary, but at least shows that the tested identity is *different* from the previous iteration), and the sub of the identity.
Old output looked like:
2023-12-15 [...]:212 map_identity Identity mapper failed -- (IdentityMappingError) Error mapping identity
New output looks like:
2023-12-15 [...]:213 map_identity Identity mapper failed for mapper 1 (ExternalIdentityMapping) with identity 2 (abc91c2e-1234-4d38-9a8f-1cbf4a6ce811) -- (IdentityMappingError) Error mapping identity
There's …
> Be more transparent with identity mapping errors

- changelog.d/20231219_144502_30907815+rjmello.rst
- compute_endpoint/setup.py
This version contains a few improvements to worker robustness. For example, workers will now shut themselves down if their associated manager processes terminate for any reason.
[sc-25274]
> Pin Parsl to 2023.12.18

- changelog.d/20240102_141658_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
The interchange should quiesce when the task RabbitMQ channel closes for any reason. This enables the endpoint to shut down when, for example, the task queue is deleted.
Fixes [sc-28687]
> Set quiesce event when task RMQ channel closes

- changelog.d/20240104_141408_chris_endpoint_default_443.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Motivated by a [conversation in Slack](https://funcx.slack.com/archives/C016JMYST9C/p1704308608039249?thread_ts=1704306163.967149&cid=C016JMYST9C). 
> Change default AMQP port for new endpoints to 443

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Per Python documentation, `sys.exit()` is the preferred choice.  See:
https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module
> Prefer sys.exit over exit

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/logging_config.py
Per slack conversations on varying terminal emulators actual color output.  For the interested devs, this set of colors is more pleasing and/or easier to read.
- Code maintenance/cleanup  (a useful-for-devs feature)
> Update debug color palette

- README.rst
The docs badge still pointed to funcx.readthedocs. Also updates the main website links to globus.org/compute, and the build status badge to the hourly GitHub Action.
> Update some old README.rst links

- .github/workflows/daily.yaml
- smoke_tests/Makefile
- smoke_tests/README.md
- smoke_tests/tests/conftest.py
- smoke_tests/tests/test_version.py
Daily smoke tests on 'dev' has been failing.  As we already have ECS services up and running, a 'better' fix rather than investigating the current failure is to replace 'dev' with one of the ECS non-prod environments for the daily test.
Picked 'staging' as the services env to test against, but this can be changed easily enough.  Outside of the PR, I also created hello_world public functions for all the non-prod environments needed by the smoke tests, IDs specified here.
Note that
- The new Tutorial endpoints for all environments is supposed to be Multi-User.  However, there are working endpoints only for test and staging as of Jan 11 2024.  Manually running the smoke tests for any other env will not work as the ``4b11...`` endpoint isn't running yet for sandbox, integration or preview (to …
> Add non prod environments to smoke tests, replacing dev

- .github/workflows/ci.yaml
Numbers chosen based on typical test run times, plus some fudge.  No sense in waiting 6 hours to discover a hung test.
> Implement CI timeouts

- compute_sdk/setup.py
Building the docs recently broke with a requirement requiring a more recent version of Sphinx.  We last touched this in Mar 2022, so it's perhaps time for at least a library update.
> Fix docs build

- .github/workflows/daily.yaml
In the github actions is probably the best place to set GLOBUS_SDK_ENVIRONMENT for the tests.  client_args obeys environment=XXX which is set in client_args but globus_sdk needs the former.
> set GLOBUS_SDK_ENVIRONMENT when make staging

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_utils.py
When an endpoint fails to start up, if the endpoint manager has at least acquired the UEP's AMQP credentials, it can send a failure status to the web services.  In the majority of cases then, the SDK need not wait for the web-service to time out -- it can get near-instantaneous feedback.
This changeset addresses both the pre-exec states (e.g., the user cannot be mapped to local uid) and in the post-exec UEP startup failures (e.g., an invalid configuration).
[sc-28883]
> Send UEP startup failure AMQP message

- compute_sdk/tests/unit/test_executor.py
The test verification relies on `any()`, but `any([])` (i.e., if the mock data is a 0-length list) evaluates to `False`:
```python
>>> any([])
False
```
Doh!
> Address flaky test

- .github/workflows/daily.yaml
- smoke_tests/tests/conftest.py
The previous attempt, adding ``GLOBUS_SDK_ENVIRONMENT=staging make staging`` to the run command apparently isn't sufficient to set the env var.
Trying a different syntax - Adding it directly to the ``env:`` section.  That *could* work, but it's difficult to test it locally.  The second change - setting it manually in conftest.py - is the backup option.
My strategy is to merge in both methods, confirm that this does resolve the issue, then try removing the conftest change and seeing if the daily.yaml change is sufficient. (via followup PR).
> Trying again to fix GLOBUS_SDK_ENVIRONMENT for smoke tests

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
There's no need to incur the overhead of `mp.Event`; we don't use `.wait()`, and we don't pass the event to any external processes.  Internally, we treat it as a set-only flag, so just use a simple boolean.
> Remove unnecessary event

- changelog.d/20231215_125237_chris_hardware_details.rst
- changelog.d/20240104_141408_chris_endpoint_default_443.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
PR for today's release, bumping versions.
For the AMQP change, the documentation change in https://github.com/funcx-faas/funcX/pull/1405 can be merged in afterwards, assuming the SDK/EP release goes as planned.  (readthedocs updates when it's merged to main, so #1405 does not need to be part of the release, but it can be)
> Bump versions for release 2.11.0 Jan 17 2024

- docs/endpoints.rst
Document how to configure AMQP ports on endpoints, and the new default port. Going to wait to merge this until after the next endpoint/SDK release, when I'll fill out the version number.
> Document endpoint AMQP port configuration

- compute_sdk/tests/conftest.py
- compute_sdk/tests/unit/test_client.py
`login_manager` was setting the Mock class to the yielded object, rather than creating a new instance.  This was leading to leakage between tests, which work for PR #1428 highlighted.
For the reviewer: the main changes of note are
- Implementation of a `test_client.py` specific `gcc` fixture.
- Removal of the `login_manager` fixture.
- Updating the tests that used `login_manager` to use the `gcc` fixture.
I marked this an quick review because most of the changes are plug and chug of the third bullet point.
- Bug fix (non-breaking change that fixes an issue) [in tests]
> Fix broken fixture

- changelog.d/20240122_102159_30907815+rjmello_retain_uep_config_exception.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
We will soon mark the `HighThroughputEngine` for deprecation.
> Change default engine type to `GlobusComputeEngine`

- changelog.d/20240123_115035_kevin_update_parsl.rst
- compute_endpoint/setup.py
Bring in a couple of minor fixes in Parsl, including some work relevant to endpoint robustness.
[sc-25274]
> Update parsl to 2024.01.22

- docs/endpoints.rst
- docs/index.rst
`shell` is a different than `console`.  Sphinx, for example, changes the prompt symbol color and takes care to make it not selectable.
> Update doc code blocks syntax highlighting

- changelog.d/20240111_165100_yadudoc1729_GCE_container_support_sc_28238.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_gce_container.py
- compute_endpoint/tests/unit/test_gce_container.py
- docs/endpoints.rst
This PR adds support for launching managers/workers in containers. Currently docker, singularity and apptainer are supported. Container support is limited to ``GlobusComputeEngine`` on the ``globus-compute-endpoint``. To
configure the endpoint the following options are now supported:
* `docker_container_uri` : Specify docker URI if using Docker
* `singularity_container_uri`: Specify singularity file path if using Singularity
* `apptainer_container_uri`: Specify path to apptainer sif file if using Apptainer
* `container_cmd_options`: Specify custom command options to pass to the container launch command,
such as filesystem mount paths, network options etc.
```
display_name: Docker
engine:
type: GlobusComputeEngine
docker_container_uri: funcx/kube-endpoint:main-3.10
container_cmd_options: …
```
> GCE container support

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
This is a test release version for the upcoming release process.
2.12.0a0 will be pushed to PyPI shortly.
Note that changelog/scriv collection will be done only on 2.12.0 release itself next Wednesday.
> Bump versions for alpha release 2.12.0a0 for testing release

- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/unit/test_worker.py
Another small preliminary PR for https://github.com/funcx-faas/funcX/pull/1434. Communicates the endpoint ID to workers so that they can return it as part of their task reporting, as discussed in scrum. 
> Send endpoint_id to workers and back to SDK

- changelog.d/20240205_123835_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/tests/unit/test_htex.py
Instead of breaking the endpoint, we now return an error to the user and log the exception.
[sc-27140]
> Gracefully handle invalid result msg for HTEngine

- docs/actionprovider.rst
As discussed with Ryan, the old Action Provider (dev.funcx.org/automate) hosted on Lambda has been turned down.  See note in # dev - no users had been using it for months.
There shouldn't be any complaints but the old AP now returns a response which directs to the readthedocs AP page.  To make it easier in case anyone needs to update their old flows, this is a further clarification on the 'upgrade' path.
The footnote, referenced after the ActionUrl, is near the top of the page, a bit prominent?  Perhaps we can move it to  the bottom of the page later as it should be relevant to few users.
> Add a note about upgrading from previous Action Provider

- changelog.d/20240208_180713_30907815+rjmello_pasl_htex_encryption.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/setup.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/unit/test_engines.py
Upgraded Parsl to version ``2024.02.05`` to enable encryption for the ``GlobusComputeEngine``. Under the hood, Parsl uses CurveZMQ to encrypt all communication channels between the engine and related nodes.
We enable encryption by default, but users can disable it by setting the ``encrypted`` configuration variable under the ``engine`` stanza to ``false``.
[sc-14420]
> Enable encryption for `GlobusComputeEngine`

- compute_endpoint/globus_compute_endpoint/strategies/base.py
This PR removes `BaseStrategy.notify` that is never used. 
> Removing dead code. BaseStrategy.notify is never used.

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/__init__.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
On the heels of [PR #578 (web-service)](https://github.com/globusonline/funcx-services/pull/578), implement the client-side aspect of informing the web-services that the MEP process is online and available.
[sc-30054]
> Implement MEP heartbeats

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
Need an alpha version on PyPI to test MEP heartbeat changes.  v2.13.0a2 has been pushed as of 10:30 CST
> Bump versions for alpha release v2.13.0a2

- compute_endpoint/globus_compute_endpoint/strategies/base.py
- compute_endpoint/globus_compute_endpoint/strategies/kube_simple.py
- compute_endpoint/globus_compute_endpoint/strategies/simple.py
- compute_endpoint/globus_compute_endpoint/strategies/test.py
- `threshold` is no longer utilized
- `_event_count` unused
- `_event_buffer` unused
- `.callback` is not a settable item; hard-code to `.strategize`
- Vastly simplify the interval waiting logic
- Improve the typing situation
- Begin (but only begin) the refactor `interchange` to `engine`.  This is what we're now using, but we need to flesh out the changes to the likes of kube_simple.py as well.  For another day.
> Remove vestigial items from strategy

- compute_endpoint/globus_compute_endpoint/strategies/base.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Motivated by pytest's durations report, reduce the unnecessary test delays from the `test_interchange` set of tests.  The core concept here is the iterations, not the actual time waited.
Reduces time taken for this collection of tests from ~24s to ~1.5s on my local hardware.
> Reduce unnecessary test delays

- changelog.d/20240227_130057_30907815+rjmello_gcengine_max_workers.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_engines.py
The default `user_config_template.yaml` file defines this attribute but the Parsl HTEX only supports `max_workers`. This is a temporary fix until we can update the attribute name in the Parsl HTEX.
If the user defines both `max_workers_per_node` and `max_workers`, the former will take precedence.
> Support `max_workers_per_node` attr for GCEngine

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/logging_config.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_logging_config.py
PR #1475 addressed the case of the UEP incorrectly assuming grandfathered access to the MEP's log file descriptor.  A tangential issue, however, is that some files are not rotatable.  For example, it is entirely feasible to symlink `endpoint.log` to `/dev/stdout`, in which case the RFH does the right thing and ignores it -- but it shouldn't have been setup in the first place.  So, do the first place thing, and don't set up the more correct logging handler.
[sc-30480]
> Globally address non-seekable log file

- changelog.d/20240301_105729_kevin_update_two_deps.rst
- compute_endpoint/setup.py
- compute_sdk/setup.py
Jinja2 update to silence the IDE complaint, but the Globus SDK update as we march toward Python 3.12 support (or, more sanguinely, ~6 months back is what we support).
> Two dependency updates

- changelog.d/20240302_235505_30907815+rjmello_container_launch_cmd.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_gce_container.py
`shlex.join()` adds quotes around launch command template placeholders for variables that do not have an option defined in the template. Thus, when the associated configuration variables are absent, the submit script will trigger an unrecognized arguments error.
I've decided to remove the code rather than fix it because we already have a Jinja template filter, `shell_escape` (see #1264), that enables endpoint admins to escape user-provided shell commands.
[sc-30541]
> Do not escape containerized launch command

- changelog.d/20240305_135742_30907815+rjmello.rst
- compute_endpoint/globus_compute_endpoint/logging_config.py
- compute_endpoint/tests/unit/test_logging_config.py
Our logging config did not include the parsl logger, resulting in no parsl logs showing up in `endpoint.log`.
[sc-30588]
> Ensure parsl logs propagate

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Users can view the template later via the web service API (see https://github.com/globusonline/funcx-services/pull/603).
[sc-29931]
> Include user config template in MEP registration

- changelog.d/20240308_113821_yadudoc1729_bump_parsl_pinned_version_to_2023_3_4.rst
- compute_endpoint/setup.py
Bumped parsl pinned version from ``2024.02.05`` to ``2024.3.4``
This version bump brings in following fixes:
- HTEX to support `max_workers_per_node` as a kwarg
- Better stdout/err reporting from failed tasks
- Support for detecting MISSING jobs
- Better HTEX interchange shutdown logic to avoid hung processes
> Bump parsl pinned version to 2023.3.4

- changelog.d/20240227_130057_30907815+rjmello_gcengine_max_workers.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
The Parsl HTEX supports both `max_workers` and `max_workers_per_node` as initialization arguments starting in version `2024.03.04`. The former is deprecated and will be removed in a future release.
[sc-30483]
> Remove `max_workers` rename in GCEngine

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Users should be able to set a display name on a multi-user endpoint.
> Include `display_name` in MEP registration payload

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- smoke_tests/tests/test_version.py
Un-skip test now that multi-user endpoints show as online.
> Bump version for alpha release

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
The `public` field indicates if all users can discover the multi-user endpoint via our web UI and API. This field is only supported on multi-user endpoints and does not control access to the endpoint; therefore, it should not be used as a security feature.
[sc-30385]
> Add support for `public` config field 

- changelog.d/20240321_121200_kevin_update_parsl.rst
- compute_endpoint/setup.py
Mostly to aid development and testing; there's nothing groundbreaking in this update of Parsl.
- Code maintenance
> Bump parsl pinned version to 2023.3.18

- RELEASING.md
- release.sh
(Split off from the version bump for 2.16.0a0)
- Removed redundant version file editing copy/paste
- Updated version naming scheme with current ones instead of '-dev'
- Added the long-postponed auto-pushing of the git tag so people won't forget
> update release notes and add git auto push tag

- changelog.d/20240326_114255_kevin_mu_more_robust_aws_amq_interaction.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/command_queue_subscriber.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
- compute_endpoint/tests/unit/test_command_queue_subscriber.py
- compute_endpoint/tests/unit/test_result_publisher.py
These were a temporary data structure hack for understanding interactions with AWS' RMQ.  Replace with the only important change: lots of retry attempts.
Meanwhile, per the ticket and identified needs, improve the logging situation by emitting RMQ connection updates at key times, while simultaneously not spamming the logs.
[sc-30467]
> Remove temporary cqs_/rp_ kwargs hack

- changelog.d/20240326_153234_30907815+rjmello_gc_common_pydantic_sc_26075.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/setup.cfg
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_sdk/setup.py
Version `0.4.0` of `globus-compute-common` contains a [module ](https://github.com/funcx-faas/funcx-common/blob/8fd10350629a4a5ca0e23440836d19d3b8fe5cda/src/globus_compute_common/pydantic_v1.py)that enables users to install either Pydantic V1 or V2. The former remains the recommended and officially supported version.
I also added the [Pydantic plugin for mypy](https://docs.pydantic.dev/1.10/usage/mypy/) to improve the ability of mypy to type-check our Pydantic code.
[sc-26075]
> Enable users to install Pydantic V2

- changelog.d/20240326_153234_30907815+rjmello_gc_common_pydantic_sc_26075.rst
- compute_endpoint/setup.py
- compute_endpoint/tox.ini
- compute_sdk/setup.py
Version `0.4.1` of `globus-compute-common` extends the Pydantic version range in its `setup.cfg` file to include V2, avoiding dependency conflicts with consuming packages.
[sc-26075]
> Fully support Pydantic V2

- changelog.d/20240328_144808_kevin_address_fail_counter_race_condition_reset.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
The EP world roughly revolves around heartbeats, an "I'm alive" notification that goes out, by default, every 30s.  In the interchange, we also use this interval to determine whether our connection is stable.  Unfortunately, if we only detect that our connection is stable _when we attempt to send a heartbeat_, then it's anyone's guess which thread wins: "successfully alive for a HB, mark as stable" vs "quiesce because we're clearly not stable."
This manifests as an EP staying up for much longer than the settings would otherwise attempt to enforce -- in the motivating case, almost an hour before the race condition finally caught up to the settings which wanted the EP to shutdown in roughly 2m, preventing the fix to the larger errant condition.
Work around this for now by bumping the …
> Reset retry counter after 2 HBs

- RELEASING.md
While doing the release today I noticed a few things still inaccurate in RELEASING.md, so might as well update it.
* one of the bash lines was missing the 3rd version file
* we don't do dev releases during production (*dev is no longer a thing)
> update release doc inline with current procedures

- changelog.d/20240313_135645_yadudoc1729_update_strategy.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/test_engines.py
`GlobusComputeEngine` currently uses globus-compute's `Strategy` code which is a fork of Parsl's `Strategy` implementation. This PR switched `GCE` over to use Parsl's `Strategy` instead.
Here's what to expect with these changes:
1. GlobusComputeEngine no longer takes the strategy class as a kwarg but rather you select from `None|'simple'`
2. Faulty configs where the batch scheduler immediately rejects jobs cause endpoint shutdown and submitted tasks that reach the endpoint return with an exception message with info on the failure
3. Faulty configs where batch jobs fail to have workers start (bad networking configuration, or python environment) are reported as `MissingJobs` that also cause endpoint shutdown.
- Bug fix …
> Update GlobusComputeEngine to use Parsl's `Strategy`

- docs/limits.rst
Our limits restrict inbound and outbound payloads to 10MB of serialized data. Previously our docs stated that it was 5MB in and 512KB out. This updates those numbers to 10MB and adds a little more info about the TASK_PAYLOAD_TOO_LARGE error returned when submitting large payloads, rather than the custom exception that was previously explained.
> Update the documentation to reflect the 10MB data limit

- docs/configs/worker_pinning.yaml
- docs/configuring.rst
We will soon deprecate the `HighThroughputEngine`.
[sc-32323]
> Update pinning workers config to use GCEngine

- compute_endpoint/packaging/Makefile
- compute_endpoint/packaging/create-prereqs-tarball.sh
- compute_endpoint/packaging/debian/changelog.in.in
- compute_endpoint/packaging/debian/rules
- compute_endpoint/packaging/fedora/globus-compute-endpoint.spec.in
The individual pieces and parts are laid out in the Makefile, extending the same workflow as introduced in [funcx sc-29028]/[sc-32395]/#1492.  Thus:
```console
$ make rpm
...
RPM package successfully built:
-rw-r--r-- 1 root root 16M Apr  7 15:31 dist/rpmbuild/RPMS/x86_64/globus-compute-endpoint-2.17.0-1.fc39.x86_64.rpm
```
Additional items from the Makefile which may be useful for debugging or development are accessible from a naked `make` invocation or `make help`.
The resulting `.rpm` has a dependency on Globus' Python[1], and will install the Globus Compute Endpoint agent code into `/opt/globus/`, as well as a symlink `/opt/globus/bin/globus-compute-endpoint` into `/usr/sbin/`.
Meanwhile, while lurking in the RPM build innards, realize that `/opt/globus/` is a venv for GCS, so set …
> Create an RPM package of the Endpoint

- changelog.d/20240415_191133_30907815+rjmello_extend_pyzmq_version_range.rst
- compute_endpoint/setup.py
We currently only support `pyzmq` versions up to `23.2.0`, but our code is compatible with the latest `26.x.x` versions.
> Expand pyzmq supported versions to <27.0.0

- compute_endpoint/packaging/Makefile
- compute_endpoint/packaging/fedora/globus-compute-agent.spec.in
OpenSUSE ... just likes to be different.  Per the Fedora spec, `HOME="$$(pwd)"` should be enough, but, per the output of `rpm --showrc | grep topdir`, it's clearly not in OpenSUSE's case.  #smh
Meanwhile, OpenSUSE's `make` implementation differs from (apparently) all others in that `$(shell ...)` does not accept `-c`.  Workaround that by manually invoking the shell.
Finally, reduce a dependency on `unzip` by bringing the `pip` update inline with the DEB package installation procedure: properly install via `pip` rather than the naive wheel unzipping.
[sc-33089]
> Fix OpenSUSE rpm builds

- compute_endpoint/tests/unit/test_logging_config.py
When running tests locally I discovered that this new one added a month ago that uses /proc/self is only linux based and does not work on mac.
The simple fix is to use a /dev equivalent for darwin.  See the answer with 9 upvotes in https://stackoverflow.com/questions/20974438/get-list-of-open-files-descriptors-in-os-x
> Fix test that uses /proc so it works on macOS

- endpoint_dev.Dockerfile
- local_dev/.gitignore
- local_dev/README.md
- local_dev/compose.yml
Globus Compute endpoints are only supported on Linux, so non-Linux users must utilize Docker containers (or similar) for their local development workflow. This work provides a sensible framework for doing so.
[sc-33088]
> Create docker compose workflow for EP dev

- changelog.d/20240418_203003_30907815+rjmello_validate_strategy_field_sc_33155.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/tests/unit/test_endpoint_config.py
We now raise an informative error when a user sets the ``strategy`` configuration field to an incorrect value type for a given engine. 
[sc-33155]
> Raise error for incompatible engine and strategy

- docs/configs/perlmutter.yaml
This PR updates the Perlmutter config example to use ``GlobusComputeEngine``. 
> Updating Perlmutter config to use GCE

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
We've discussed the ability for users to modify the UEP configuration at submission time, but we've not been explicit that they need create whole new objects when doing so.  So, do what we should have done in the first place, and snapshot the `TaskSubmissionInfo`.
Notably, this does _not_ address the possibility that users modify the args or kwargs to a function, but saving that for a future moment as that potentially comes with some memory concerns.  (This does too, but I think will be minimal compared to the possibility that args/kwargs might be much larger.)
[sc-33284]
> Snapshot per-task uep submission configuration

- docs/executor.rst
Change the default port that the Executor uses to connect to AMQP to 443 to match the new Endpoint config.yaml default amqp_port.
> Add amqp_port setting documentation in the Executor

- changelog.d/20240427_105242_kevin_gracefully_shutdown_after_broken_mq_connection.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
From the problem report, the relevant log lines were:
... :08:52,7 INFO MainProcess ... Thread ... .result_publisher:268 _on_queue_verified ResultPublisher<✓; o:1; t:0> Ready to send results to exchange: results
... :09:56,3 WARNING MainProcess ... Thread ... .result_publisher:244 _on_channel_closed ResultPublisher<✗; o:0; t:44> Channel closed  [<Channel number=1 CLOSED conn=<SelectConnection CLOSED transport=None params=<URLParameters host=compute.amqps.globus.org port=5671 virtual_host=/ ssl=True>>>
((320, 'CONNECTION_FORCED - Node was put into maintenance mode'))]
... :10:02,9 INFO MainProcess ... Thread ... .result_publisher:135 run ResultPublisher<✗; o:0; t:44> Opening connection to AMQP service.
... :10:03,1 WARNING MainProcess ... Thread ... .result_publisher:181 _on_open_failed …
> Daemonize threads, and still shutdown gracefully

- compute_sdk/globus_compute_sdk/sdk/batch.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
MPI applications require resource specifications for individual task execution. Users can define these when instantiating an `Executor` object, or via direct attribute assignment.
[sc-33025]
> Enable users to define per-task resource specs

- compute_endpoint/packaging/JenkinsFile
- compute_endpoint/packaging/Makefile
- compute_endpoint/packaging/create-prereqs-tarball.sh
- compute_endpoint/packaging/debian/changelog.in.in
- compute_endpoint/packaging/debian/control
- compute_endpoint/packaging/debian/rules
- compute_endpoint/packaging/fedora/globus-compute-agent.spec.in
Builds currently rely on Globus' internal Jenkins coordinator and infrastructure.  A fair number of changes here are to work with the CI infrastructure, which is a good bit more strict about placement of files and which utility does what task.
[sc-32896]
> Implement CI building

- docs/configs/bridges-2.yaml
Adding a tested config from Bridges@PSC that updates the config to use GCE instead of HighThroughputEngine.
> Updating Bridges2 config to use GCE

- changelog.d/20240429_144311_chris_package_systemd_unit.rst
- compute_endpoint/globus_compute_endpoint/boot_persistence.py
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_boot_persistence.py
- docs/endpoints.rst
Adds two commands, `enable-on-boot` and `disable-on-boot`, for managing systemd services for the endpoint. They're intended for interactive use rather than automation, so they don't directly call `systemctl`, rather they print out commands the admins can run. They also verify that the endpoint and the system are set up properly to enable/disable a systemd unit, and `enable-on-boot` automatically creates a unit file in the right place.
[sc-32913]
> Package systemd unit

- compute_endpoint/globus_compute_endpoint/boot_persistence.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_boot_persistence.py
Only check the `detach_endpoint` setting for single-user endpoints.  Meanwhile, if unable to write the unit file, share the content with the user.
> detach_endpoint isn't a thing on MEP

- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The fundamental missing detail was the missing data during function registration -- and that was mistakenly added to PR #1559 (544af0f97558af06a5c3a920095ef11813689fcc).  Follow up with a test change.
[sc-33481]
> Test already committed work

- docs/quickstart.rst
Includes the --include-deps flag in the quickstart example to install the endpoint.
> Update quickstart to specify --include-deps

- changelog.d/20240508_000749_kevin_idempotent_executor_shutdown.rst
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
At the point an executor has been shutdown, its state has already been set:
* `_stopped` is `True`
* `_result_watcher` is gone (`None`)
* `_task_submitter` is (nominally) stopped
In refactoring for idempotency (early return), realize that there is no use to `.join()` the task submitter thread.  The Python internals already clean up the underlying thread when the thread completes.  All `.join()` does is wait for that -- there is no resource value in waiting, only algorithm logic, if necessary.  Instead, take out the shutdown lock and drain the queue of tasks before sending the poison pill, then stop there.  The thread will either complete or it won't, but because it's `daemon=True`, it won't hold up the shutdown process.
[sc-33249]
> Make Executor shutdown idempotent

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
version changes for alpha release for QA.  Note that we previously used v2.20.0a0 for Globus World testing.
> Bump versions for QA release v2.20.0a1

- .github/workflows/ci.yaml
- .github/workflows/daily.yaml
- compute_endpoint/tox.ini
- compute_sdk/tox.ini
Dependabot fulfills our use case of SafetyCLI, and even creates PRs automatically.
[sc-33596]
> Remove SafetyCLI from GH actions

- docs/endpoints/single_user.rst
- docs/index.rst
- docs/quickstart.rst
We added --include-deps last week but the change was lost in the rewrite, adding it back in.
> add --include-deps to pipx install examples

- docs/endpoints/multi_user.rst
- docs/endpoints/single_user.rst
We deemed the last comments able to "wait another day" given the urgency of scheduling.  This PR is a follow-up #1566.
* Prefer SEP over CEP ("single user Compute endpoint")
* Reorganize and move a couple of sections
* Minor wording changes
* Minor formatting
[sc-33255]
> Respond to PR comments

- changelog.d/20240523_121518_30907815+rjmello_self_diag_mep_sc_33745.rst
- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
Modified the self diagnostic command to display all files with the expected file extensions, including those related multi-user endpoints.
I also slightly modified the self diagnostic output to clarify which commands use Python functions vs direct shell commands. This follows the hardware report implementation, which uses `python` in the command display names instead of `func`. The latter was somewhat unclear.
[sc-33745]
> Include MEP files in self diagnostic output

- changelog.d/20240523_154926_kevin_stop_mep_unrecoverable_auth_error.rst
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/command_queue_subscriber.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
- compute_endpoint/tests/unit/test_command_queue_subscriber.py
- compute_endpoint/tests/unit/test_result_publisher.py
Catch the known `ProbableAuthenticationError` and quit immediately.  Prior to this, the RP and CQS threads would try up to `attempt_limit` times, which could be up to 20 hours before failing.  No good.
[sc-33757]
> Stop immediately on unrecoverable error

- compute_endpoint/packaging/Makefile
- compute_endpoint/packaging/create-prereqs-tarball.sh
We should be building the SDK with the Endpoint for packaging, rather than relying on PyPI.  The earlier PR today attempted to do this, but still inadvertently relied on the network to download the pre-packaged SDK.  That's a problem for not-yet-released packages.
So, step 1 is to actually *build* the SDK package, and then step 2 is to educate the build script to not download (an older) version of the SDK.
- Bug fix (non-breaking change that fixes an issue) [more packaging; not user-facing]
> Build SDK as well as endpoint wheel for packaging

- docs/endpoints/configs/midway.yaml
Minor doc update for Midway3@RCC to use `GlobusComputeEngine` instead of `HighThroughputEngine`
> Updating Midway config to use GCE

- changelog.d/20240423_142117_yadudoc1729_gce_working_dir.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_working_dir.py
This PR fixes the issue where the endpoints using ``GCE`` would have functions run in the directory from which the endpoint was started rather than some well-defined location. This PR adds support for setting a ``working_dir`` option to 
configure function's working directory and for functions that create files a new sandboxing feature is added. Setting ``run_in_sandbox: True`` each function executes in a sandbox directory set to function_uuid as the name. 
Here's a config example:
``` yaml
display_name: WorkingDirExample
engine:
type: GlobusComputeEngine
working_dir: /projects/MY_PROJ
run_in_sandbox: True
```
[sc-32391]
- New feature (non-breaking change that adds …
> Support for setting working_dir and sandboxing in ``GlobusComputeEngine``

- compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
- compute_sdk/tests/unit/test_login_manager.py
The rebrand happened > 12 months ago, and the old-style credentials have not been in use for more than 2 years.
> Remove no-longer needed code

- changelog.d/20240612_164858_kevin_enable_configurable_interchange_debug.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
The `debug` state of the endpoint can now be set by configuration as well as the command line's `--debug`.  Per ticket description, if the CLI flag is specified, the configuration flag is ignored.  "Most specific wins," and the CLI is considered more specific.
[sc-34093]
> Teach UEP configuration `debug` flag

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- docs/endpoints/multi_user.rst
If the endpoint configuration is passed in via stdin and the configuration specifies `debug: True`, then emit the entire passed configuration yaml to the logs.
[sc-34149]
> Log anonymous configuration in debug

- compute_endpoint/globus_compute_endpoint/boot_persistence.py
This removes the "systemd service" verbiage, which is both redundant and nonstandard (other services do not reference the fact that they are services in their description).
> Reword default systemd service description

- .github/ISSUE_TEMPLATE/bug_report.md
After a GitHub issue someone opened a while back, I realized that we don't point users toward the self-diagnostic in our bug report template. Fixing that here.
> Add reference to `self-diagnostic` command in bug report template

- changelog.d/20240617_133114_30907815+rjmello_fix_gcengine_channel_check.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_engines.py
Some Parsl providers do not utilize `Channel` objects to communicate with resource managers (e.g., `KubernetesProvider`).
> Enable GCEngine to support providers w/o a channel

- changelog.d/20240410_130138_LeiGlobus_delete_remote_endpoint_sc_31206.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_logging_config.py
This adds functionality to delete endpoints when a local config is not present.
It differs from the original story in that this no longer uses t he --remote option, but just as part of normal delete, with the usual --yes and --force options behaving as they should intuitively.
A few notes:
- Modified ``get_ep_dir_by_name_or_uuid()`` to take an extra parameter with default so it doesn't raise if an UUID is specified that does not exist on the system, and also to pass the uuid on as an argument
- Added a new wrapper ``name_or_uuid_arg_non_local`` that takes advantage of the above without affecting the existing ``name_or_uuid_arg``
- Note that the happy deletion path calls the Globus Compute Client's ``delete_endpoint()`` which has the same name but is a direct API call via …
> Refactor endpoint delete to account for local, remote, or both

- changelog.d/20240622_114437_30907815+rjmello_add_bin_paths_to_self_diag.rst
- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
- compute_endpoint/tests/unit/test_cli_behavior.py
Included the paths to the ``globus-compute-endpoint`` and ``process_worker_pool.py`` executables in the ``self-diagnostic`` command output. These can help us to identify issues with a user's local environment.
> Add executable paths to self-diagnostic output

- changelog.d/20240628_090506_30907815+rjmello_bump_parsl_2024_06_10.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/setup.py
- compute_endpoint/tests/conftest.py
Bumped parsl dependency to version 2024.6.10. This required a couple of minor changes:
* As of Parsl PR https://github.com/Parsl/parsl/pull/3283, the initial HTEX block scale out occurs on the first strategy poll, not at HTEX start. Thus, our tests should use a small strategy period to speed them up and avoid timeouts.
* As of Parsl PR https://github.com/Parsl/parsl/pull/3338, the `dfk` argument for `JobStatusPoller` initialization is no longer supported.
> Bump parsl dependency version to 2024.6.10

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_resource_spec.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_htex_regression.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_htex.py
- compute_endpoint/tests/utils.py
This PR updates the Endpoint Interchange to pull the `resource_specification` for tasks from the RMQ message headers and pass those along to the GlobusComputeEngine. EngineBase is updated to allow passing resource_specification when `engine.submit` is called. If no `resource_specification` is passed, none is passed along to the engine retaining old behavior.
This functionality is not user-facing until a follow-up PR introduces `BashFunctions` and `MPIFunctions`, so I'm leaving out docs/changelog entries.
> Update Endpoint to pass on resource_specification to GCEngine

- changelog.d/20240702_104011_yadudoc1729_gce_run_tasks_in_working_dir.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_working_dir.py
By default the working_dir was set to the endpoint_dir, which results in BashFunctions quickly cluttering up the dir.
This change is added to collate output from BashFunctions in one directory.
``GlobusComputeEngine.working_dir`` now defaults to ``tasks_working_dir``
* When ``working_dir=relative_path``, tasks run in a path relative to the endpoint.run_dir.
The default is ``tasks_working_dir`` set relative to endpoint.run_dir.
* When ``working_dir=absolute_path``, tasks run in the specified absolute path
> Update GCE to run tasks in `tasks_working_dir`

- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_util.py
Our typical warning message:
Warning - dependency versions are mismatched between local SDK and remote worker on endpoint f93919c6-ceb7-4833-1dfe-ef3edbbea706: local SDK uses Python 3.11.9/Dill 0.3.6 but worker used 3.11.8/0.3.6
(worker SDK version: 2.22.0; worker OS: Linux-5.10.217-205.860.amzn2.x86_64-x86_64-with-glibc2.36)
has come up a few times when users were unsure about its actual impact. It is also displayed with minor PY version mismatches when that may not impact serialization.
We should make the message more clear, and possibly avoid minor version mismatches triggering the warning.
For now, until more team members give input, this PR leaves the micro-version checking logic alone, and only updates the warning message itself to be more helpful.
> Change version mismatch message, add logic to ignore Python micro # if desired

- changelog.d/20240627_181028_chris_mep_config_user_runtime.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/batch.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/tests/unit/test_client.py
- docs/endpoints/multi_user.rst
- docs/reference/client.rst
When submitting a task, the SDK now collects information about the user's runtime environment, such as Python version and Compute SDK version, which is sent alongside the task submission. In the case where this submission is to an MEP, the web service will (in a separate PR) include the new information in the MEP submission request. Then, the MEP renders the config template with that information as a variable named `user_runtime`. As documented here, this enables a workflow where admins can run UEPs under different Python versions depending on how the task was submitted.
[sc-34336](https://app.shortcut.com/globus/story/34336/send-information-about-a-user-s-runtime-environment-to-mep-config-renderer)
> Send information about a user's runtime environment to MEP config renderer

- changelog.d/20240612_140404_30907815+rjmello_pool_result_watchers_sc_33032.rst
- compute_sdk/globus_compute_sdk/sdk/asynchronous/compute_future.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/integration/test_executor_int.py
- compute_sdk/tests/unit/test_executor.py
Unless manually specified, `Executor` objects in the same process will share the same task group ID. To avoid having multiple consumers of the same task group RabbitMQ queue, we create a pool of task group-specific `_ResultWatcher` threads that are shared among `Executor` objects.
[sc-33032]
> Share task groups among Executor objects

- changelog.d/20240410_130138_LeiGlobus_delete_remote_endpoint_sc_31206.rst
- changelog.d/20240617_133114_30907815+rjmello_fix_gcengine_channel_check.rst
- changelog.d/20240622_114437_30907815+rjmello_add_bin_paths_to_self_diag.rst
- changelog.d/20240628_090506_30907815+rjmello_bump_parsl_2024_06_10.rst
- changelog.d/20240702_104011_yadudoc1729_gce_run_tasks_in_working_dir.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Collect changelog and bump versions for release
(pip-audit/lint fails until this is released as the current SDK version dependency isn't on PyPI until released)
> Bump versions for prod release 2.23.0 2024-07-10

- changelog.d/20240702_175644_30907815+rjmello_exec_cmd_sc_34376.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_gce_container.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_gce_container.py
This PR adds the `globus-compute-endpoint python-exec` command to run Python modules as scripts via the Globus Compute endpoint CLI.
E.g.,
```bash
globus-compute-endpoint python-exec parsl.executors.high_throughput.process_worker_pool --debug
```
We then use this to launch worker pools without requiring worker nodes to resolve the `process_worker_pool.py` command.
[sc-34376]
> Use endpoint CLI to launch worker pool

- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_util.py
- docs/sdk.rst
As referred to in scrum, this PR shortens the previous env difference message slightly and links to a new readthedocs.io section with more details on its implication.  Feel free to comment on the wording.
Also, this changes the above's output from logger.warning() to warnings.warn() to let the user manage warnings more easily.
Example new output:
```
>>> with Executor(endpoint_id='4b116d3c-1703-4f8f-9f6f-39921e5864df') as gce:
...     fut = gce.submit(abs, -1234)
...     print(fut.result())
...
/Users/lei/glob/funcX/compute_sdk/globus_compute_sdk/sdk/client.py:192: UserWarning:
Environment differences detected between local SDK and endpoint ab77c7ab-265b-d1db-870d-9d3715242fa1 workers:
SDK: Python 3.10.4/Dill 0.3.5.1
Workers: Python 3.11.8/Dill 0.3.6
This may cause serialization issues. …
```
> Reformat env difference warning again and link to readthedocs

- RELEASING.md
Using a merge commit, rather than squash or rebase, will ensure that the tagged commit from the release branch is properly included in the `main` branch.
> Use merge commit during release process

- changelog.d/20240711_190719_yadudoc1729_mpi_engine_2.rst
- compute_endpoint/globus_compute_endpoint/engines/__init__.py
- compute_endpoint/globus_compute_endpoint/engines/globus_mpi.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
- docs/endpoints/configs/expanse_mpi.yaml
- docs/endpoints/endpoint_examples.rst
- docs/reference/engine.rst
- docs/reference/index.rst
- docs/reference/mpi_engine.rst
This PR adds support for `GlobusMPIEngine` with better support for MPI applications.
`GlobusMPIEngine` uses Parsl's `MPIExecutor` under the covers to dynamically partition a single batch job to schedule MPI tasks. I'm not adding integration tests that confirm proper MPI launches since those exist in Parsl, and tend to be really slow.
Here's an example endpoint configuration that uses `GlobusMPIEngine`
``` yaml
display_name: MPIEngine@Expanse.SDSC
engine:
type: GlobusMPIEngine
mpi_launcher: srun
address:
type: address_by_interface
ifname: ib0
provider:
type: SlurmProvider
partition: compute
account: chi150
launcher:
type: SimpleLauncher
worker_init: "source ~/setup_funcx_test_env.sh"
nodes_per_block: 2
init_blocks: 0
min_blocks: 0
max_blocks: 1
walltime: 00:05:00
``` …
> Adding `GlobusMPIEngine` to support MPI applications

- changelog.d/20240710_113622_30907815+rjmello_tqs_thread_sc_34463.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- compute_endpoint/tests/integration/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
Pulling tasks from RabbitMQ is now performed via a thread within the main endpoint process, rather than a separate process. This reduces the endpoint's overall memory footprint and fixes sporadic issues in which the formerly forked process would inherit thread locks.
The new `TaskQueueSubscriber` follows the design and functionality of the `CommandQueueSubscriber`. I plan to move common code between these classes to a base queue subscriber class in a subsequent PR.
[sc-34463]
> Convert `TaskQueueSubscriber` to a thread

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/ci.yaml
- README.rst
- changelog.d/20240731_163659_yadudoc1729_update_sdk_to_drop_py3_7.rst
- compute_endpoint/setup.py
- compute_sdk/setup.py
We are well over a year since Python3.7 reached EOL (2023-06-27). Parsl now only supports 3.8+. 
This PR drops support for support for 3.7 and removes 3.7 from test targets in CI.
> Drop support for Python3.7

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
The `python-exec` CLI command now uses `execvpe` to replace the existing process rather than launch an additional subprocess. This reduces some process complexity and ensures that signals make it to their intended destination.
> Make python-exec replace the existing process

- changelog.d/20240807_114300_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_engines.py
Bumping parsl to version 2024.8.5 required a couple of changes:
- Parsl's `HighThroughputExecutor` now launches its interchange process via the `interchange.py` command. To avoid PATH-related issues, we utilize our `python-exec` endpoint CLI command to launch the interchange, as we do for the process worker pool.
- Updated the `GlobusComputeEngine` to use the `scale_out_facade` and `scale_in_facade` methods from Parsl's `HighThroughputExecutor`, which are now intended for external use.
[sc-34891]
> Bump parsl dependency to v2024.8.5

- docs/endpoints/configs/kube.yaml
Updated the Kubernetes example endpoint configuration to use `GlobusComputeEngine` and Parsl's `KubernetesProvider`.
> Update K8s example to use GlobusComputeEngine

- compute_endpoint/setup.py
The latest globus-compute-endpoint, which upgraded to a more recent version of parsl, started generating this error message on endpoint CLI commands:
```
/opt/globus-compute-agent/venv-py39/lib/python3.9/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES a
nd will be removed from this module in 48.0.0.                                                                                                                                                               
"cipher": algorithms.TripleDES, …
```
> update parsl to latest to avoid cryptography version warning

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The endpoint registration API route now accepts the endpoint's raw configuration file content as a string for UI display purposes. We will keep the JSON object config field in place until the web app team has started using the new field.
[sc-33036]
> Include config file content in EP registration

- changelog.d/20240814_122332_kevin_remove_websockets_from_dependency.rst
- compute_sdk/setup.py
We removed the last vestigial use of websockets in July 2023:
commit dacdc8ee6fccbc2f77a3d478860a3231ce77cb58
Date:   Tue Jul 25 14:22:04 2023 -0500
Remove deprecated "asynchronous" mode from Client
This was a forgotten dependency removal.
With thanks to @dylanmcreynolds for pointing this out.
Fixes #1624
Closes #1626
> Remove no-longer-needed dependency

- compute_endpoint/tests/conftest.py
As evidenced by a recent CI failure, the tests expecta `nodeslist` to be a list of least 1 item in length.  As written, there's 1 in 99 change that it doesn't:
```python
limit = random.randint(1, 100)  # but say limit yields 1, then:
yield [f"NODE{node_i}" for node_i in range(1, limit)]  # is an empty list.  DOH!
```
> Fix broken MPI test

- changelog.d/20240811_174452_chris_remove_whitelist.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_web_client.py
With the config-based `allowed_functions` feature, managing endpoint allow-lists via `add_to_whitelist` and `delete_from_whitelist` does not work as expected. Since `allowed_functions` is the recommended route, this simply removes those broken features.
[[sc-34835]](https://app.shortcut.com/globus/story/34835/remove-remote-whitelist-commands-from-sdk-and-api)
> Remove remote whitelist commands

- docs/endpoints/configs/midway.yaml
- docs/endpoints/configs/midway_apptainer.yaml
- docs/endpoints/endpoint_examples.rst
This PR makes a number of updates to the Midway container configuration examples. Notably, it updates the container example to use `GlobusComputeEngine` instead of `HighThroughputEngine` and sets the container type to Apptainer, reflecting Singularity's renaming in 2021.
> Update Midway config examples

- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
`try_assert` is a function, rather than a Python builtin; the `fail_msg` needs to be given to it.
> Submit message to function

- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Copy pasta oversight, I suspect.  In short, the `_channel` is the structure under test, so await its existence before continuing.  Else, it's a race-condition of whether that points to a None, or a test-expected structure.
> Test-await the thing under test

- compute_endpoint/tests/unit/test_engines.py
The underlying tested code was not incorrect, but the live call log was reporting a suspicious traceback, culminating in a Pydantic error:
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Result
task_id
value is not a valid uuid (type=type_error.uuid)
That was caused by incorrect data sent by the test, resulting in a task_id of:
...
'task_id': <function double at 0x71221d039d00>
...
Clearly incorrect.  So, correct the test call-site to more strongly verify that the test tests the appropriate detail and to remove the suspicious traceback. The implementation is mainly fixing `test_proc_pool_engine_not_started`, but update the surrounding tests in the module with the newly implemented fixtures for consistency.
> Fix test-passed data

- .github/workflows/ci.yaml
What was once plenty/an overkill amount of time is apparently biting us on "slow network days."  So, bump this value just a smidgen.
> Update CI job timing

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
Whether or not a `Config()` object gets instantiated, merely importing the file had the side-effect of instantiating an Engine.  This comes with a network lookup which need not be paid if the configuration doesn't actually require a Engine.  The main example: MEP.
> Do not prematurely create (default) Engine

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Version 26.1.1 of `pyzmq` manually sets the LDFLAGS environment variable during the `libzmq` installation process, causing installation failures on some systems. To prevent these issues, we set the upper bound for `pyzmq` to 26.1.0 until `pyzmq` developers resolve the bug.
Ref: https://github.com/zeromq/pyzmq/pull/2014
> Hotfix(v2.27.1): Set upper bound for `pyzmq` to avoid bug

- changelog.d/20240821_225122_kevin_remove_long_deprecated_client_args.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
The last deprecation was in Summer, 2023.  Ref: 14c4b3c07389889c16eb53a1c7fb97bf2376112a
> Remove long-deprecated args to Client

- compute_endpoint/tests/unit/test_config_utils.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
These tests verify the rendering of the Jinja templates, and don't touch the EndpointManager routines at all.  Accordingly, move them to their own unit file.
> Move tests to their own unit file

- compute_endpoint/tests/unit/test_endpointinterchange.py
Same fix as in b9eae39699901c433e378f26247e98cd31139c2d (via PR #1635)
Short version: mock away unnecessary (thread) class.
> Reduce test noise

- changelog.d/20240822_230438_kevin_redirect_stdstreams_to_eplog.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Update MEP logic to direct UEP `stdout` and `stderr` to the `endpoint.log` file rather than the dev null.  This will aid (has already aided) in bootstrap debugging the MEP/UEP deployment experience.
[sc-35380]
> Write std streams to log; don't ignore

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/logging_config.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The pre-exec environment was the initial place for the configuration emission during development, but that proved a problem as it was never stored -- it wasn't very debuggable for regular users!  Thus, moved it to the post-exec environment so it would show up in logs.
However, this poses a problem if *something* happens before logging is setup and the string is written -- debugging the rendered template is not possible then.  Instead, piggy back on the recent std-stream to `endpoint.log` work to move configuration emission to prior to exec, and guarantee that it makes it to the log file.  This also avoids the odd check-if-config-is-a-string to decide whether to write it to the log.  The pre-exec environment has the information that it's ephemeral and can thus just log it.
- Code …
> Move conf debug emission to preexec

- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
This PR updates the retry tests to use mocked executors to speed up test runtimes.
> Updating retry tests to use mocked executors

- compute_endpoint/tests/unit/test_engines.py
This test was added in #1472, during an interim period before Parsl had the updated parameters.  Parsl nominally is responsible for verifying this behavior, not us.
> Remove vestigial test

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/globus_mpi.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
- compute_endpoint/tests/unit/test_engines.py
There is no sense in duplicating the arguments.  Update related `GlobusMPIEngine` docstring and tests.
> Remove redundant GlobusMPIEngine arguments

- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_shell_functions.py
- compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_htex_regression.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/unit/test_htex.py
- compute_endpoint/tests/unit/test_worker.py
- compute_endpoint/tests/unit/test_working_dir.py
We have the fixtures, let's use them.  Take a more global look at some of the tests; move a helpful fixture (`ez_pack_task`) to the top-level `conftest.py`, then reference it where appropriate.
Dedup the lines by over half.
> Refactor selected tests to use fixtures

- changelog.d/20240905_180131_30907815+rjmello_allow_client_id_alone.rst
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/client_login.py
- compute_sdk/tests/unit/test_login_manager.py
Defining the `GLOBUS_COMPUTE_CLIENT_ID` environment variable without defining `GLOBUS_COMPUTE_SECRET_KEY` is a valid use case. The reverse, however, is not and will still raise an exception.
> Allow `GLOBUS_COMPUTE_CLIENT_ID` env var alone

- changelog.d/20240919_155327_chris_json_serializer.rst
- compute_sdk/globus_compute_sdk/errors/error_types.py
- compute_sdk/globus_compute_sdk/serialize/__init__.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- docs/sdk.rst
Adds `JSONData` serialization strategy. Also tweaks the serde error message wording a little bit.
```python
from globus_compute_sdk.serialize import ComputeSerializer, JSONData
serde = ComputeSerializer(strategy_data=JSONData())
print(serde.deserialize(serde.serialize({"some": ["json", "data"]})))
not_json = JSONData()
serde.serialize(not_json)
```
See `tests/integration/test_serialization.py:test_check_strategies` for a test that exercises this.
[[sc-35783]](https://app.shortcut.com/globus/story/35783/support-json-serializer-for-args-and-kwargs)
> Implement JSON serialization strategy

- compute_endpoint/tox.ini
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
- compute_sdk/tox.ini
Update mypy as consequence of an unrelated change that removing these deprecated args now seems to trigger.  1.11.2 does not fail where 1.10.0 did. :shrug:
> Remove obsolete Executor args

- Makefile
- docs/autobuild.sh
Annoyed by alt-tab and up-enter interactions, I submit this simple script to watch for change on the filesystem and automatically run `make html`.  At which point, it runs every time any file is modified in docs/, and all the dev need do is reload the relevant page in the browser.
Only caveat is that the script looks for changes _in the git index_.  So new files that have not yet been added to git's watch list won't be considered. (Simple fix == `git add <docs/your/new/file>`)
- New feature (for devs)
> Autobuild docs on file changes

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
If a log file exists, then `os.open` was opening the file as expected.  But I forgot to include the `O_CREAT` flag so new endpoints would fail to start when the log file would fail to open.  Whoops!
Luckily we caught this before the recent log changes were released; no changelog necessary.
- Bug fix (but caught before feature release so win!)
> Allow UEPs to create log files

- docs/changelog.rst
- docs/endpoints/multi_user.rst
Mostly just correct a few reST oversights (like single backtick to double-backtick), and add links and semantic markup (like `:class:...`).
This should basically be an easy review, and "almost quick."  But I'll stop just shy of marking the PR as `quick-review`.
> Touchup changelog

- changelog.d/20240918_223810_kevin_bursty_rate_limit_executor_submit.rst
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
The Executor currently drains the incoming task queue or stops draining at `.batch_size` before submitting to the API.  If tasks are `.submit()`ed at just the right cadence, it's possible to get the Executor to send lots of small batches very frequently rather than coalescing more tasks.
The fix implemented here is to allow up to 5 back-to-back API `/submit` calls within a window of 25s.  If more API calls come in after than, then induce up to a 6s delay so as to play nice with the API.  The burst window will hopefully be ample to work within a Jupyter notebook and not be an annoyance to a human working through cells, and only up to a 6s delay after that until the window clears.
(Discovered via log trawling and conversations with a user in funcx#help.)
[sc-35759]
Choose which options …
> Teach Executor a bursty rate-limit

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
There's a distinction between the file permissions, and the descriptor permissions.  The descriptor, per stdout and stderr needs only to be writable. But the file, per other tools, needs to be readable.  `chmod` is easy enough to invoke, but there's no need to for us to do the weird thing here.  So, create the file with user rw perms.
Before:
```console
$ cd ~/.globus_compute/uep.[mep_uuid].[uep_uuid1]/
$ ls -l endpoint.log
--w------- 1 kevin kevin 367 Sep 30  7:49 endpoint.log
```
After:
```console
$ cd ~/.globus_compute/uep.[mep_uuid].[uep_uuid2]/
$ ls -l endpoint.log
-rw------- 1 kevin kevin 367 Sep 30  7:51 endpoint.log
```
> Make UEP endpoint.log readable by default

- changelog.d/20241008_092953_kevin_improve_double_registration_error_message.rst
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
The observed behavior in the wild was that a double registration would complain (correctly), but reference `None` as the function id.  Clearly not helpful. Improve the situation by referencing the cached value, but also relax the double-registration constraint slightly: if the calling code attempts to re-register the function with the _same_ id, then that's odd -- so warn about it -- but let it go.  Still raise the exception for other errant registration attempts.
[sc-36241]
> Improve error message for errant func registration

- smoke_tests/tests/test_running_functions.py
See [story description](https://app.shortcut.com/globus/story/36175/intermittent-failing-hourly-test-with-timeouterror) - increase timeout in case this helps with the occasional failing hourly test.
[sc-36175]
> increase smoke_test timeout for intermittent failure

- docs/endpoints/configs/kube.yaml
A recent change (PR #1654) to the default `label` argument value passed to the `HighThroughputExecutor` causes Parsl's `KubernetesProvider` to hit a maximum character limit for pod labels.
Users should be able to specify labels of almost any length without causing issues, so this should be addressed directly in Parsl. For now, to help users avoid this bug, the example config manually sets a short label value.
> Add short label to Kubernetes example config

- docs/endpoints/single_user.rst
- docs/index.rst
- docs/quickstart.rst
As of https://github.com/globus/globus-compute/pull/1600, we call Parsl's `process_worker_pool.py` script via the `python exec` endpoint CLI subcommand. Hence, this flag is no longer necessary.
> Remove pipx --include-deps flag from docs

- compute_sdk/globus_compute_sdk/sdk/diagnostic.py
- compute_sdk/tests/unit/test_diagnostic.py
The recently refactored diagnostic command is silent when doing the default zip option without the --verbose flag.
Too silent - if the diagnostic is quick, there is no information for the user of what happened, and the command completes with no output - may be confusing to the user 'did it work?'.
On Josh's suggestion, this PR adds a simple message acknowledging that the diagnostic was run, and what the generated filename is, see attached screenshot for the normal and --verbose outputs., compared to previous behavior.
(previously, without info)
> add diagnostic ack message with file name

- changelog.d/20241017_111821_30907815+rjmello_fix_authz_lm_auth_client.rst
- compute_sdk/globus_compute_sdk/sdk/login_manager/authorizer_login_manager.py
- compute_sdk/tests/unit/test_authorizer_login_manager.py
The `AuthorizerLoginManager.get_auth_client()` method used the wrong resource server name to get the relevant authorizer, leading to a `KeyError`. This cropped up because, as of #1661, the `Client` calls this method directly.
[sc-36693]
> Fix AuthorizerLoginManager KeyError

- compute_endpoint/tests/unit/test_endpointmanager_unit.py
> epmanager tests DRY refactor

- .github/workflows/ci.yaml
- README.rst
- changelog.d/20241023_194824_30907815+rjmello_HEAD.rst
- compute_endpoint/setup.py
- compute_endpoint/tox.ini
- compute_sdk/setup.py
- compute_sdk/tox.ini
- docs/quickstart.rst
Python 3.8 entered the end-of-life phase on 10-07-2024, and Parsl dropped support in v2024.10.14.
Ref: https://peps.python.org/pep-0569/
> Drop support for Python 3.8

- changelog.d/20241023_153605_30907815+rjmello_bump_parsl_2024_10_21.rst
- compute_endpoint/setup.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
Pinned `parsl` dependency to version 2024.10.21.
[sc-36694]
> Bump parsl dependency to 2024.10.21

- docs/endpoints/configs/kube.yaml
We recently bumped our parsl dependency to version 2024.10.21 (#1693), which [includes a fix](https://github.com/Parsl/parsl/pull/3639) ensuring that the default pod names and labels for the `KubernetesProvider` comply with Kubernetes naming conventions.
Cross-ref: https://github.com/globus/globus-compute/pull/1681
> Drop temporary fixes to Kubernetes example config

- changelog.d/20241030_122237_30907815+rjmello_fix_globus_app_stdin_check.rst
- compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
- compute_sdk/tests/unit/auth/test_globus_app.py
In cases where stdin is closed or not a TTY, we now only raise an error if the user requires an interactive login flow (i.e., does not have cached credentials).
[sc-37125]
> Skip errors when stdin closed if creds cached

- compute_sdk/tests/unit/test_executor.py
The pytest-mock plugin was complaining (warning!) about our context management ... which is to-do with what these two particular tests test.  :facepalm:
.../globus_compute_sdk/sdk/executor.py:786: PytestMockWarning: ... do not need to be used as context managers.
> Clear test-induced warning

- compute_sdk/tests/unit/test_executor.py
Ensure that infrastructure is in place before we let the tests poke at it.  The flakiness is a very rare occurrence&nbsp;&mdash;&nbsp;I've only encountered it once, recently&nbsp;&mdash;&nbsp;but flaky == no good.
> Fixup a flaky test setup

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_cli_behavior.py
The MEP does not use an Executor, and even takes pains to prevent it from being specified (e.g., from user error or oversight) in the MEP configuration. However, because the MEP and UEP have initially shared the same basal data structure, and the `Config()` object historically automatically created the Executor, the MEP codes have been needlessly instantiating a useless executor. No more.
> Don't needlessly instantiate GlobusComputeExecutor

- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_boot_persistence.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_engines.py
The core of this change revolves around:
- reducing splatter of tests that don't need the `GlobusComputeEngine`; these mostly use `ThreadPoolEngine` now
- Specifying `address="127.0.0.1"` for those tests that do need the `GlobusComputeEngine`&nbsp;&mdash;&nbsp;for the tests, there should be no need to look farther than home
At a cleanliness level, this set of changes should not be controversial&nbsp;&mdash;&nbsp;the tests have no business making arbitrary lookups of the network.  Pragmatically, this also improves performance (negligible on fast networks, but by a good amount on slow networks).
To the reviewer: I waffled on `quick-review`, but I think the changes, while somewhat numerous, are basically the same thing over and over.
> Reduce spurious DNS lookups in tests

- compute_sdk/tests/unit/test_executor.py
In 4f6e7aa897629f5d36fb3b2229e8bc154696e763 (#1421), the `gc_executor` started using `MockedExecutor`.  This also removed the need to create a separate mocked Client.  To keep the change at the time focused on that, the changeset did not remove the now-superfluous `gcc` part of the yield.
This changeset now cleans up that refactor, and the core of this change is:
```diff
-def gc_executor(mock_result_watcher):
-    gce = MockedExecutor()
-    yield gce.client, gce
+def gce(mock_result_watcher):
+    gc_executor = MockedExecutor()
+    yield gc_executor
```
The `yield` statement is the key change, but the renaming of the fixture is intended to reduce the other necessary changes, since the tests that use this fixture use `gce` as their executor variable.
> Mild executor fixture refactor

- compute_endpoint/globus_compute_endpoint/boot_persistence.py
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/__init__.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_boot_persistence.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_config_utils.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_engines.py
To date, we've been comingling the MEP and UEP configurations in `Config`.  At this time, the two implementations are starting to diverge in their overlap, so bite the bullet and be clear about the differences.  This implementation uses `BaseConfig` for the shared attributes, maintains `Config` for backward compatability, and introduces `UserEndpointConfig` for the user endpoint and `ManagerEndpointConfig` for the endpoint manager configuration.
The core of the changes start in `endpoint/config/config.py`, where `UserEndpointConfig` (for UEPs) and `ManagerEndpointConfig` (for MEPs) are defined. These are backed up by requisite changes to the Pydantic model in `config/model.py`,  Just about every other change is in support of the now-distinct configuration classes.
Notes:
- test coverage …
> Separate MultiUser configuration

- changelog.d/20241101_153924_chris_function_name_code.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
* Add a check to ensure function_name and function_code cannot be present if function is provided to FunctionRegistrationData
* Deprecate the function_name argument to Client.register_function, as it was not being used
[[sc-34831]](https://app.shortcut.com/globus/story/34831/sdk-behavior-when-function-code-and-function-name-are-both-specified)
> Disallow function and function_name

- compute_endpoint/globus_compute_endpoint/engines/base.py
This PR updates type hints to use future annotations and move away from the typing module (although not completely). There are no  functional changes here.
This PR:
* Removes Union, Optional, List, Dict hints from typing.
* We still keep t.Callable and t.Any
> Updating `GlobusComputeEngineBase` to use future annotations

- changelog.d/20241023_095610_yadudoc1729_configure_tasks_working_dir.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/unit/test_worker.py
- compute_endpoint/tests/unit/test_working_dir.py
- compute_endpoint/tests/utils.py
Currently `ThreadPoolEngine` and `ProcessPoolEngine` now pass the working_dir: default `tasks_working_dir`. 
Executing functions on these engines affect subsequent function execution when they say change directory for eg, unlike `GlobusComputeEngine`. When executing functions, our `execute_task` wrapper currently attempts to look for a `tasks_working_dir` in the current dir, creates it if not present, and then switches into it. Unfortunately, each subsequent function finds itself one directory deeper.
* This PR updates `GlobusComputeEngineBase` to check if the `working_dir` is an absolute path, and if not make it absolute. This ensures that every function would run in `~/.globus_compute/<endpoint_name>/tasks_working_dir`.
* `working_dir` is now a configurable option for all engines.
* …
> Enable working_dir configurability and safety

- compute_endpoint/globus_compute_endpoint/engines/helper.py
No functional change but move result length check one level higher in the call stack.  There's no sense in passing the size limit.  `_call_user_function`'s purview is to invoke the function.  Checking the result validity is for the higher-level helper.
While in `_call_user_function`, make IDE slightly happier by not shadowing the module variable.
> Move result size check one level higher

- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/utils.py
Move `divide` to utils, and remove the recently unreferenced `div_zero`.  While here, make the test slightly more honest by using random numbers.
> Move test task kernel to utils

- compute_endpoint/tests/unit/test_htex.py
Was manually creating a hard-coded path in `/tmp/`.  No good.  Update to use `tmp_path` fixture.
> Remove test detritus

- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_execute_task.py
- compute_endpoint/tests/unit/test_worker.py
`run_dir` is not optional; in a previous commit, it was enforced by an inline check.  Update the function signature to match that requirement.
While here, test the addition, and also bolster the module's tests in general.
> Update execute_task signature

- changelog.d/20241114_143416_yadudoc1729_require_engine_start.rst
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/test_engines.py
This PR adds a flag to `GlobusComputeEngineBase` to ensure that engine is started before task submission is allowed. Engine will raise an `AssertionError` if a task is submitted before it was started.
These checks are mainly for tests that miss engine misconfiguration. 
> Require engine.start before engine allows task submission

- changelog.d/20241101_155044_chris_function_description_from_docstring.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
- docs/sdk.rst
Following our UI discussion today, it occurred to me that we don't have a user-friendly way to add a description to a function. Reading docstrings like this is really easy, so figured I'd knock it out while its on my mind (even though we don't really do anything with function descriptions yet).
~~Currently includes the changes from the other work it's based off of from #1699, hence the draft mode.~~
[[sc-37237]](https://app.shortcut.com/globus/story/37237/register-function-docstrings-as-function-descriptions)
> Function description from docstring

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- docs/endpoints/config_reference.rst
- docs/endpoints/index.rst
We have plenty of examples of known working configurations.  But what we don't currently have is exhaustive documentation on what the YAML files support.  Start to address that oversight.
Reviewer reminder: one can build the docs by invoking `docs/autobuild.sh`, which also starts a local-only web server to serve them.
> Add general config documentation

- .github/workflows/ci.yaml
- changelog.d/20241111_160525_chris_new_pythons.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_endpoint/tox.ini
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/version.py
- compute_sdk/setup.py
- compute_sdk/tox.ini
* Fix deserialization code to use a dedicated namespace instead of `locals`, due to new strictness from 3.13
* Bump GIM and `globus-compute-common` to versions that officially support 3.12 and 3.13
* https://github.com/globusonline/globus-identity-mapping/pull/25
* https://github.com/globus/globus-compute-common/pull/135
* Update test matrices in `tox.ini`s and `ci.yaml`
[[sc-37235]](https://app.shortcut.com/globus/story/37235/add-support-for-recent-python-versions-to-compute-sdk-endpoint)
> Add support for Pythons 3.12 and 3.13

- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/utils.py
Having written this function multiple times, then pulled it out of the tests fixtures while poking at the engines before throwing it away N more times, recognize that it's perhaps a REPL-useful utility.  Documentation for the dev inline, while the core is still used by the test fixtures.
- New feature (entirely oriented toward devs hacking on the engines)
> Make test function readily-REPL-available

- docs/endpoints/multi_user.rst
Update example names to more neutral ones.
> Updating example names to be more neutral

- changelog.d/20241114_172127_chris_remove_tty_checks.rst
- compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
- compute_sdk/setup.py
- compute_sdk/tests/unit/auth/test_globus_app.py
`globus-sdk==3.47.0` handles this class of errors for us by informing users on what to do when `input` receives `EOFError` during login flows.
[[sc-37236]](https://app.shortcut.com/globus/story/37236/move-interactive-terminal-check-on-login-code-to-globus-sdk)
> Remove code that checks if the user is in a TTY

- .github/workflows/ci.yaml
- changelog.d/20241111_160525_chris_new_pythons.rst
- compute_endpoint/tox.ini
- compute_sdk/tox.ini
During testing, it was discovered that the following error happens when starting an endpoint on py313. Pulling support for that version until a future release while diagnosing the error.
```
File "/Users/chris/opt/anaconda3/envs/gce-py313/bin/globus-compute-endpoint", line 8, in <module>
sys.exit(cli_run())
~~~~~~~^^
File "/Users/chris/opt/anaconda3/envs/gce-py313/lib/python3.13/site-packages/globus_compute_endpoint/cli.py", line 984, in cli_run
app()
~~~^^
File "/Users/chris/opt/anaconda3/envs/gce-py313/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/Users/chris/opt/anaconda3/envs/gce-py313/lib/python3.13/site-packages/click/core.py", line 1078, in main
rv = …
```
> Drop support for Python 3.13

- docs/actionprovider.rst
Add documentation on the input format of the new AP, and provide some guidance for migration.
[[sc-32291]](https://app.shortcut.com/globus/story/32291/add-v3-schema-as-new-routes-to-action-provider)
> Document V3 of Compute Action Provider

- changelog.d/20241126_104747_LeiGlobus_bump_parsl_11_25.rst
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
- compute_endpoint/setup.py
Bumping parsl mostly works, except that Compute uses a method that's been removed/cleaned up in Parsl:
https://github.com/Parsl/parsl/pull/3689
The original code does a redundant makedirs anyway - if the child is made, the parent is also created.
*edit* However, I left the parent's makedirs() in anyway, because the original child dir creation had a different default permission, just in case.
> Bump parsl 11 25 and remove reference to removed method

- changelog.d/20241115_095433_kevin_implement_pam_for_meps.rst
- compute_endpoint/globus_compute_endpoint/boot_persistence.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/__init__.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/pam.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/pam/__init__.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_pam.py
- docs/endpoints/config_reference.rst
- docs/endpoints/multi_user.rst
PAM (Pluggable Authentication Modules) is an opt-in configuration item for `ManagerEndpointConfig`.  As documented in this PR, it is enabled via the `pam` configuration item, and defaults to false/not enabled if not specified:
```yaml
multi_user: true
pam:
enable: true
```
I was unable to find a suitable Python PAM implementation for our needs, so ended up creating a PAM wrapper.  In particular, all of the PAM implementations I found seemed to only implement the `pam_authenticate()` method, but we need the `pam_acct_mgmt()` and `pam_*_session()` functions.  Until I'm educated otherwise then, our internal library appears to be more fully featured than other Python PAM implementations&nbsp;&mdash;&nbsp;we may pull it out and offer it as an independent project at some point.
[sc-36027]
- New …
> Implement PAM for MEPs

- compute_endpoint/globus_compute_endpoint/cli.py
Non-functional change; independent of upcoming refactor, so pulling out for clarity.
> Reduce variable scope

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Update recent logic to only force UEPs to a certain function allow list iff the parent MEP has such a list.  If the parent MEP is _not_ otherwise restricted, then let the UEP's configuration decide.  This allows administrators to use Jinja logic to have different users restricted to different functions.
> Allow UEPs to restrict functions

- RELEASING.md
This is the documented procedure to build DEB/RPM packages.  It was part of the build_for_stable branch, now separated so we can merge it into main.
> document package pushing procedures

- changelog.d/20241205_121009_30907815+rjmello_bum_dill_v0_3_9.rst
- compute_sdk/setup.py
Bumped ``dill`` dependency to version 0.3.9 for Python 3.11+.
> Bumped dill dependency to v0.3.9 for Python 3.11+

- compute_endpoint/globus_compute_endpoint/endpoint/taskqueue.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/manager.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/worker.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/zmq_pipes.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/test_bad_endpoint_config.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_gce_container.py
- compute_endpoint/tests/unit/test_reporting_period.py
- compute_endpoint/tests/unit/test_worker.py
- compute_endpoint/tests/unit/test_working_dir.py
- compute_sdk/tests/unit/test_login_manager.py
- docs/autobuild.sh
One of the steps in making sure ipv6 is supported is too remove the usage of the ipv4 loopback address `127.0.0.1`, replacing it with `::1` to confirm that things work with ipv6.  (127.0.0.1 has already been working since beginning of history, so doesn't need to be kept in most circumstances.
We also decided that we should not go the extra mile to ensure that ipv6 is compatible with HTEX, as that's being deprecated.  All the 127.0.0.1 should be only in the htex module.
[sc-37307]
> Replace ipv4 v6 sc 37307

- compute_sdk/globus_compute_sdk/sdk/diagnostic.py
Also slightly reorder tests so ordered by hosts and port.
1. web conn (443)
2. web ssl conn (443)
3. amqp conn (443)
4. amqp ssl conn (443)
5. amqp conn (5761)
6. amqp ssl conn (5761)
> Add port 443 of amqp host to diagnostics

- smoke_tests/tests/conftest.py
- smoke_tests/tests/test_running_functions.py
Applying a uniform linear backoff strategy with a 60-second timeout improves test stability and simplifies debugging.
> Apply linear backoff strategy to Client smoke tests

- smoke_tests/tests/conftest.py
- smoke_tests/tests/test_running_functions.py
- smoke_tests/tests/test_s3_indirect.py
These skips were transitionally necessary, but the underlying imports and expectations are now stabilized.
> Remove no-longer necessary test-skips

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
The main change is the `fut._metadata` dictionary update in `executor.py` in the happy and non-happy paths.  This suggested a change in the fixtures of the tests, which resulted in a larger than expected set of test-changes.  But it's all in service to the 2 `_metadata` hunk changes.
> Add request_id to ComputeFuture._metadata

- docs/sdk.rst
The documentation has a very visible TODO. I've replaced that with a proposed link to a relevant doc section.
Alternate solutions are possible and welcome; this is the smallest possible fix.
Documentation update
> Replace TODO with link

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
No public changelog for this release.  Most distinguished commit is add exponential backoff to smoke tests.
> Bump versions for V2.34.0 release

- compute_endpoint/globus_compute_endpoint/engines/high_throughput/messages.py
This started giving the following mypy error recently.  Not quite sure what changed, but handling str vs. bytes formally is better anyway.  (line a bit long for a one-liner so split it into if/else)
```
globus_compute_endpoint/engines/high_throughput/messages.py:110: error: If x = b'abc' then f"{x}" or "{}".format(x) produces "b'abc'", not "abc". If this is desired behavior, use f"{x!r}" or "{!r}".format(x). Otherwise, decode the bytes  [str-bytes-safe]
```
> fix possible issue regarding bytes/str decoding

- docs/endpoints/configs/ospool.yaml
- docs/endpoints/endpoint_examples.rst
Open Science Pool is an open computing pool maintained by the OSG-Consortium. 
This configuration uses CondorProvider with apptainer.
Please note that the config example has encryption disabled to work around system limitations (no shared-FS).
> Adding a config example entry for Open Science Pool

- compute_endpoint/tests/unit/test_gce_container.py
Add a missing `.shutdown()` in a test engine factory.  The comment was correct that the _executor_ was not started, but either missed that the status reporting thread was started, or the rug was changed underneath it.
Not sure if this will address all of what we're seeing in CI, but this was a repeat offender that I was finally able to recreate locally.  At the very least, it should help reduce the noise if/when other tests fail.
> Shutdown engines in test

- changelog.d/20250109_115759_kevin_update_parsl.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/setup.py
I am unable to recreate the recent CI failures (that are so consistent in CI!) locally.  However, there was a major fix recently to be more clean during Parsl shutdown, so I'm hoping this addresses the flakiness.  Let's see what happens!
- Bug fix (non-breaking change that fixes an issue)  (Bug fix for CI, hopefully!)
- Breaking change (fix or feature that would cause existing functionality to not work as expected) (Channels are no more.)
> Update Parsl to 2025.1.6

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
Pulling out of larger work on closing all resources for the recent broken CI.
> Close internal SelectConnection resources

- release.sh
When I released 2.32.0 earlier this week, the git tag command in release.sh failed(my gpg key, only used for tags, expired a few weeks earlier), but I missed the error message amongst the release output:
```
...
error: gpg failed to sign the data
error: unable to sign the tag
...
```
The script thinks it's a 'tag already exists' error and asks to confirm, which I answered 'y' without becoming suspicious of why the tag would already be pre-existing.  In the end, the packages were released but the tag wasn't pushed.
Instead, the user should be prompted for 'already exists' situations, but the script should abort for other, unknown issues.
> Modify release script to distinguish git tag errors

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
- compute_endpoint/tests/integration/conftest.py
- compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_result_q.py
There's no need to create an external process to run the AMQP test class; in fact, doing so has hidden a couple of subtle pika interaction bugs. Consequently, though the motivating change in this commit is:
- multiprocessing
+ threading/queue.SimpleQueue
there are also some fixes in `test/.../result_queue_subscriber` around the proper shutdown procedure of the `pika.SelectConnection`: don't stop the loop prematurely, and close all resources.
> Convert test class to threading

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
- compute_endpoint/tests/integration/conftest.py
- compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
- compute_endpoint/tests/integration/test_rabbit_mq/task_queue_publisher.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
- remove an unwarranted test `reconnect()` (makes flow much simpler to verify)
- don't forget to remove reference to connection so it can be GC'd
- remove redundant shutdown requests, given fixtures
- fix test to let ioloop know that connection is closing, allows for a cleaner shutdown in the ioloop internals.
> Check before test ioloop close

- compute_endpoint/tests/unit/test_cli_behavior.py
As of Nov, 2024, the MEP configuration is separate from the SEP/UEP.  This test is effectively accounted for within that entire structure and set of tests.
Ref: f12b50b17b4a008a85b63c794d5afcf311ca1741 (via PR #1708)
> Remove obsolete test for MEP config

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
This is the skeleton of adding high-assurance to endpoint configuration.
The option in ``globus-compute-endpoint configure --high-assurance`` is marked as hidden for now.
Like multi-user, the config is only present in the config file if it is True.  The web service treats missing values as False as well.
Obviously no changelog fragment for now.
For a bit more context see [SC https://github.com/globusonline/funcx-services/pull/726](https://app.shortcut.com/globus/story/35308/allow-endpoint-to-be-marked-as-ha)
V3 register adds the high_assurance option if provided, V2 does not support registration with the value set to True.  However GET /v2/endpoint does return the value.
> add high-assurance placeholder option to endpoint configuration

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_result_q.py
Another unnecessary resource consumed.  Tangentially found a missed `SimpleQueue` refactor item from yesterday, and realize during log trawling that we only care about the log if we're stopping unexpectedly.
> Remove unnecessary c&p fixture

- changelog.d/20250113_150119_chris_restrict_serializers.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/unit/test_engines.py
- compute_sdk/globus_compute_sdk/errors/error_types.py
- compute_sdk/globus_compute_sdk/serialize/__init__.py
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/integration/test_serialization.py
- compute_sdk/tests/unit/test_client.py
- docs/sdk.rst
Adds functionality to the `ComputeSerializer` to restrict what strategies can be used to deserialize a payload, and exposes that functionality to engines.
The first 3 commits are mostly cleanup. The meat of the changes is in the second to last commit, and the last commit is just about surfacing this functionality to endpoint configs.
[[sc-35784]](https://app.shortcut.com/globus/story/35784/add-option-to-endpoint-config-to-require-a-specific-serializer-for-functions-args-and-kwargs)
> Restrict serializers

- compute_sdk/tests/unit/test_serialization.py
Every test in this file is concerned with small units of functionality to varying degrees, so this is more appropariate in the unit test dir. Also fixes some typing warnings and uses the new IDENTIFIER_LENGTH constant.
> Clean up serialization tests a little

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
> Fix `allowed_serializers` missing in `GlobusComputeEngine` docstring

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
For short runs of the endpoint, perhaps while developing or with a very short idle timeout, the internal `_connection_tries` may not have been reset.  In those cases, only emit the warning if shutting down was not intentional.  (This was already done for the `ResultPublisher` as part of the recent cleaning up of resources drive.)
> Remove spurious warning

- changelog.d/20241209_081322_30907815+rjmello_globus_sdk_compute_client_sc_36127.rst
- changelog.d/20241209_143843_30907815+rjmello_globus_sdk_compute_client_sc_36127.rst
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/diagnostic.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/setup.py
- compute_sdk/tests/integration/test_executor_int.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_executor.py
- compute_sdk/tests/unit/test_web_client.py
- smoke_tests/tests/test_version.py
- Created the `_ComputeWebClient` class, which integrates `ComputeClientV2` and `ComputeClientV3` from the `globus-sdk` using composition. This work is part of our effort to more closely align with the `globus-sdk`.
- Marked the `WebClient` class and `Client.web_client` attribute as deprecated and replaced their usage with the `_ComputeWebClient` class and `Client._compute_web_client` attribute, respectively.
[sc-36127]
> Replace `WebClient` with `globus-sdk` clients

- changelog.d/20250127_162749_30907815+rjmello.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
This attribute is only used by the `EndpointManager`, which will instead instantiate its own `AuthClient`.
> Deprecate `Client.auth_client` attribute

- changelog.d/20250122_104738_yadudoc1729_update_parsl_version_req.rst
- compute_endpoint/setup.py
There's a version dependency conflict currently between parsl and globus-compute-endpoint, this version bump fixes that.
For a user trying to use Parsl with the new optional extra that allows task submission of Globus Compute, we currently have a version dependency bug: the latest `globus-compute-endpoint==2.24.0` pins parsl to `2025.1.6` while `parsl
>=2025.1.20` is required to use the new functionality.
Reported by @christopherwharrop-noaa
> Bumping Parsl version req from 2025.1.6 to 2025.1.20

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_identity_mapper.py
Following the GCS move to deprecate the singular `.map_identity()` in the Globus Identity Mapping tool, go ahead and do similar here.  This is actually convenient timing as this work is also a precursor to sc-37953 to send endpoint meta information to the web-services, and doing this segment now clears up a couple of future PRs.
[sc-37953]
> Find all matched identities, not just first

- docs/endpoints/configs/polaris.yaml
As @khk-globus discovered recently, the `bond0` interface on Polaris@ALCF is no longer working for worker to login node communication. This PR updates our documented configs for Polaris to use the `hsn0` interface which we tested to confirm that it works for internal communication.
> Update Polaris config to use alternate interface for engine communication

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/conftest.py
- compute_endpoint/tests/integration/endpoint/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/test_rabbit_mq/test_heartbeat_q.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_utils.py
To ensure endpoint heartbeats are always processed in a timely manner, a dedicated multiprocessing queue and RabbitMQ channel, exchange and queue are now used.
[sc-37952]
> Process EP heartbeats separately from results

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
Accept `ep_info` from stdin, if provided, and treat as a static set of data that will not change for the life of the process.  In the case where nothing is provided, generate default values (e.g., `os.getpid()`, etc.).  Use this data structure to augment the EPStatusReport structure that the heartbeat sends.
Add notion of `active`, a boolean, to heartbeat.  This will aid the WS in determining the online status of an endpoint.
Add first test of fields of status report (`global_state`).  Currently, only the fields of the GlobusComputeEngine status report are tested.  I opted to wait to implement tests for the ProcessPool and ThreadPool engines at this time.
[sc-37953]
> Add static information to EP Info in heartbeat

- docs/sdk.rst
This section briefly describes how the `Client` uses `GlobusApp` objects and links to the Globus SDK docs for more info.
> Add section to SDK docs for GlobusApps

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
Main addition is a couple of new fixtures, `mock_gcc` and `mock_get_client`. Using these, replaced a number of boiler-plate setups with a single point of authority.  In the course of this refactor, discovered one oversight bug: the heartbeat AMQP port replacement logic.
> Refactor the Endpoint unit tests

- changelog.d/20250206_125215_kevin_remove_obsolete_funcx_upgrade_code.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
This command helped with the upgrade process for endpoints created prior to v2.0.0 (a.k.a, the rebrand to Globus Compute from funcX).  Beyond the sheer amount of time (21 months), the vast majority of folks use the YAML configuration approach rather than manually creating configurations.
> Remove obsolete upgrade command

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
We recently (ok, "ish") refactored to use threads, rather separate processes, to handle AMQP communication.  In so doing, we no longer needed the plumbing of `multiprocessing`.  Complete the refactor by moving to `queue.Queue` and `threading.Event`.
> Complete overlooked refactor item

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The SEP/UEP recently learned about a static set of information about the EP process to send along with the heartbeat.  It can also get information from its `stdin` via the usual (JSON dictionary) mechanism.  This commit now teaches the MEP to pass along identity information about which identity matched, that will be included in the heartbeat.
While here, fine-tune the auto-population of the `ep_info` datastructure to always add the information.  There is no need to ferry the data around from the pre-exec context when the OS freely manages this data already.
[sc-37953]
> MEP passes identity information to UEP

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/endpoint/taskqueue.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_engines.py
- docs/endpoints/config_reference.rst
Engines entered the mix in Summer, 2023; update configuration to use `.engine` instead of the list of length 1 vestigial thought-process.  Deprecate use of `.executors` at the UserWarning level for visibility.
This should largely be a noop as far as users are concerned, because we've been translating `config.yaml`'s `engine` since day one.
> Deprecate executors (list of len() == 1)

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/test_boot_persistence.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_gce_container.py
- compute_endpoint/tests/unit/test_working_dir.py
Pay attention to the recent change to start the JSP thread during intialization.  It was clearer organization, but means that we now need to ensure that we also shutdown the thread.  This usually means shutting down the engine, often "hidden" as part of the configuration, even though we didn't start the interchange.
> Don't leave GCE threads running

- changelog.d/20250207_160227_30907815+rjmello_fix_default_engine.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/tests/conftest.py
- smoke_tests/tests/sh/test_endpoint.sh
The default engine is now `GlobusComputeEngine` when the engine `type` is not specified. Previously, the default was `HighThroughputEngine`, which was removed in version `3.0.0`.
> Fix default engine type

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
Clarified a few docstrings for `GlobusComputeEngine` methods related to the endpoint status report.
> Update engine status method docstrings

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
This indicates the total number of tasks that the `GlobusComputeEngine` has submitted to its underlying `HighThroughputExecutor`.
> Add total tasks count to GCEngine status report

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
We now include the python version in the endpoint registration metadata along with the endpoint version and SDK version.
> Include python version in endpoint registration

- changelog.d/20250213_000051_kevin_delay_start_jsp_thread.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
- docs/changelog.rst
The recent refactor to move the JobStatusPoller thread initialization to the `GlobusComputeEngine.__init__` method missed that endpoints are often daemonized.  Daemonization only allows the fork()ing thread to survive.
Fix: Move the JSP thread creation back to the GCE's `.start()` method, since this method is invoked *after* the daemonization.  This time, cement the expectation with a test.
Reference:
- #1779 (as part of [sc-37953])
- 393b41002f417a05be878ece2e010fef11259ae2
> Bugfix: start JobStatusPoller at engine start

- compute_endpoint/packaging/JenkinsFile
Last few builds have failed due to some issues, this update (should) improve it. 
After it's merged, I'll also update the default branch in Jenkins to main.
> Update jenkins script for building packages

- changelog.d/20250205_151005_30907815+rjmello_deprecate_login_manager.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/authorizer_login_manager.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/manager.py
- compute_sdk/tests/unit/test_authorizer_login_manager.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_login_manager.py
- docs/sdk.rst
- Deprecated the `LoginManager` and `AuthorizerLoginManager` classes.
- Deprecated the `Client.login_manager` attribute.
- Added an `authorizer` parameter to the `Client` initializer to enable using a `GlobusAuthorizer` for authentication.
- The SDK docs on using an existing access token now instruct users to pass in a `globus_sdk.AccessTokenAuthorizer` to the `Client` initializer instead of using the deprecated `AuthorizerLoginManager`.
[sc-38908]
> Deprecate LoginManager and AuthorizerLoginManager

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
[[sc-35311]](https://app.shortcut.com/globus/story/35311/ha-endpoints-should-enforce-zmq-encryption)
> Enforce encryption in high assurance endpoints

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/diagnostic.py
- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/tests/unit/test_diagnostic.py
- compute_sdk/tests/unit/test_executor.py
- compute_sdk/tests/unit/test_version_parse.py
- docs/changelog.rst
- docs/endpoints/configs/polaris.yaml
- docs/endpoints/multi_user.rst
- docs/sdk.rst
- docs/tutorial.rst
The typos were caught when reading the documentation [[link to typo that caught my eye](https://globus-compute.readthedocs.io/en/latest/tutorial.html#:~:text=standard%20python%20serilaization%20libraries)], and subsequently by running codespell and typos against the docs and code directories.
Note that a line in `test_diagnostic.py` had to be reflowed because flake8 complained about the line length after adding a 't' to "writen".
> Fix some typos

- changelog.d/20250218_125140_30907815+rjmello_bump_parsl.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
We utilize the Parsl HTEX `connected_managers_packages()` method to retrieve the installed versions of `globus-compute-endpoint` and `globus-compute-sdk` running on each connected worker manager, then add them to the status report.
[sc-39409](https://app.shortcut.com/globus/story/39409/add-worker-endpoint-version-to-ep-status-and-console-api)
> Add manager EP and SDK versions to status report 

- docs/endpoints/configs/perlmutter.yaml
Includes the gpus-per-node flag in the scheduler options comment. This flag is needed for the workers to be able to access the gpus on the node.
> Minor Perlmutter example update.

- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
Create serialization strategy cache automatically on class init. Also derive selectable strategy list from properties on the class, rather than creating it ad-hoc later.
> Serialization strategy list/map cleanup

- .github/workflows/ci.yaml
- changelog.d/20250205_154700_chris_re_python_313.rst
- compute_endpoint/tox.ini
- compute_sdk/tox.ini
Was finally able to test on ARM hardware after Kevin's thread rework in #1779, and everything looks good in Py3.13 land. This just adds 3.13 back to test matrices.
[[sc-37235]](https://app.shortcut.com/globus/story/37235/add-support-for-recent-python-versions-to-compute-sdk-endpoint)
> (Re-)Add support for Python 3.13

- changelog.d/20250304_000638_30907815+rjmello_template_dir_sc_39429.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/conftest.py
- compute_endpoint/tests/unit/test_config_utils.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- docs/endpoints/config_reference.rst
- docs/endpoints/multi_user.rst
Enabled multi-user administrators to specify custom user configuration template and schema paths with the `user_config_template_path` and `user_config_schema_path` config options.
[sc-39429](https://app.shortcut.com/globus/story/39429/add-ep-config-variable-to-specify-template-dir)
> Enable custom user config template and schema paths

- changelog.d/20250310_105447_kevin_address_shutdown_race_condition.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
There was a moment in time right at shutdown where a task would be received by the receiving thread.  The thread dutifully sent it on to be processed, naive to the fact that the whole process would shutdown.  Combined with the ACK, this made for lost tasks.
New approach: lock the heartbeat kernel, so that when to quiesce is deterministic.  Attempt to take the same lock in the thread; if the quiesce flag is set, then do *not* ACK the result.  The AMQP service will resend the task when the EP next connects.
[sc-36175]
> Address EP interchange shutdown race condition

- changelog.d/20250305_205605_kevin_v3_function_registration.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/setup.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_executor.py
- docs/changelog.rst
For most users, this will be a silent difference.  However, for users who manually serialize and specify the function parts, they will now need to specify the function metadata, and, in particular the serialization method.
[sc-36296]
> Use v3 register_function API route

- changelog.d/20250320_135249_chris_executor_serializer.rst
- compute_sdk/globus_compute_sdk/errors/error_types.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
- docs/sdk.rst
Preliminary work related to result serialization. The list of result serializers will live on the Executor, so to keep things consistent, this change makes all client-side serialization knobs (of which there is currently one) accessible through the Executor.
> Add a passthrough interface to the Client's serializer through the Executor

- changelog.d/20250325_120334_LeiGlobus_refresh_token_request_sc_40211.rst
- compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
- compute_sdk/tests/unit/auth/test_globus_app.py
- docs/changelog.rst
[sc-40211]
Compute asks for login flow before refresh_token expiry
See [support ticket](https://globusonline.zendesk.com/agent/tickets/389213) and [Slack discussion](https://globus.slack.com/archives/C0896RYMBGX/p1742853460624439)
Refresh tokens were removed going from 2.27.1 -> 2.28.0 from .globus_compute/storage.db
The related change:  [Using GlobusApp for authentication: ](https://globus-compute.readthedocs.io/en/latest/changelog.html#globus-compute-sdk-globus-compute-endpoint-v2-28-0)
This appears to be caused by a missing request_refresh_tokens=True param in GlobusAppConfig.
Also fixes a formatting issue with the changelog for the earlier version bump for 3.4.0a0
> Request refresh tokens when initializing GlobusApp

- compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Avoid a minor race-condition where the open operation is only half-complete before the close operation begins:
AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ConnectionOpenAborted: ("Connection.close() called before connection finished opening: prev_state=TUNE (200): 'Normal shutdown'",)
> Ensure test prerequisite

- changelog.d/20250325_160052_chris_pure_source_combined.rst
- compute_sdk/globus_compute_sdk/serialize/concretes.py
Adds two new sub-strategies to `CombinedCode` (which requires moving them around a little). Also fixes the documentation comments for both `PureSource` strategies.
> Add `PureSource*` strategies to `CombinedCode`

- changelog.d/20250325_154559_chris_strategylike.rst
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/unit/test_serialization.py
More preliminary work for selectable result serialization. We're going to be passing around serializer import paths for that work, so it's important to have a central validation engine that supports all three modes of referring to a strategy (namely by instance, type, and import path).
> Add Strategylike type and utility function

- docs/endpoints/endpoints.rst
These values are indeed wildcards - what they aren't is *globs*.
> Fix semantics of wildcard documentation

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/integration/endpoint/executors/test_engines.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/utils.py
The engines all return Futures for each task submitted to them.  When each Future completes, it can initiate the appropriate event to forward the associated result to the AMQP service.  In so doing, remove the `results_passthrough` queue&nbsp;&mdash;&nbsp;now completely unnecessary&nbsp;&mdash;&nbsp;and similarly remove the `result_processor_thread` in the Endpoint's interchange.
This refactor also more nicely isolates the retry logic and retry data structure to strictly the base Engine class&nbsp;&mdash;&nbsp;the other engines can now partake in the retry goodness as well.
[sc-35488]
> Refactor engine infra to use futures

- compute_endpoint/globus_compute_endpoint/cli.py
Removing the 'hidden' flag from high-assurance.
[sc-40477]
Silently make it (more) visible, to be announced at Globus World first, so no changelog or redirection to documentation.
> unhide HA option when configuring

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/__init__.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_shell_functions.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/integration/endpoint/executors/test_engines.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_working_dir.py
The `Future` object returned by the engine is now a `GCFuture`.  It's purpose is to inform watchers when the associated task is complete.  But rather than make the engine responsible for creating this object, pass one in already instantiated.  The idea is that the task-result concept has a larger lifetime than just what the engine sees, so it doesn't quite align to have the engine be the generator.  The engine certainly is a part of the task lifecycle, but what creates the task is the interchange when it receives the task from upstream.
Beyond philosophy, this means that the interchange can use the same object in multiple branches, rather than creating different instances to satisfy the interface.  In upcoming changes, there will be attributes beyond just `gc_task_id` that will better …
> Pass future to engine instead

- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
This makes no difference in the happy-path, but no sense in waiting to fail while debugging the errant-case.
> Disable Globus SDK retries in tests

- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
While in a hurry to review the previous one, missed that the decorator isn't needed any longer now that you moved its use to two context managed calls
> context manager not needed for RequestsMock

- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/globus_compute_endpoint/engines/globus_mpi.py
- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
- compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/unit/engine/conftest.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
- compute_endpoint/tests/unit/engine/test_globusmpi.py
- compute_endpoint/tests/unit/engine/test_processpool.py
- compute_endpoint/tests/unit/engine/test_threadpool.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_gcfuture.py
Parsl adds a `parsl_executor_task_id` attribute to the Futures it returns; translate this to a generic name, and teach all executors to have an `executor_task_id` before setting that on the `GCFuture` returned to the interchange.
[sc-35488]
- New feature (well, progress _toward_ the user-facing feature; still internal days)
> Teach GCFuture executor_task_id

- changelog.d/20250404_172727_30907815+rjmello_ha_endpoint_id.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
Enabled support for registering a function to a specific HA endpoint via the `ha_endpoint_id` argument in the `register_function` methods of the `Client` and `Executor` classes.
Since HA functions cannot be shared, this argument is mutually exclusive with the `group` and `public` arguments.
[sc-35310](https://app.shortcut.com/globus/story/35310/allow-a-function-to-be-marked-as-restricted-to-a-specific-ha-endpoint)
> Enable HA function registration

- docs/endpoints/installation.rst
The apt-key file `/usr/share/globus-repo/RPM-GPG-KEY-Globus` is apparently deprecated for DEB and RPM and the file is no longer included, so removing the lines from readthedocs installation instructions for packages.
Based on [GCS docs here](https://docs.globus.org/globus-connect-server/v5/#gcsv5-install)
See https://globus.slack.com/archives/C0896RYMBGX/p1744228361088989
> remove reference to Globus RPM-GPG-KEY from DEB and RPM instructions

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_shell_functions.py
- compute_endpoint/tests/integration/endpoint/executors/test_engines.py
- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
- compute_endpoint/tests/unit/engine/test_base.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
- compute_endpoint/tests/unit/engine/test_globusmpi.py
- compute_endpoint/tests/unit/engine/test_processpool.py
- compute_endpoint/tests/unit/engine/test_threadpool.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_gcfuture.py
- compute_endpoint/tests/unit/test_working_dir.py
Tell Parsl to send monitoring events (when nodes have new state/tasks), and then watch the incoming monitoring information to update each task with block and job identifiers.
Because jobs can be rescheduled or retried internally, also implement an observer pattern to account for updates to the GCFuture information.
[sc-35488]
- New feature (still internal days yet)
> Add Parsl monitoring queue

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
The implementation is fairly self-explanatory: call a method at opportune points in a task lifetime on the endpoint.  Points of note:
- Enforce that audit logging is only available for HA endpoints by removing the `audit()`ing method implementation`
- Events logged are `RECEIVED`, `EXEC_START`, `RUNNING`, and `EXEC_END` to denote when the task is received by the interchange, when it's received by the executor, when it's known to be running (i.e., if assigned to a `block_id`), and when the execution is complete.
- Auditing records are written to an externally provided file descriptor. Pragmatically, this means that auditing will only be available to UEPs on HA MEPs.
[sc-35488]
- New feature (not user-functional yet; next PR)
> Implement UEP audit method

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_mep_audit_log.py
Don't overthink it&nbsp;&mdash;&nbsp;if the audit method has a problem, there is a problem. Don't fix it, ignore it, or attempt to be graceful.  Explode the log with the traceback (we already do), and *shut down the MEP.*
To the reviewer: consider ignoring whitespace to see the salient change.  (`try: ... finally:`)
[sc-35488]
- Bug fix (a not-yet-release bug, but still)
> Ensure failed audit setup shuts down MEP

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
See thread https://globus.slack.com/archives/C0896RYMBGX/p1744755803507389
We want to create an HA policy based on the endpoint configure value, not whether there's a timeout.
> change HA policy creation to be based on configure HA flag, not timeout

- compute_endpoint/globus_compute_endpoint/cli.py
We have already changed a policy's HA-ness to be based on the user's endpoint configure flag instead of timeout in https://github.com/globus/globus-compute/pull/1860 but missed changing the help message.  
This just removes that part of the help text for --timeout
> remove language that associates timeouts with high-assurance

- changelog.d/20250423_130657_nicholas.s.tyler.4_add_podman_hpc.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_gce_container.py
- docs/endpoints/endpoints.rst
This both adds `podman-hpc` as a container runtime for running containers at HPC centers like NERSC. It also reduces some code duplication for running similar container runtimes.
> Adds podman-hpc for running at NERSC

- changelog.d/20250428_144312_30907815+rjmello_escape_user_runtime.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_config_utils.py
Apply JSON escaping to the values of the ``user_runtime`` Jinja variable passed to the user endpoint configuration template. This matches our handling of user-provided template variables and helps endpoint administrators prevent YAML injection attacks.
> JSON-escape user_runtime in UEP config template

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
To date, the thread has quit immediately before completing the first iteration. This is a mistake as the thread should stay around for the life of the endpoint to verify that the parent always exists.  Whoops!
The automated test missed this because while it verified the loop conditional, it did not verify the internal conditional.  Correct by ensuring loop iterates at least a few times.  (Overkill to 100, "just because.")
> Invert mistaken boolean conditional

- docs/endpoints/multi_user.rst
The web service now includes the user's runtime information in the UEP identifier hash since it is passed into the UEP configuration template.
> Mention user runtime in UEP identifer hash docs

- compute_sdk/globus_compute_sdk/sdk/utils/gare.py
- compute_sdk/tests/unit/test_util.py
Generic function that handles retrying functions when GAREs are encountered. To be used in [[sc-33476]](https://app.shortcut.com/globus/story/33476/create-auth-policy-commands-do-not-prompt-for-re-authentication-as-needed) and [[sc-39660]](https://app.shortcut.com/globus/story/39660/expire-or-disable-result-rabbitmq-queues-along-with-defined-auth-policy-timeout).
> Add a function for handling GAREs

- changelog.d/20250505_113845_chris_gare_handle_create_auth_policy.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
[[sc-33476]](https://app.shortcut.com/globus/story/33476/create-auth-policy-commands-do-not-prompt-for-re-authentication-as-needed)
> Handle GAREs in create auth policy code

- compute_endpoint/setup.py
Click minor version 8.2.0[^1], which released two days before this commit, involves some major breaking changes, including dropping support for some old Python versions, of which we still support 3.9. It also removes an argument that we use in a test runner (`CliRunner`'s `mix_stderr` constructor arg).
In the future, we should update to a more recent version, but for now this just makes the upper bound on the click dependency stricter.
[^1]: https://click.palletsprojects.com/en/stable/changes/#version-8-2-0
> Add a stricter upper bound for click version

- changelog.d/20250513_102548_30907815+rjmello_k8s_pers_vol_type.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/tests/unit/test_endpoint_config.py
The `persistent_volumes` argument to Parsl's `KubernetesProvider` expects a list of tuples, so we perform a conversion when loading the endpoint YAML configuration.
> Convert persistent_volumes to a list of tuples

- changelog.d/20250516_095252_30907815+rjmello_remove_get_containers.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/tests/unit/test_client.py
The Globus Compute web service does not support the corresponding API route: `/v2/get_containers`.
[sc-32334]
> Remove legacy get_containers method

- changelog.d/20250515_080955_kevin_executor_handles_ha_tasks.rst
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
The web-service does not send High Assurance results via AMQP.  Instead, it notes merely that task is complete.  This commit teaches the Compute SDK Executor to recognize those HA result responses (which present as failed tasks but with the AMQP header `high_assurance` set), and to reach out to the web-service to collect them.
[sc-39660]
> Load HA results from web service

- RELEASING.md
There was a typo in the release script, and GCS has changed the text of a checkbox.  This fixes the typo and reformats the sentence a bit.
> Update release readme for package building to fix typo and update text

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_config_utils.py
The former message added an additional ".yaml.j2" to the filename.
> Fix missing uep config log message

- changelog.d/20250531_143312_kevin_ha_audit_log_by_default.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- docs/changelog.rst
- docs/endpoints/multi_user.rst
Under the expectation that if a setup requires High Assurance, it will also require audit logs, setup a default path directly.  This is a convenience, but one to help education of the feature, and easily disabled if not desired.
[sc-41662]
> Configure audit log by default if HA

- changelog.d/20250602_121437_30907815+rjmello_multiple_login_flows_sc_42021.rst
- compute_endpoint/globus_compute_endpoint/auth.py
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_auth.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
- compute_sdk/tests/unit/auth/test_globus_app.py
We now request all required scopes when authenticating with the Globus Compute and Auth APIs via the CLI. This avoids prompting the user to run multiple login flows when starting a multi-user endpoint.
[sc-42021](https://app.shortcut.com/globus/story/42021/avoid-unnecessary-re-auths-when-starting-an-mep)
> Avoid redundant login flows in CLI

- changelog.d/20250612_090019_30907815+rjmello_mapped_id_jinja_var.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
- compute_endpoint/tests/unit/test_config_utils.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- docs/endpoints/multi_user.rst
Endpoint administrators now have access to identity mapping information in the user configuration template via the `mapped_identity` variable. The following fields are available:
- `mapped_identity.local.uname`: Local user's username
- `mapped_identity.local.uid`: Local user's ID
- `mapped_identity.local.gid`: Local user's primary group ID
- `mapped_identity.local.groups`: List of group IDs the local user is a member of
- `mapped_identity.local.gecos`: Local user's GECOS field
- `mapped_identity.local.shell`: Local user's login shell
- `mapped_identity.local.dir`: Local user's home directory
- `mapped_identity.globus.id`: Matched Globus identity ID
[sc-42194](https://app.shortcut.com/globus/story/42194/include-identity-mapping-info-in-uep-template)
- New feature (non-breaking change that …
> Pass mapped identity info to user config template

- docs/endpoints/endpoints.rst
- docs/index.rst
- docs/tutorials/dynamic_containers.rst
- docs/tutorials/index.rst
- docs/tutorials/using_the_sdk.rst
- Created tutorials index in docs to organize current and future tutorials.
- Renamed "Globus Compute Tutorial" to "Using the SDK," which more accurately reflects the content.
- Created a tutorial that demonstrates how to leverage a multi-user endpoint to enable dynamic container configuration at the point of task submission.
[sc-34263]
> Create tutorial for dynamic container config 

- changelog.d/20250702_101404_30907815+rjmello_stop_endpoint_v3.rst
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
Currently, only the V3 route supports dropping RMQ credentials for multi-user endpoints.
[sc-42844](https://app.shortcut.com/globus/story/42844/support-remotely-stopping-meps-with-sdk)
> Use V3 route in Client.stop_endpoint

- changelog.d/20250710_132341_yadudoc1729_add_get_endpoint_options.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/setup.py
- compute_sdk/tests/unit/conftest.py
- compute_sdk/tests/unit/test_client.py
This PR adds a new `role` kwarg to `client.get_endpoints()` method. Currently, this method returns endpoints that the user owns. Setting `role="any"` fetches MEPs in addition to the endpoints that are owned by the user.
* Updated `globus-sdk` version to required `3.59.0` that shipped support for the `role` kwarg in the v2 client. 
* `role` accepts `owner` (default behavior) and `any`
Refer: https://github.com/globus/globus-sdk-python/pull/1238
> Add get endpoint options

- docs/endpoints/endpoints.rst
Added an admonition to the container docs section to inform users that container images must include the `globus-compute-endpoint` package.
> Add alert for container EP package requirement

- compute_sdk/globus_compute_sdk/sdk/shell_function.py
- compute_sdk/tests/unit/test_shell_functions.py
Per a user request, update the `ShellResult` and `ShellFunction` classes to more clearly delineate the important bits.  In particular, ensure that command is easily identified and copy-paste ready.
[sc-43548]
> Separate ShellResult command for copy/paste

- .gitignore
We have this in our other repos, just not this one. Came up now that VS Code is refactoring its python env support to a plugin rather than an internal feature.
> Add .vscode folder to gitignore

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
To-date, we've conflated the `multi_user` flag to mean "template capable" and supports multiple users.  In the meantime, the EP would make the actual decision based on whether it had privileges and identity mapping set up.
The web-service now uses the existence of the template as an indicator that the EP expects start UEP commands, and we can set the `multi_user=True` only if we have privileges at registration time.
[sc-43660]
> Multi-user API flag iff process is privileged

- changelog.d/20250723_183301_lei_diagnostic_custom_dir_sc_41807.rst
- compute_sdk/globus_compute_sdk/sdk/diagnostic.py
- compute_sdk/tests/unit/conftest.py
- compute_sdk/tests/unit/test_diagnostic.py
Add a custom ``--config-dir`` param to ``globus-compute-diagnostic`` so logs can be gathered from a different globus_compute root instead.
Currently will raise ValueError if specified path is invalid instead of defaulting to the base path, expecting it is a user typo.
(Apparently paths may behave differently on ubuntu vs. macOS, TBD fix test)
> Specify custom directory in globus-compute-diagnostic

- changelog.d/20250813_113742_kevin_gce_pid_file.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
Move some of the logic out of the `Endpoint.start_endpoint` method.  This is not a complete solution&nbsp;&mdash;&nbsp;should move most of the PID logic *out* of the Endpoint class.  But not a task for today.
Motivated to "just do this" given @rjmello's recent documentation work.
[sc-43651]
> MEPs get PID files too

- docs/endpoints/config_reference.rst
- docs/endpoints/configs/anvil.yaml
- docs/endpoints/configs/bebop.yaml
- docs/endpoints/configs/delta.yaml
- docs/endpoints/configs/expanse.yaml
- docs/endpoints/configs/expanse_mpi.yaml
- docs/endpoints/configs/faster.yaml
- docs/endpoints/configs/frontera.yaml
- docs/endpoints/configs/ospool.yaml
- docs/endpoints/configs/perlmutter.yaml
- docs/endpoints/configs/polaris.yaml
- docs/endpoints/configs/stampede3.yaml
- docs/endpoints/configs/uchicago_ai_cluster.yaml
- docs/endpoints/endpoint_examples.rst
- docs/endpoints/endpoints.rst
- docs/endpoints/index.rst
- docs/endpoints/installation.rst
- docs/endpoints/multi_user.rst
- docs/endpoints/security_posture.rst
- docs/endpoints/templates.rst
- docs/tutorials/dynamic_containers.rst
Version 4 adopts a unified architecture where every Compute Endpoint consists of a manager endpoint process that uses configuration templates to launch and manage user endpoint processes. The former multi-user architecture is now the default, requiring an updated conceptual framework:
- Single-user endpoint: Started as a non-privileged user, thus does not support identity mapping
- Multi-user endpoint: Started as a privileged user (e.g., root), thus supports identity mapping
This refactoring incorporates most features that were formerly multi-user-specific into the main endpoint user guide, with the multi-user guide now focusing primarily on identity mapping features.
[sc-42857](https://app.shortcut.com/globus/story/42857/update-docs-to-redefine-uep-mep)
> Refactor endpoint docs for v4 architecture changes

- changelog.d/20250909_155630_30907815+rjmello_handle_null_user_values_sc_44820.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_config_utils.py
Our template rendering logic now handles null values in both the `user_endpoint_config` or `user_runtime` objects.
[sc-44820](https://app.shortcut.com/globus/story/44820/fix-handling-of-null-user-values-when-rendering-config-template)
> Handle null user values when rendering template

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_config_utils.py
- compute_endpoint/tests/unit/test_endpoint_config.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Previously, any user running a templatable EP as root was required to supply an identity mapping file, since there was no concept of a single- user templatable EP. Now that this concept exists, this commit removes the logic enforcing an ID mapping configuration file.
[[sc-44019]](https://app.shortcut.com/globus/story/44019/allow-privileged-users-to-run-unmapped-templatable-endpoints)
> Allow root users to run unmapped templatable EPs

- .github/workflows/ci.yaml
A new vulnerability/issue in ``pip`` Noted [here](https://github.com/pypa/pip/issues/13522#issuecomment-3353955654) with issue tracked [here](https://github.com/pypa/pip/issues/13607) is breaking all builds that use pip-audit.
This PR adds an ignore while we figure out a medium term solution - upgrade python versions/packages if necessary, wait for a decision/change w.r.t. pip 25.2, or wait for 25.3.
globus-python (GCS/Transfer) is 3.9.18, and the tutorial EP Dockerfile pins 3.11.8, which are the only related specific pins I can find.  They are both above the list of secure, can-ignore PY versions as stated in the issue, ``Python >=3.9.17, >=3.10.12, >=3.11.4, or >=3.12``
> Add ignore to pip-audit to fix build for now

- changelog.d/20250923_152715_chris_migrate_template_capable_sc_42253.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
Adds a command users can run to migrate existing, non-template-capable endpoints to become template capable. Warns users if they run a non-template-capable endpoint and informs them of the new command.
[[sc-42253]](https://app.shortcut.com/globus/story/42253/create-default-management-config-file-for-existing-single-user-endpoints)
> Add migrate-to-template-capable command

- changelog.d/20251006_162634_kevin_clear_environ_immediately_after_fork.rst
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_mep_audit_log.py
- compute_endpoint/tests/unit/test_utils.py
- docs/endpoints/multi_user.rst
Even though the final `exec()` call specifies a new environment, there's no need to keep the preexec environ the same as the parent environ.  While not a security bug, keeping the environ for longer than necessary can lead to confusing log messages and has caused concern with at least one user.
Remedy the concern by clearing the environment immediately.  Similarly, also close file descriptors immediately after fork().
Finally, implement an eager `gc.collect()` in an attempt to avoid a later-on traceback log in the pre-exec phase.  The traceback is only scary when user's go looking in the logs (so, "not professional"), but is inconsequential as the memory-space is wiped by the `exec()` call.  (And move some logic into an ad-hoc function for a similar reason: collectability.)
[sc-43531]
- …
> Clear environment variables
