globus/globus-compute

- funcx/endpoint/endpoint.py
There were a lot of unused functions left in the endpoint. Everything still works fine.
> cleaning up endpoint code

- examples/introduction.ipynb
- funcx/endpoint/endpoint.py
- funcx/sdk/client.py
Also update example notebook.
This is a minor change to use the uuid returned from the function publication.
> Change to use uuids in the client and endpoint.

- funcx/endpoint/endpoint.py
- funcx/sdk/client.py
- funcx/sdk/config.py
Updated the endpoint to use the sdk's configobj to set and restore a consistent uuid. Also addressed #16 with a little function to use lookup_option on the endpoint uuid.
> Add config #15

- funcx/endpoint/config.py
- funcx/endpoint/endpoint.py
- funcx/sdk/client.py
- requirements.txt
- setup.py
Switching the endpoint to a class. This doesn't yet address all of DLHub's requirements, but it is getting there.
> Dlhub enhancements #4

- funcx/endpoint/config.py
- funcx/endpoint/endpoint.py
- funcx/sdk/client.py
- funcx/sdk/config.py
- funcx/sdk/utils/futures.py
All execution requests to the service now return a task id. I borrowed Logan's futures code to deal with sync requests in the sdk.
> Async requests #24

- funcx/executors/high_throughput/default_config.py
- funcx/executors/high_throughput/funcx_manager.py
Should be an easy one.  Multi-container otherwise works just fine.
> Cores on worker fix

- funcx/endpoint/endpoint.py
- funcx/executors/high_throughput/interchange.py
> Adding support for specifying endpoint address

- docs/endpoints.rst
- funcx/endpoint/endpoint.py
- funcx/tests/test_interchange.py
Adding configure option to replace the overloaded start method.
Fixes #48
> Configure option #48

- funcx/sdk/client.py
- requirements.txt
This allows you to modify the funcx web service address used by the client to help debugging. It also addresses #70 by switching to fair research login.
> Client updates

- funcx/executors/high_throughput/interchange.py
> remove manager from interesting manager after losing heartbeat

- funcx/endpoint/endpoint.py
- funcx/executors/high_throughput/executor.py
- funcx/executors/high_throughput/interchange.py
- funcx/executors/high_throughput/zmq_pipes.py
- funcx/sdk/client.py
Add heartbeat checks to the endpoints so they start new forwarders when disconnected.
> Reconnect endpoints #83

- funcx/errors.py
- funcx/sdk/client.py
Also: fix missing import. Fixes #106.
> Make repr method return string

- examples/Tutorial-River-Endpoint.ipynb
- funcx/executors/high_throughput/interchange.py
- funcx/sdk/client.py
- funcx/tests/test_batch_submit.py
- requirements.txt
Adds support for:
* Submitting batches of tasks with `funcx_client.map_run(...)`
* Requesting status of batches of tasks with `funcx_client.get_batch_status(<task_id_list>)`
Fixes bad serialization of exceptions reported by the interchange.
> Request batching and bugfixes

- funcx/sdk/client.py
Adds functions to the SDK to allow users to include a function in an endpoints whitelist, list the endpoints whitelist, and remove from the whitelist.
> Whitelist support

- funcx/executors/high_throughput/funcx_manager.py
- funcx/executors/high_throughput/worker_map.py
change the `spin_up` function to return a list of processes, so that the manager can properly kill all the processes when exiting.
Now the worker counts are only updated inside worker map --- `add_worker`, `register_worker`, `remove_worker`
rename `worker_count` to `worker_id_count`
> fix bugs in manager and worker map and reorganize worker count update

- funcx/executors/high_throughput/interchange.py
Reverts funcx-faas/funcX#135
Fixed the mess accidentally did before.
> Revert "Update endpoint reporting #129"

- funcx/sdk/client.py
- setup.py
Adds the function to the SDK to query for endpoint status.
> Add ep stats function

- funcx/executors/high_throughput/container_sched.py
- funcx/executors/high_throughput/funcx_manager.py
- funcx/executors/high_throughput/worker_map.py
Currently, the manager cannot spawn enough workers to process tasks or spawn too many workers in some situations. This PR fixes the bug.
> fix spawning up and down many workers

- funcx/sdk/client.py
- funcx/sdk/utils/batch.py
- funcx/tests/test_per_func_batch.py
This PR adds a new batching interface for users to use. It also changes the `run` to use `batch_run` interface
> new batch interface

- funcx/sdk/client.py
- funcx/sdk/search.py
Created a module to handle searching for functions on client side.  Ingest takes place from server, but client handles queries.  Mostly this is just a wrapper for globus search sdk, with some reformatting of json to be easier to use for this purpose.  Doesn't expose advanced query API.  
Includes helper class for viewing ascii tables of search results.
> Function searching

- funcx/endpoint/endpoint.py
- funcx/executors/high_throughput/executor.py
- funcx/executors/high_throughput/funcx_manager.py
- funcx/executors/high_throughput/interchange.py
- funcx/executors/high_throughput/messages.py
- funcx/executors/high_throughput/zmq_pipes.py
Working on the new mechanism described in https://github.com/funcx-faas/funcX/issues/174.  Starting by having nicer messaging interface I pulled from my branch on Task Parameter passing.  I think this is probably the better feature to first use it for, and the work on that might be changed in light of our discussion on this. 
See the comments on https://github.com/funcx-faas/funcX/issues/174 for a full discussion of the features / code changes.
> New heartbeat mechanism

- docs/endpoints.rst
- examples/Tutorial.ipynb
Working on updating docs for the endpoint CLI and adding examples to tutorial notebook.  See https://github.com/funcx-faas/funcX/issues/184
> Updating docs

- funcx/endpoint/endpoint.py
- funcx/executors/high_throughput/default_config.py
- funcx/sdk/client.py
- funcx/sdk/search.py
Allow for EP searching similar to Globus' EP search, responding to https://github.com/funcx-faas/funcX/issues/185.
> Copying Globus EP Search API 

- README.rst
- docs/endpoints.rst
- examples/Tutorial.ipynb
- funcx/endpoint/endpoint.py
- funcx/executors/high_throughput/default_config.py
- funcx/executors/high_throughput/executor.py
- funcx/executors/high_throughput/funcx_manager.py
- funcx/executors/high_throughput/interchange.py
- funcx/executors/high_throughput/interchange_task_dispatch.py
- funcx/executors/high_throughput/messages.py
- funcx/executors/high_throughput/zmq_pipes.py
- funcx/sdk/client.py
- funcx/sdk/search.py
- funcx/sdk/utils/throttling.py
- funcx/version.py
- requirements.txt
Brings in all of the 0.0.2 changes and refactors. Primary changes include:
- Changes how endpoints communicate with forwarders (breaking)
- Adds endpoint heartbeats and status reports
- Adds task tracking to report detailed task statuses
- Uses the api.funcx.org subdomains, rather than funcx.org/api
- Includes function and endpoint searching
- Adds version checks to the endpoint when registering
- Increases the max request size from 2MB to 5MB
- Updates tutorial notebook to include additional capabilities
- Updates docs
> Merge 0.0.2 changes

- funcx/endpoint/endpoint.py
- funcx/sdk/client.py
Bring Kyle's changes over to master so they are deployed in our Binder examples.
> Update binder on master

- funcx_sdk/funcx/sdk/client.py
Fix the wrong import path from PR #264
> Fix import from funcx to funcx_endpoint

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_sdk/funcx/sdk/client.py
Discovered this issue while trying to get SlurmProvider running on Midway. Was throwing exception while trying to raise the scalingerror exception. This fixed it.
> Fixed scalingerror args in interchange.py [one line] 

- funcx_sdk/funcx/sdk/client.py
> Issue #261 added detailed status updates from web service

- funcx_endpoint/funcx_endpoint/__init__.py
- funcx_sdk/funcx/__init__.py
> Revert "Remove top-level `__init__.py` files for PEP-420 compliance."

- examples/Tutorial.ipynb
- funcx_endpoint/funcx_endpoint/tests/test_batch_submit.py
- funcx_sdk/funcx/sdk/client.py
changed the get_batch_status() function name to get_batch_result() and also changed all its instances
> get_batch_result() Updated

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
Will have further discussion with Kyle.
> Issue 330: Exception handling in case of serivce down

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
As we discussed, removed the `register_with_hub` function, preparing for further restructure.
> Cleaning up: removing register_with_hub function

- funcx_sdk/funcx/tests/test_batch.py
Fix how the task completion is checked in test_batch.py
> [forwarder_rearch_1 branch] Fix the task completion condition in test_batch.py

- funcx_endpoint/funcx_endpoint/strategies/simple.py
This PR fixes the mismatch between funcx strategy and parsl 1.0 status interface.
Note: this PR is merging to `forwarder_rearch_1` branch, rather than `main`
fixes #364
> Fix simple strategy for parsl 1.0 in forwarder_rearch_1 branch

- funcx_sdk/funcx/tests/README.rst
Updating testing notes for release testing
> Updating readme for release testing

- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/tests/test_errors/test_invalid_endpoint.py
- funcx_sdk/funcx/tests/test_errors/test_invalid_function.py
This is a refactor draft that goes along with https://github.com/funcx-faas/funcx-web-service/pull/211 for the sdk
> Task submit/status error handling refactor

- funcx_sdk/funcx/serialize/facade.py
Missing variable reference. Minor bug.
> Fixing unbound variable error

- docs/quickstart.rst
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/zmq_pipes.py
A bunch of log line changes.
* Adding pyzmq and libzmq info to current platform info block which is logged
* Removed several debug lines
* Updated log strings for clarity
> Log line cleanup

- funcx_sdk/funcx/sdk/client.py
Modifies the routes used by the SDK to register endpoints and functions. These changes are necessary for https://github.com/funcx-faas/funcx-web-service/pull/213
> Update routes for endpoint and function registration

- helm/README.md
- helm/funcx_endpoint/Chart.yaml
- helm/funcx_endpoint/templates/endpoint-deployment.yaml
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
- helm/funcx_endpoint/values.yaml
This updates the helm chart to use the latest Executor config and updates the minimum funcX sdk version to 0.2.0
Also exposes a couple of debugging/development features in `values.yaml`
> Update endpoint helm chart to use updated executors config

- Dockerfile-endpoint
- helm/funcx_endpoint/templates/endpoint-deployment.yaml
Move zmq install command from yaml file to dockerfile to save endpoint deployment time
> Move zmq install command from yaml file to dockerfile to save endpoint deployment time

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
> Version bump to 0.2.0a2 for testing

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
> Bumping to release version v0.2.0

- funcx_sdk/funcx/serialize/concretes.py
remove json serializer to avoid convert tuple result to list
fixes #424
> remove json serializer to avoid tuple to list

- docs/configs/kube.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
This PR fixes container resolving in k8s deployment in 0.2.0
> Fix container resolving in k8s deployment

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
The PR is for Issue #427
Let us discuss where to put the example config
> Added debug info for out of date config

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/version.py
Previously we only check if endpoint version matches with the service. This PR adds capability to check sdk as well
> Check funcx sdk version with web service

- funcx_sdk/requirements.txt
This PR adds packaging to requirements.txt
> Add packaging to requirements.txt

- docs/changelog.rst
Adding changelog notes for v0.2.1 and v0.2.2.
> Changelog updates 0.2.2

- .github/workflows/tutorial.yaml
- funcx_endpoint/tests/tutorial_ep/test_tutotial_ep.py
Goals:
We want to build a github actions workflow, which sends a `FuncXClient` function invocation request every hour to the tutorial endpoint to test its liveness.
The current status:
- The python code has been tested locally by `python funcx_endpoint/tests/tutorial_ep/test_tutotial_ep.py -t '4b116d3c-1703-4f8f-9f6f-39921e5864df' -i API_CLIENT_ID -s API_CLIENT_SECRET`. It works well.
- Two secrets `${{ secrets.API_CLIENT_ID }}` and `${{ secrets.API_CLIENT_SECRET }}` have been created on github.
- We should be able to test the work after merging it. There are two items we should pay attention: (1) make sure the test is executed every hour. (2) If meeting any exception, we should receive note email.
> Testing tutorial endpoint

- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint.py
This PR is for Issue #438.
This PR adds unit tests for code changes in PR 431 and PR 435.
> Added unit tests for PRs #431 and #435

- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint.py
Loosed a too strict assertion in endpoint unit test
> Update to endpoint unit test

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds github templates to fix #471
> Adding PR and issue templates.

- .github/workflows/tutorial.yaml
Added timeout to github workflow, to avoid infinite work status checking
> Added timeout for workflow

- .github/workflows/tutorial.yaml
For tutorial endpoint test, make all installations from pip, not local repo
> For tutorial endpoint test, make all installations from pip, not local repo

- funcx_endpoint/tests/tutorial_ep/test_tutotial_ep.py
Removed the use of numpy from the tutorial endpoint test
> Remove numpy requirement from the test

- docs/changelog.rst
- docs/reference.rst
- docs/stubs/funcx.rst
- docs/stubs/funcx.sdk.errors.TaskPending.rst
- docs/stubs/funcx.serialize.base.rst
- docs/stubs/funcx.serialize.concretes.rst
- docs/stubs/funcx.utils.errors.TaskPending.rst
- docs/stubs/funcx_endpoint.endpoint.endpoint.rst
Changelog for v0.2.3. Do not merge!
> Changelog v0.2.3

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
As described in Issue#474, we wanted to refactor the task loop in the funcx_worker, to make it more readable.
> Refactored the task loop in the funcx_worker

- docs/endpoints.rst
- docs/stubs/funcx.utils.errors.TaskPending.rst
Docs update to describe new endpoint state
Should be merged after: https://github.com/funcx-faas/funcX/pull/520
> docs: update endpoint list/stop info related to new endpoint state

- docs/endpoints.rst
This PR adds descriptions of container behaviors and routing to docs
> Add docs for container behaviors and routing

- funcx_sdk/funcx/utils/response_errors.py
We are missing a few error types that the web service is sending, which currently will not have as pretty of an error message
Partially Fixes https://github.com/funcx-faas/funcX/issues/389 (do not close until related PR is merged on web service side)
> add new uuid and task group error types

- docs/configs/bluewaters.py
- docs/configs/cori.py
- docs/configs/frontera.py
- docs/configs/kube.py
- docs/configs/midway.py
- docs/configs/perlmutter.py
- docs/configs/theta.py
- docs/configs/uchicago_ai_cluster.py
- funcx_endpoint/requirements.txt
- funcx_sdk/funcx/tests/test_result_size.py
- funcx_sdk/requirements.txt
- funcx_sdk/setup.py
#Problem
Adding the parsl namespace to the SDK causes problems in the endpoint which also relies on parsl.
Reverting those changes
> Revert spoof parsl

- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/tests/conftest.py
- funcx_sdk/funcx/tests/test_async.py
- funcx_sdk/funcx/tests/test_executor.py
More tests are needed for executor and the async client. This PR normalizes existing tests to the pytest suite and adds new tests.
Fixes https://github.com/funcx-faas/funcX/issues/515
- Tests
> Add more executor/async tests to pytest suite

- helm/funcx_endpoint/Chart.yaml
Update helm chart to have latest version
> Update chart version to 0.3.0

- docs/actionprovider.rst
- docs/doc-requirements.txt
- docs/index.rst
Introduces an initial doc file for the Globus Flows Action Provider funcX exposes.
Fixes #556 
> Initial AP doc

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
Just updated sdk and endpoint version.py to reflect the latest release
> Bump version to 0.3.1

- tag_and_release.sh
There was a mistake in the tag_and_release script.
Changed `git branch -b` to `git checkout -b`
> Fix git command to create version branch

- funcx_sdk/funcx/tests/test_async.py
Fix issue of `test_async` timing out
> Fix issue of test_async timing out before test complete

- funcx_endpoint/funcx_endpoint/endpoint/taskqueue.py
Some zmq socket option setting needs to be fixed (all options must be set before the bind/connect call is made)
Working on https://app.clubhouse.io/funcx/story/9842/handle-endpoint-zmq-disconnects-with-forwarder
> Fix zmq option setting bugs

- helm/README.md
When going through the helm endpoint installation docs I noticed a few typos and places where a new helm user (such as myself) might get tripped up. I added more context around the instructions to make the process easier.
@BenGalewsky I'm new to the helm side of things so let me know if any of my elaborations are off.
> Helm installation docs updates

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/tests/funcx_endpoint/executors/high_throughput/test_funcx_manager.py
- funcx_endpoint/tests/funcx_endpoint/executors/high_throughput/test_funcx_worker.py
- funcx_endpoint/tests/funcx_endpoint/executors/high_throughput/test_worker_map.py
Fixing pytest tests for the endpoint to prevent hangs
(Test updates)
> Fix endpoint pytest hangs

- funcx_endpoint/funcx_endpoint/endpoint/results_ack.py
Change task ack log level to debug to reduce log spam
> Ack log debug level

- .github/workflows/tutorial.yaml
Sends emails to multiple people when the tutorial test action fails.
> Email tutorial tests

- README.rst
- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
Updates the changelog, and version numbers to 0.3.3a0
> Adding changelog and updating version to 0.3.3a0

- .github/workflows/smoke_test.yaml
- .github/workflows/tutorial.yaml
* Change the build target from a dead branch to main
* Rename the test from tutorial test to smoke_test
> Change build target tutorial repo

- funcx_endpoint/tests/smoke_tests/conftest.py
version=0.3.5
add a "dev" block to the config for ease of use.
black and isort on the file
> Update smoke test config with version, dev env

- helm/funcx_endpoint/Chart.yaml
- helm/funcx_endpoint/templates/endpoint-deployment.yaml
We needed to include a security context to allow endpoints running on EKS to provision new pods.
Fixes # [(issue)](https://app.shortcut.com/funcx/story/12051/create-a-tutorial-endpoint-with-a-fixed-id-in-the-dev-environment)
> Fix helm permissions

- .pre-commit-config.yaml
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/strategies/simple.py
- funcx_endpoint/tests/integration/test_batch_submit.py
- funcx_endpoint/tests/integration/test_per_func_batch.py
- funcx_sdk/funcx/tests/test_batch.py
- funcx_sdk/funcx/tests/test_performance/test_performance.py
Update to the latest versions of all hooks with `pre-commit autoupdate` and apply the changes the hooks require.
Primarily, `pyupgrade` now turns `sum([<generator>])` into `sum(<generator>)`.
> Update pre-commit (autoupdate)

- README.rst
- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
Only version bump and changelog updates included.
> Version bump to 0.3.6

- funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
The signature for GlobusAPIError has changed such that it now consumes a requests.Response object, not a GlobusHTTPResponse. Furthermore, it is necessary for a Response to have an attached PreparedRequest.
Patch these into the tests which were broken by the upgrade.
I tested this on top of #686, and then rebased from there. I recommend cherry-picking in #686 if you want to test this locally.
> Fix endpoint tests broken by sdk v3

- .pre-commit-config.yaml
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/tests/integration/test_throttling.py
- funcx_sdk/funcx/tests/test_async.py
`pre-commit autoupdate`
This should also trigger (newly-enabled) pre-commit.ci for this repo.
> Update pre-commit config

- .github/workflows/daily.yaml
- .github/workflows/hourly.yaml
Remove uriel from smoke test notifications.
> Removing uriel from action notifications.

- changelog.d/20220223_151734_rchard_add_task_timing.rst
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Captures the execution time of the task and adds it to the result dict passed back to the forwarder.
Fixes # [sc-13437]
> Add task execution timing

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/sdk/version.py
The PR only contains a version update to 0.3.8-dev.
> Bump version to 0.3.8-dev

- changelog.d/20220315_140531_benc_benc_exa_logs_process_thread_names.rst
- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/strategies/base.py
This adds process names and thread names to everything launched in the endpoint code. This is intended to enhance PR #716 
> Name endpoint threads and processes, to appear in logs

- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Remove `!` to lessen the surprisiness of an expected debug message.
> Reduce surprise level for expected log message

- funcx_sdk/funcx/sdk/executor.py
This is a live test, so better instantiated in a developer's personal
corpus of scripts.
> Remove unused testing code.

- funcx_sdk/funcx/sdk/executor.py
This is in line with changes made to the endpoint in PR #716 to name threads
using Python's built-in thread naming, which means that logged thread names
should correspond to the actual thread.
In this case, TASK_SUBMIT_THREAD messages were being logged by the main thread
in the default case of batch_enabled=False
> Remove incorrect manual thread identification from executor and add names on Threads

- funcx_sdk/funcx/sdk/executor.py
Previously tasks and task_id were used to refer to a "thing that will
probably become a funcx task later, but for now is just a Future".
The id is renamed future_id.
The _tasks dictionary is renamed to be consistent with _function_future_map,
to _counter_future_map.
The type of _counter_future_map is fixed.
Please include a summary of the change and (optionally) which issue is fixed. Please also include
relevant motivation and context.
No changelog because this is not externally visible to users.
> Rename variables in FuncXExecutor for clarify

- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/funcx/tests/unit/test_atomiccontroller.py
A minor reduction of required function calls and lock acquisitions.
> Teach AtomicController to increase by n

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/executor.py
A mostly NFC (non-functional change).  Just typing info.
> Add some typing information

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
A mild NFC.  In pursuit of #11102
> Remove useless else branch

- funcx_sdk/funcx/sdk/executor.py
There is no need to copy (okay, likely interned, but still) the strings around.  Let `FuncXClient` be the single source of truth until we refactor this whole shebang at a later date.
> Remove some redundancy

- funcx_sdk/funcx/sdk/executor.py
An NFC, to elucidate some typing information, and make a future modification more clear.
> Mild clarification of data structure parts

- funcx_sdk/funcx/sdk/executor.py
Submit just needs a registered function.  It should not be responsible for the logic of _registering_ the function.
> Reduce visual complexity of `.submit()`

- funcx_sdk/funcx/sdk/client.py
> Minor refactor to clarify class var intent

- funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
> An unused decoding.  No need.

- funcx_sdk/funcx/sdk/executor.py
The thread is a "private" implementation detail of the class, so underscore it.  Meanwhile, make use of a variable in a loop criteria.
> Mild variable name change.

- funcx_sdk/funcx/sdk/executor.py
Minor NFC cleanup.
In pursuit of #727.
> "Privatize" lock, update method signatures.

- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_atomiccontroller.py
A small PR in pursuit of #727.
> Teach AtomicController how to reset itself.

- funcx_sdk/funcx/sdk/executor.py
A simple refactor while pursuing #727.
> No need for extra method.

- funcx_sdk/funcx/sdk/executor.py
But the larger thrust is to private the thread start() method.  That
is not currently designed to be touched by external code.
In pursuit of #727.
> Remove unused arguments.

- funcx_sdk/funcx/sdk/executor.py
As a mild simplification for tests in an upcoming PR, teach the class a trick.
- Maintenance
> Teach FuncXFuture to set the task_id in init.

- .github/PULL_REQUEST_TEMPLATE.md
> PR template spelling typo

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/executor.py
This simultaneously sets up the possibility to reuse an `ExecutorPollerThread` instance, cleans up `_start()`, and cleans up `shutdown()`.
In pursuit of #727.
> Remove type ambiguity in ExecutorPollerThread

- funcx_endpoint/setup.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange_with_rabbit.py
This avoids any requirement for local creds
> Fix: test clients should use a mock login_manager

- changelog.d/20220506_150231_chris_client_version_logging.rst
- funcx_sdk/funcx/sdk/login_manager/manager.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/tests/unit/test_web_client.py
> Client version logging

- .dockerignore
[sc-12147]
Using modified `.dockerignore` template from https://github.com/themattrix/python-pypi-template/blob/master/.dockerignore
> Add dockerignore to endpoint

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/funcx_endpoint/endpoint/test_messages_compat.py
The (hopefully) final message that needs to be converted from HTEX messages to `funcx_common.messagepack`.
Fixes [sc-13574]
> Convert `Task` to messagepack

- smoke_tests/tests/test_s3_indirect.py
- smoke_tests/tests/test_version.py
Update smoke tests to work with new RabbitMQ changes.
Fixes [sc-14883]
> Fix smoke tests

- funcx_sdk/setup.py
> Remove numpy from test deps

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Mostly just define some class vars in `__init__` rather than after initialization.  Typing is Good Stuff!
> Mild set of changes to appease mypy

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Non-functional change; just using the loop conditional syntax over an embedded if-break.
> Minor loop refactor

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
> Publishing a message is probably not an emergency

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
> Lower severity of task submission warning

- funcx_endpoint/funcx_endpoint/strategies/simple.py
The much more interesting information is when data _changes_.
> No sense in repeating unchanging information

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_sdk/setup.py
> Remove typoed manual thread annotation in favour of existing automatic log annotation

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
> Log which manager a task was sent to

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange_task_dispatch.py
> Reduce severity of endpoint message appearing multiple times per second

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
All paths are covered by more specific statements, so remove extra log line in
the most common case.
> Remove unnecessary log statement.

- funcx_endpoint/funcx_endpoint/cli.py
Dropped in 35e3d2b931271f2a70864b3d83ab66232f029708.
> Mistakenly lost interpolation variable

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
> Remove unused variable.

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Previously, the endpoint was shutdown by the cold logic of SIGTERM, wait for 10s, then SIGKILL.  The problem was that the SIGTERM handler was blocking everytime, and so SIGKILL was always called.  In production, this might be hidden by logs -- if evidence of it was logged at all -- or ignored because Ctrl+C (a.k.a., "SIGINT") is handled differently by default.  So ... not a visible problem, but certainly "dirty" in the professional sense, and made writing useful integration tests quite difficult.
To see this in action on code prior to this PR, run an endpoint (e.g., `funcx-endpoint start <ep_name>`) configured to not detach (`config.py`, `detach_endpoint=False`), then send the main process a SIGTERM.  Watch as the endpoint will not shutdown.  Then hit Ctrl+C to see the traceback and …
> Correct endpoint shutdown logic

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Hopefully never a problem in production, but helpful while building tests.  We have the information, why not share it?
> Provide a little more help in error case

- funcx_endpoint/funcx_endpoint/version.py
Only version update for `funcx-endpoint==1.0.0a0`
> Updating version to 1.0.0a0

- funcx_endpoint/funcx_endpoint/version.py
Update to address the release-day-found authentication bug, addressed by PR #884.
> Release v1.0.1

- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
Provide default values for exec_.._ms in case not present as short term fix
> provide default values for exec_.._ms to avoid keyerror

- funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
Should have been refactored in 8f41c61e24ea42f900e0e3e8d8600d22f658c35b.
> Missing variable refactor

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
A non-functional change -- just reducing the imported tokens.
> NFC: namespace the typing hints

- funcx_sdk/funcx/sdk/executor.py
There's no need to iterate the loop when no results come in.  Transition to a poison-pill methodology and let the native Queue blocking semantics slightly improve the resource usage.
> Remove artificial iteration and wait during submission

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
This method's invocation has been commented out for some time.
> Remove dead code

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/tests/unit/test_highthroughputinterchange.py
We can detect most startup errors in the executor interchange fairly quickly: catch the exception.  Thus, do so, and let the parent process know right away -- no sense in timing out if we know with certaintly that we're not going to succeed.  Now the endpoint won't continue but quit immediately -- better iteration path for the human.
Meanwhile, add a slight delay as a quick-and-dirty hack to avoid interwoven exception lines from the parent and child processes in the log or output.
> More robustly handle executor failure to start

- funcx_sdk/funcx/sdk/executor.py
This is all of note only when trying to track down a problem -- akin to trace.  These paths are expected to "just work" 99.9% of the time and only be of interest to developers.
> Reduce log-level to debug

- funcx_sdk/funcx/sdk/executor.py
A non-function-change of `msg` &rarr; `task` for code clarity.  Yes, it's a "message", but we mentally think about it as a task of a set of tasks.
> Rename variable for clarity

- funcx_sdk/funcx/sdk/executor.py
And a couple of other minor doc or typing additions.
> Add a block comment to the FuncXExecutor class

- funcx_endpoint/funcx_endpoint/logging_config.py
Only an issue for those of us `--debug`ing via the command line.
> Correct errant copy-paste-o

- funcx_sdk/funcx/sdk/login_manager/manager.py
Check if running in Jupyter, in which proceed instead of Raise
> check jupyter notebook in addition to tty

- changelog.d/20220831_210735_kevin_add_submitted_task_counter.rst
- changelog.d/20220907_150940_chris_dont_require_client_argument.rst
- changelog.d/20220908_132611_LeiGlobus_websocket_queue_flag_sc_15524.rst
- changelog.d/20220920_114304_kevin_refactor_executor_task_future_association.rst
- changelog.d/20220921_161549_kevin_serialize_access_to_sqlite.rst
- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_endpoint/setup.py
- funcx_sdk/funcx/version.py
Bump version to 1.04 in prep for release to dev and prod
> Bump versions and changelog for release v1.0.4

- funcx_sdk/funcx/sdk/batch.py
There's no sense in doubling the work; do it once, and share the result.  Nicer on the internal memory, and a mild performance boost.  (At a decidedly non-bottleneck point!)
> Refactor internal data structure

- docs/endpoints.rst
- docs/sdk.rst
Add documentation regarding client logins and custom login managers.
Fixes [sc-19653] and [sc-18508]
> Update client docs

- .github/workflows/ci.yaml
- changelog.d/20221028_065929_rchard_ati_with_htex_fix.rst
- funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/messages.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
- funcx_endpoint/tests/unit/test_funcx_manager_unit.py
- funcx_endpoint/tests/unit/test_highthroughputinterchange.py
- funcx_endpoint/tox.ini
- funcx_sdk/setup.py
Includes timing breadcrumbs in both manager and endpoint status reports.
[sc-17571]
> Add timing info

- docs/endpoints.rst
- docs/sdk.rst
Quick fix to a broken link in the docs.
> Correct link to client login description

- smoke_tests/tests/test_running_functions.py
While here, replace non-DRY code with a for-loop.
> Add .reload_tasks() to executor smoke test

- funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
- funcx_sdk/funcx/sdk/batch.py
- funcx_sdk/funcx/sdk/executor.py
Correctly address a couple of newly-identified issues.
> Mypy got more strict this weekend

- docs/quickstart.rst
And add link to endpoint page.
> Use convenience import in doc

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
- funcx_endpoint/tox.ini
- funcx_sdk/setup.py
Safety checks have been failing due to a recently discovered [vulnerability in `py`](https://pyup.io/v/51457/f17/) - this PR fixes the failing safety checks.
I also included some "leave it better than you found it" cleanup, so it's probably easier to review this on a commit-by-commit basis.
- Security fix
> Address CVE-2022-42969

- funcx_endpoint/funcx_endpoint/cli.py
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/conftest.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
- funcx_endpoint/tests/unit/test_cli_behavior.py
The only structure of interest is the Config object.
> Stop passing around module

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
In it's own PR to unclutter others.
> Remove useless branch

- changelog.d/20221027_140534_LeiGlobus_endpoint_lock_sc_19081.rst
- changelog.d/20221206_113101_chris_get_endpoints_functions.rst
- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/version.py
Release branch: updates version number and changelog.
> Bumping version and changelog for release v1.0.6

- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Migrates task statuses from the heartbeat status into the result object. Currently, interim task statuses (running, waiting for nodes, etc.) are only reported as part of the heartbeat. However, when a task completes any outstanding heartbeat statuses related to the task are popped off the status report and discarded. This means short running tasks that complete before a heartbeat is sent will not capture interim statuses. This PR migrates the interim statuses into the result object before returning it to the service.
Fixes # [sc-20393]
> Migrate task statuses

- funcx_sdk/funcx/sdk/executor.py
- funcx_sdk/tests/unit/test_executor.py
We already had retry logic, but the bug was in not allowing the retry logic to execute after the `_on_open_failed()` callback -- crucial since this first step was impeded by other processes.  Addressed with an if-branch.  Meanwhile, this would have been noisy for users, so take the extra step of hiding (moving to `log.debug()` level) the exception until there are no more attempts left.
One notable change: no longer opportunistically shutdown the connection to the AMQP service.  Instead, wait until the Executor is shutdown normally (e.g., `fxe.shutdown()`).  Unlike in times past, the AMQP connection is much lighter-weight and our handling routines are now much more robust.  Per team discussion.
N.B. The recreation code provided for testing was:
from multiprocessing import Pool
import funcx …
> Play nice with multi-process approaches

- funcx_sdk/tests/unit/test_login_manager.py
Test worked through "sheer luck" and that the code under test was correct, not because the _test_ code was correct.  :facepalm:
> Correct errant test

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
Utilize `pathlib` and slight DRYification; mainly to ease the review burden on an upcoming PR.
> Minor refactor

- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
> Another minor "to pathlib" refactor

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Code cleanup. This PR removes some vestiges from when the interchange was launched onto a remote machine. 
> Interchange cleanup

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
> Remove unused constants

- funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Observed verbally in a previous PR, addressing before they leave my mind.
> Minor documentation and log changes

- funcx_endpoint/funcx_endpoint/cli.py
> Minor refactor to use pathlib

- changelog.d/20230119_130618_chris_endpoint_metadata_sc_20196.rst
- funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
- funcx_endpoint/setup.py
- funcx_endpoint/tests/unit/test_endpoint_unit.py
- funcx_sdk/funcx/sdk/client.py
- funcx_sdk/funcx/sdk/web_client.py
- funcx_sdk/funcx/version.py
Sister PR for https://github.com/globusonline/funcx-services/pull/211
[sc-20196]
> Update endpoint metadata registration for SC 20196

- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/version.py
About to do a dev deploy, need to update the EP version to do so
> Bump versions for alpha release

- changelog.d/20230202_002915_kevin_htex_interchange_bad_manager_iteration_fix.rst
- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/version.py
Bug fix release, bumping to v1.0.10
> Bump versions and changelog for (bugfix) release

- funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
- funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
This code is completely unused.
> Remove dead status_message handling code

- helm/README.md
- helm/boot.sh
And add a debugging message for container start.
> Remove stale documentation from README

- docs/changelog.rst
- funcx_endpoint/funcx_endpoint/version.py
- funcx_sdk/funcx/version.py
Bumping changelog and metadata for v1.0.12
> Prep metadata for v1.0.12 release

- funcx_endpoint/funcx_endpoint/cli.py
A follow-up to f6e33250ae0fb18923bf4ddde698a1a1b27310b3: remove the unnecessarily non-DRY function arguments.
> Go distance and DRY the function signatures

- docs/api_docs/index.rst
- docs/index.rst
This PR adds Globus Compute API documentation external links to the documentation side bar.
[sc-21610]
> Add API docs external links to docs side bar

- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
- compute_endpoint/tests/unit/test_endpointinterchange.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_highthroughputinterchange.py
- compute_endpoint/tests/unit/test_worker.py
With thanks to @benclifford for the diagnotistic fixture idea.
[sc-23636]
> Clean up signal handlers

- compute_endpoint/globus_compute_endpoint/executors/high_throughput/worker.py
> Remove unused variable

- compute_endpoint/MANIFEST.in
- compute_endpoint/PyPI.md
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_funcx/endpoint/MANIFEST.in
- compute_funcx/endpoint/PyPI.md
- compute_funcx/endpoint/funcx_endpoint/version.py
- compute_funcx/endpoint/setup.py
- compute_funcx/sdk/MANIFEST.in
- compute_funcx/sdk/PyPI.md
- compute_funcx/sdk/funcx/version.py
- compute_funcx/sdk/setup.py
- compute_sdk/MANIFEST.in
- compute_sdk/PyPI.md
- compute_sdk/globus_compute_sdk/version.py
- compute_sdk/setup.py
- docs/changelog.rst
Wording for PyPI package descriptions. Haven't yet tested that this deploys to PyPI properly; waiting on others to OK the language first, then will do an alpha release before merging.
[sc-21439]
> Add descriptions to packages on PyPI

- docs/funcx_upgrade.rst
> Fix typo in upgrade doc

- helm/funcx_endpoint/templates/endpoint-instance-config.yaml
> Move display_name to top-level

- compute_endpoint/globus_compute_endpoint/cli.py
This adds some additional verbiage to the exception raised in the `funcx-endpoint` version check (see #1109).
[sc-23826]
> Update wording for funcx-endpoint version check

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
> Mild test refactor

- helm/funcx_endpoint/Chart.yaml
Update chart version to 0.7.0.  Repackaging for EPStatusReport Fix.
> Update chart for endopint

- Dockerfile-endpoint
- reinstall.sh
Please include a summary of the change and (optionally) which issue is fixed. Please also include
relevant motivation and context.
> remove GC_TASK timeout

- changelog.d/20230421_103504_LeiGlobus_update_globus_urls_sc_23455.rst
- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/conftest.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/globus_compute_sdk/sdk/asynchronous/ws_polling_task.py
- compute_sdk/tests/conftest.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_environment_lookups.py
- docs/api_docs/index.rst
- docs/changelog.rst
- docs/endpoints.rst
- docs/funcx_upgrade.rst
- docs/quickstart.rst
- helm/funcx_endpoint/values.yaml
Update api2.funcx.org to the brand new compute version
> Update api2... URLs to globus one

- compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
- compute_endpoint/globus_compute_endpoint/providers/kubernetes/kube.py
- compute_endpoint/globus_compute_endpoint/strategies/kube_simple.py
If nothing has change since last log line, then there is no added value by duplicating the text.
> Reduce some unnecessary log churn

- compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
Previously, the endpoint could send an arbitrarily large status report packet.  While the services handle the packet just fine (regardless of size), it's just generally courteous to chunk large amounts work.  So, play by the "unwritten rules or courtesy."
[sc-19723]
> Teach interchange to send bite-sized updates

- compute_endpoint/globus_compute_endpoint/executors/high_throughput/container_sched.py
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/manager.py
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/worker_map.py
Reduce some selected log noise.  For example, a retrospective only cares when data has _changed_, so don't uselessly repeat the same log line.
> Reduce some log noise

- changelog.d/20230508_132638_chris_seriliazation_tidy_up.rst
- compute_endpoint/globus_compute_endpoint/executors/high_throughput/manager.py
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/concretes.py
Clearing up some minor personal eye-twitches.
> Tidy up serialization-related code

- compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
The interchange should send an EPStatusReport every `heartbeat_period`, period. 273e39002cf1ceda613ba6ad7893b87549c22046 broke that expectation for the case of "no task deltas" -- a common occurrence for the tests we run because when a task is done, it's delta is handled directly by the task-specific result message and removed from the outstanding "task status deltas" data structure.
Even more than tests, however, it's also a problem when there are actually no tasks running -- when the endpoint is legitimately idle, it should still be marked as "online."
Follow up for [sc-19273]
> Send EPStatusReport even if no outstanding tasks

- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
Add tests for config serialization, including passthrough allowlist_functions for PR #1143
(decided to make testing of the serialization a separate PR as it mostly tests prior logic)
> config serialization test

- compute_sdk/globus_compute_sdk/sdk/web_client.py
Fixes smoke tests until we roll prod.
[sc-24274]
> Temporarily send entry_point on function registration

- compute_sdk/globus_compute_sdk/sdk/web_client.py
Revert #1161 to fix smoke tests
> Revert "Temporarily send entry_point on function registration"

- docs/configs/bluewaters.yaml
The example config for Blue Waters in the docs had a small indentation issue.
> Adjust indent in Blue Waters example config

- changelog.d/20230531_120415_chris_remove_entry_point.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
Redo of https://github.com/funcx-faas/funcX/pull/1160 now that the services are updated
> Remove entry point

- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/globus_compute_endpoint/engines/helper.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/globus_compute_endpoint/exception_handling.py
This doesn't mean that all subclasses have to _use_ it, but does mean that the interface it provides allows for it still work under Liskov.
Everything else beyond changing `def _submit(...)` to match the parent class, is related cleanup.
Yet a WIP.
> Return to strict executor interface

- changelog.d/20230614_163947_chris_serialization_user_convenience.rst
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/integration/test_serialization.py
Includes a new method for verifying serialization strategies against a given use-case, and some small serialization-related cleanup.
> Minor user-facing changes to serialization interface

- changelog.d/20230614_163947_chris_serialization_user_convenience.rst
- compute_sdk/globus_compute_sdk/serialize/base.py
- compute_sdk/globus_compute_sdk/serialize/facade.py
- compute_sdk/tests/integration/test_serialization.py
- docs/sdk.rst
Add a section to the SDK documentation about user-selectable serialization.
This branch also includes the changes in https://github.com/funcx-faas/funcX/pull/1177, as they all came up during the process of writing this documentation. The plan is to hold this PR back until the other one is merged.
> Document selectable serialization

- compute_endpoint/globus_compute_endpoint/logging_config.py
When reading logs, the unixtime prefix hasn't proven to be useful, instead just extra noise and bytes wasted.  The only potential value it provided was sub-second precision for each log-line; keep that by tacking on microsecond precision to the human readable variant.
Before: 1686583465.954335 2023-06-12 11:24:25 [...]
After:  2023-06-12 11:24:25.954335 [...]
Removes an unnecessary 11 bytes from each log-line.
> Remove unixtime prefix

- docs/changelog.rst
- docs/changelog_funcx.rst
Fixes the issue raised here https://funcx.slack.com/archives/C016JMYST9C/p1687462186370179?thread_ts=1687384666.191469&cid=C016JMYST9C
> Fix formatting in changelog

- docs/configs/polaris.yaml
Makes the config use double quotes and set filesystems by default
> Update the polaris example config

- docs/changelog_funcx.rst
- docs/configs/bebop.yaml
- docs/configs/bluewaters.yaml
- docs/configs/cooley.yaml
- docs/configs/cori.yaml
- docs/configs/frontera.yaml
- docs/configs/kube.yaml
- docs/configs/midway.yaml
- docs/configs/midway_singularity.yaml
- docs/configs/perlmutter.yaml
- docs/configs/theta.yaml
- docs/configs/theta_singularity.yaml
- docs/configs/worker_pinning.yaml
replace single quotes due to yaml parking issue
> Replace single quotes in yaml configs

- changelog.d/20230628_132155_chris_endpoint_setup_teardown.rst
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- docs/endpoints.rst
Redo of #1188 with expanded scope and included feedback.
[sc-24188]
> Add `endpoint_setup` and `endpoint_teardown`

- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_environment_lookups.py
- compute_sdk/tests/unit/test_web_client.py
The ability to specify an API version in each request will enable a more gradual migration to v3 API routes.
[sc-25453]
> Specify API version in each request

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
The test was utilizing the `fs` mock and also `patch()`ing a method.  The patch returned a `pathlib.Path` object, but was applied _before_ the `fs` fixture had setup.  Update test so that the `fs` fixture is in place prior to the mock.
Meanwhile, after the test was corrected, noted that the logic under test was not completely correct per the method documentation: replaced `str.replace` with `re.sub("^...")` so as to match strictly at the beginning of lines.
While here, apply a couple of other minor refactors:
- add `funcx_endpoint.engines` to what is considered for replacement (per the recently merged Engine work)
- use _MOCK_BASE to simplify some logic in the test file
- remove used test parameters (always `False`)
- correct fallback test logic (`assert AssertionError` &rarr; `raise …
> Fix broken test

- .github/workflows/ci.yaml
- .github/workflows/daily.yaml
- .github/workflows/hourly.yaml
- .github/workflows/smoke_test.yaml
- changelog.d/20230705_141150_kevin_update_locked_parsl_version.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
- compute_endpoint/setup.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tox.ini
- compute_sdk/setup.py
- compute_sdk/tests/integration/test_serialization.py
- compute_sdk/tox.ini
Besides the incremental updates, the main motivation is for [PR #2775 "Ensure timer.cancel() is always called"](https://github.com/Parsl/parsl/pull/2775)
[sc-25117]
> Update Parsl version to 2023.7.3

- changelog.d/20230714_103852_30907815+rjmello_optional_provider.rst
Add missing changelog for #1216.
> Add changelog for optional provider field bugfix

- compute_sdk/tests/unit/test_executor.py
Mild simplification of `.patch()` calls related to this test file.
> NFC: DRY some test text strings

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
Take the opportunity to store `container_id` as a more efficient UUID type.
> Submit JSON `null`, not `"None"`

- smoke_tests/tests/test_running_functions.py
We've **already published 2.2.4**.  Sometimes ...
Sorry for the noise.  :egg: &rarr; :no_mouth: 
> Make that 2.2.5.  *sigh*

- compute_sdk/globus_compute_sdk/sdk/batch.py
No sense in needlessly recreating the serializer object.
> Reuse serializer

- compute_sdk/globus_compute_sdk/sdk/web_client.py
No sense in having multiple definitions of the same thing.
> Coalesce to the UUID_TYPE_T

- compute_sdk/globus_compute_sdk/sdk/batch.py
- compute_sdk/globus_compute_sdk/sdk/client.py
> Small typing addition

- compute_sdk/tests/unit/test_executor.py
> Remove test for now-gone attribute

- compute_sdk/globus_compute_sdk/sdk/client.py
At some point, we should consider `TypedDict` or even a more formal typing, but for now, just address it.  A future ticket ...
> Address advertised typing

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Look for a file in the MT endpoint configuration directory (`user_environment.yaml`) and attempt to load it.  The file is interpreted as a 1:1 mapping to the expected environment variables the child process will have provided for it.
From the surrounding code, the `HOME`, `USER`, and `PWD` environment variables are determined by `pwd.getpwnam`, but any other environment variable may be set per the administrator's discretion.  A simple example:
```yaml
PATH: /usr/local/bin:/usr/bin:/bin:/opt/bin:/path/to/some/virtualenv/bin
OTHER_EXPORTED_ENV_VARIABLE: some value
ANOTHER_ENV_VARIABLE: "the next var is a number, but per usual semantics is a string:"
INTERPRETED_AS_STRING: 123
var5_is_ALSO_a_STRING: true
var5:
- var1: 234
- var2:
- var3: Abvc
```
Would be interpreted as the Python data …
> Implement admin-specified user-endpoint env

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Test was taking close to 18s on my machine, due to useless and idle waiting, and then producing a traceback.  The traceback wasn't important to the test, but was noise "of concern" until I figured it out.  Realized that for the original intent of the test (written in mid 2021), there was no need to start up a child process.  Now uses the `ThreadPoolEngine` for a much faster turnaround time with no traceback.
> Address slow test

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
> Use pathlib object

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
No sense in raising ClickException if not in the CLI set of codes.
> Move ClickException to closer to the CLI

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/command_queue_subscriber.py
- compute_endpoint/tests/unit/test_command_queue_subscriber.py
> Redact credentials from log emission

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Use the Jinja sandbox to prohibit access to unsafe attributes and methods in user config templates. Note that this mainly serves as an additional layer of security to protect endpoint admins from themselves.
[sc-26181]
> Evaluate untrusted code in Jinja sandbox

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The filter is a passthrough to `shlex.quote()`. We expect endpoint admins to use the filter on the config variables that accept arbitrary shell command tokens.
E.g.,
```yaml
engine:
type: GlobusComputeEngine
provider:
type: SlurmProvider
scheduler_options: '#SBATCH {% for opt in OPTIONS %}{{ opt|shell_escape }} {% endfor %}'
```
[sc-26181]
> Create Jinja filter to escape shell commands

- changelog.d/20230814_175226_30907815+rjmello_HEAD.rst
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
Identified and fixed by @rjmello; pulled into a separate PR (from #1268) for clarity of changes.
> Ensure matching types in TG UUID comparison

- compute_sdk/globus_compute_sdk/serialize/concretes.py
- compute_sdk/tests/integration/test_serialization.py
Update CombinedCode to handle serialization Exceptions
CombinedCode was designed to handle deserialization errors.  However, it was never tested with functions that fails to serialize.  It should be resilient during both serialization and deserialization.  Updated and added test case.
> Make sure combinedCode works when serialization fails

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_endpoint/tests/unit/test_utils.py
Fixes imports around `import pyprctl`, which raises an `AttributeError` on macOS.
> Allow macOS to test

- changelog.d/20230814_180727_chris_cli_name_uuid_equivalence.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
> CLI can accept UUID arguments in addition to names

- docs/endpoints.rst
> Add tutorial for systemd service

- compute_endpoint/globus_compute_endpoint/cli.py
Following [this PR](https://github.com/funcx-faas/funcX/pull/1282) where we blocked the ability to start multi-tenant endpoints on macOS, we should also block the ability to *configure* them. Don't want to instill false hope.
> Also block macos from configuring multi-tenant endpoints

- compute_endpoint/MANIFEST.in
These are necessary for the multi-tenant work.
[sc-26865]
> Two forgotten files to endpoint packaging

- changelog.d/20230907_152826_kevin_upgrade_requests.rst
- compute_endpoint/setup.py
- compute_sdk/setup.py
Correctly appease the linters and IDEs.
> Upgrade requests

- compute_endpoint/tests/unit/test_command_queue_subscriber.py
The mock setup was waiting for *one* indicator, but not all.  Make the mock setup indicator explicit with a `threading.Event` object.
- Bug fix (non-breaking change that fixes an issue)  [a _test_ bug, but a bug!]
> Address flaky test

- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/tests/unit/test_environment_lookups.py
Updated the production AMQP service host to the new domain. This fixes the `self-diagnostic` connection tests.
> Update prod AMQP service host to new domain

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
- compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_web_client.py
> Rename anything "multi tenant" to "multi-user"

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tox.ini
So remove a workaround we had implemented previously
> Mypy 1.6.1 got a little smarter / picky

- compute_endpoint/MANIFEST.in
> Add missing files to manifest

- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
Alpha release for testing a few MU related items.
* This is to incorporate a few of the recent bugfixes re:  config json files.
> Bump version for 2.8.0a0 alpha testing release

- changelog.d/20231108_133632_yadudoc1729_heartbeats_and_reporting_sc_28343.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
Bumping version to v2.8.0. Only updates the version and changelog.
> Bumping version to v2.8.0 for release

- compute_endpoint/globus_compute_endpoint/engines/base.py
The `report_status` method is used instead.
> Remove unused `_status_report` method

- compute_sdk/globus_compute_sdk/sdk/executor.py
As with a recent commit (7ec9c67307138) tell the format string what we're specifically after.
> Be explicit about use of `repr()`

- compute_endpoint/tests/unit/test_cli_behavior.py
Just implementing `_MOCK_BASE`
> Minor NFC change to test_cli codes

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
Recreating case:
```python
with Executor(
endpoint_id, user_endpoint_config={"endpoint_setup": "something that will break"}
) as ex:
ex.submit(noop).result(2)
```
The web service (currently) takes about 30s to give up waiting for the UEP to come online.  But the code will only wait for 2s (`.result()`).  Unfortunately, if the underlying HTTP request to the API is outstanding, there is no way to interrupt it.
So, don't try too hard.  If the script continues, then it will _eventually_ time out, but if the script is about to shutdown, let it (via `daemon=True`).  There's no data the user cares about in the thread at that point.  Meanwhile, at least mention it (`log.warning`) for transparency.
For the reviewer: the core changes are the first two hunks in `executor.py`, the `daemon=True`, and …
> Add warning for stuck thread and early stop

- changelog.d/20231216_131520_kurtmckee_fix_daily_workflow.rst
- changelog.d/20231219_144502_30907815+rjmello.rst
- changelog.d/20240102_141658_30907815+rjmello_HEAD.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Bumping version and collecting change-log for 2.10.0 release.
> Bump version for releasing 2.10.0 Jan 3 2024

- docs/configs/faster.yaml
- docs/configuring.rst
By request, creating documentation of a config for FASTER system at TAMU. 
> Adding example configuration in docs for TAMU faster

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
A small set of effectively noop changes to make the follow-up PR more clear.
[sc-28883]
> Preparatory refactor

- changelog.d/20231215_125237_chris_hardware_details.rst
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/globus_compute_sdk/sdk/hardware_report.py
- compute_sdk/tests/unit/test_hardware_report.py
> Add helper functions for reporting endpoint hardware details

- compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
- The unprivileged route needed some coverage.  While here, minor refactor to a couple of fixtures
- Unindent a couple of assertions -- were missed inside of pytest.raises context
> Add 3 missing tests, fix missed assertions

- compute_sdk/tests/unit/test_client.py
In the parent commit, we introduced the `gcc` fixture as an avenue to address the broken `login_manager` fixture.  That commit was focused on the broken fixture.  This commit follows-through on using the new `gcc` fixture for DRYness.
> Replace vestigial non-fixture instantions

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
A forgotten aspect of testing: the chunking logic.
> Add missing test for .reload_tasks

- changelog.d/20240123_115035_kevin_update_parsl.rst
> Typo in changelog.

- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- docs/reference/engine.rst
- docs/reference/index.rst
> Adding reference docs for GlobusComputeEngine

- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_executor.py
> Always warn when SDK and workers have different Python versions

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
> Use the library we created

- compute_endpoint/globus_compute_endpoint/logging_config.py
Rather than a series of if-statements in multiple spots, opt for a `defaultdict` with a pre-defined set of formatters for the common four logging levels.  This makes selection much easier (`formatter = formatters[record.levelno]`).  At the same time, don't attempt to find each individual case of uuid for highlighting.  Instead, format the record to a log line (i.e., a string), and search/replace the string exactly once.  Much simpler.
> Simplify log formatting

- changelog.d/20240216_182658_chris_py_typed.rst
- compute_sdk/setup.py
Required in order for dependent code to use our type hints: https://peps.python.org/pep-0561/#packaging-type-information
[sc-30215]
> Add py.typed

- compute_endpoint/globus_compute_endpoint/MULTIUSER_SETUP.md
> doc: correct getpwnam

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
This is a temporary approach for working through an MEP interaction with cloud services.
> Enable configuration of AMQP connection handling

- changelog.d/20240301_101449_kevin_update_gim_to_030.rst
- compute_endpoint/setup.py
> Bump globus-identity-mapper to 0.3.0

- smoke_tests/tests/test_running_functions.py
> Remove a no-longer-necessary branch (#617)

- changelog.d/20240306_142334_chris_login_command.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
Motivated by [this issue I ran into](https://funcx.slack.com/archives/C016JMYST9C/p1709679728082239?thread_ts=1709677153.704929&cid=C016JMYST9C)
[sc-30608]
> Add login command

- changelog.d/20240319_185839_chris_config_cmd_create_auth_policy.rst
- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/manager.py
- compute_sdk/setup.py
- compute_sdk/tests/unit/test_login_manager.py
[sc-27704]
(based off of [Lei's branch](https://github.com/funcx-faas/funcX/tree/add-auth-policy-params-sc-27704) - thanks to him for that)
> Support auth policy creation during EP configuration

- docs/tutorial.rst
Many users have asked how to run Parsl workflows remotely with Globus Compute. While possible, some special care is required to avoid issues.
Fixes #1490
[sc-30954]
> Add Parsl workflow example to docs

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
> Remove skipped, now stale tests

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
For the reviewer, the main change is to implement the fixtures `ei` and `ei_factory`.  Everything else is just refactoring in terms of those two fixtures.
The motivation of this work is to clarify an upcoming PR.
> Refactor (DRY) test file with fixtures

- changelog.d/20240328_150658_chris_env_var_rename.rst
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_sdk/globus_compute_sdk/sdk/_environments.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/client_login.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/globus_auth.py
- compute_sdk/globus_compute_sdk/sdk/login_manager/manager.py
- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/tests/unit/test_authorizer_login_manager.py
- compute_sdk/tests/unit/test_client.py
- compute_sdk/tests/unit/test_environment_lookups.py
- compute_sdk/tests/unit/test_login_manager.py
- docs/endpoints.rst
- docs/sdk.rst
> Update client env vars to Compute

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Nothing ground-breaking; tell mypy it's okay check these two functions ... and force us to be slightly more strict in our definition.
> Add type-checking to a function

- .github/_support/github-slack-notify.py
- README.rst
- compute_endpoint/packaging/debian/copyright
- compute_endpoint/setup.py
- compute_sdk/setup.py
- docs/changelog.rst
- docs/sdk.rst
- smoke_tests/tox.ini
Update our codebase to match the new repo URLs
> Rename links from funcx-faas GitHub org

- changelog.d/20240411_134946_chris_hotfix.rst
- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Fixes the bug identified [here](https://funcx.slack.com/archives/C016JMYST9C/p1712859596852949)
> Fix breaking change for HighThroughputExecutor

- compute_endpoint/packaging/Makefile
- compute_endpoint/packaging/debian/rules
- compute_endpoint/packaging/package_shim.sh
> Package shim for SEPs

- compute_endpoint/packaging/Makefile
- compute_endpoint/packaging/debian/changelog.in.in
- compute_endpoint/packaging/debian/control
- compute_endpoint/packaging/debian/copyright
- compute_endpoint/packaging/debian/rules
- compute_endpoint/packaging/fedora/globus-compute-agent.spec.in
Per team discussion and naming conflicts
[sc-33028]
> Rename package to `globus-compute-agent`

- compute_sdk/tests/conftest.py
As near as I'm able to determine, this fixture was never anything more than a commented-out line.  I am not able to discern provenance from the Git logs.
> Remove unused fixture

- docs/configs/uchicago_ai_cluster.yaml
PR only updates the UChicago AI cluster config to use GCE. I've also updated the config with a commented out
config snippet to use a single GPU which the cluster docs recommend.
> Updating UChicago AI cluster config to use GCE

- docs/configs/bebop.yaml
Updates the Bebop example config to use GlobusComputeEngine.
> Add Bebop GCE config

- docs/configs/anvil.yaml
- docs/configs/delta.yaml
- docs/configs/faster.yaml
Story details: https://app.shortcut.com/globus/story/32323
> chore: [sc-32323] Update example configs to use GlobusComputeEngine

- compute_endpoint/packaging/JenkinsFile
- compute_endpoint/packaging/Makefile
Fine-tune which part does what; more correctitudes for the CI vs local builds.
> Working toward publishing builds

- docs/configuring.rst
Documentation section on GCE and various GCE-specific features like retries, container support, and auto-scaling.
> Adds new document section on GCE specific options

- compute_endpoint/globus_compute_endpoint/cli.py
> Unhide `configure --multi-user`

- docs/endpoints.rst
Ryan missed a spot - pipx was also in endpoint.rst
> include deps option added to Documentation - part deux

- compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
Never used from initial implementation.
> Remove unused assignment

- docs/changelog.rst
An oversight in our releaes during v2.20.0.  Whoops!
[sc-33868]
> Delineate changes from v2.20.0 and v2.21.0

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
> Warn if MEP user environment file is missing or empty

- local_dev/compose.yml
To prevent namespace collision with [the services](https://github.com/globusonline/funcx-services/pull/674)
> Rename local dev EP docker compose project

- docs/changelog.rst
> Merge adjacent `Changed` sections in changelog

- compute_endpoint/globus_compute_endpoint/self_diagnostic.py
- compute_endpoint/tests/unit/test_self_diagnostic.py
This ensures that diagnostic files include interchange and worker logs in addition to endpoint logs.
> Glob recursively in self diagnostic

- changelog.d/20240725_104852_yadudoc1729_mpi_functions_2.rst
- compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
- compute_sdk/globus_compute_sdk/__init__.py
- compute_sdk/globus_compute_sdk/sdk/mpi_function.py
- compute_sdk/globus_compute_sdk/sdk/shell_function.py
- compute_sdk/tests/unit/conftest.py
- compute_sdk/tests/unit/test_mpi_functions.py
- compute_sdk/tests/unit/test_shell_functions.py
- docs/mpi_functions.rst
- docs/reference/index.rst
- docs/reference/mpi_function.rst
- docs/shell_functions.rst
Support for `MPIFunctions` which extends `ShellFunctions`
[sc-32391]
> Support for MPIFunctions

- changelog.d/20240807_114300_30907815+rjmello_HEAD.rst
- changelog.d/20240807_183559_30907815+rjmello_gcengine_with_k8s_provider_sc_33870.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Merging release branch back to `main`.
> Bump versions and changelog for release v2.26.0

- RELEASING.md
Formalized a procedure for pushing alpha releases and related bug fixes.
[sc-35278]
> Add alpha release procedure to RELEASING.md

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
For these tests, the TaskQueueSubscriber is not under test; mock it away completely to avoid some spurious noise like:
...task_queue_subscriber.py:146 <TaskQueueSubscriber(TQS, started 132706721584704)> Unhandled exception: shutting down connection.
File "VENV/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py", line 142, in run
self._connection = self._connect()
^^^^^^^^^^^^^^^
File "VENV/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py", line 160, in _connect
pika_params = pika.URLParameters(self.queue_info["connection_url"])
~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'connection_url'
> Reduce test log noise

- compute_endpoint/tests/unit/test_config_utils.py
The default `Config()` instantiation creates a GlobusComputeEngine, which makes at least one DNS call.  There is no need for that given the purview of these tests, and, for more latent networks, this makes a big difference in test run time.
> Remove network lookup for rendering UTs

- compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
> Remove test-induced warning

- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Besides being more correct for the tests, also improve (slightly) test performance.
> Do not needlessly instantiate an Engine

- compute_endpoint/tests/unit/test_endpoint_unit.py
The test failed to add a mock response, and so was actually timing out a real network call&nbsp;&mdash;&nbsp;and not one of interest for the test.  Add missing mock, and also include a test-setup-verification assertion.
> Fix bit-rotted delete endpoint test

- docs/executor.rst
- docs/mpi_functions.rst
- docs/shell_functions.rst
With thanks to Christopher Harrop (NOAA) for the report.
> Correct docs

- changelog.d/20240909_171516_kevin_update_parsl.rst
- compute_endpoint/setup.py
- compute_endpoint/tests/unit/test_engines.py
- compute_endpoint/tests/unit/test_status_reporting.py
Update Parsl pin to `2024.9.9`
> Update Parsl to 2024.9.9

- compute_endpoint/globus_compute_endpoint/engines/process_pool.py
> Remove forgotten debugging log

- compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
Update `globus_app.py` to match `login_manager/manager.py`
> Release fix - Fix operator precedence in Jupyter checking

- compute_sdk/globus_compute_sdk/sdk/diagnostic.py
- compute_sdk/tests/unit/test_diagnostic.py
The previous self-diagnostic PR still prints the test headings to stdout, even when redirecting the actual output to compressed file, as a sort of 'progress bar so the user does not think it is stuck if slow tests are encountered'.
See attached screenshot for a sample.  
It was suggested that the highlighted headings aren't as necessary, so this adds a --verbose flag and puts those headings behind it.  Without headings, as each test's timeout is 15s, if the user runs diagnostics with no flags and presses Ctrl-C when after 20 seconds 'nothing is happening', there will be no indicator of what was stuck, as the test results are only in a memory buffer and only written to file at the end if all the tests finish.
Also now redirecting stderr as well as stdout in diagnostic output.
> Add --verbose flag for the new self-diagnostic and put heading output behind it

- changelog.d/20241004_101450_rchard_set_default_max_workers.rst
- docs/changelog.rst
> Use code-style formatting for link

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
The original thrust of the MEP work was that it was strictly for administrators.  After we realized that normal users would want templating as well, we updated the logic to be flexible by allowing `initgroups` to fail but still proceed to start the UEP.  But then we also included a check to only attempt to change the UID if it needed changing ... in practice, then, this should never fail because if `os.getuid() != new_uid` then the `os.getuid()` has the necessary privileges.
However, `initgroups()` is not a fungible action when changing the process persona, so take out the ambiguity by just letting it fail if [something happens].
In the same vein, implement a "paranoia" check that ensures that we *can't* get back the privileges.  If the kernel doesn't have our back, then we bail out right …
> Update initgroups thinking

- compute_sdk/tests/unit/test_executor.py
The underlying thread was not stopped, so whether the test passed was dependent on whether the test finished before the thread was scheduled.  Fix by turning off the thread and manually doing what queue item management.
> Fix flaky Executor test

- compute_endpoint/tests/unit/test_htex.py
These HTEX tests were temporarily skipped in good-faith, but the HTEX class is now deprecated.  It will be removed completely in the near future, so remove these now unused tests.
> Remove unused HTEX tests

- compute_endpoint/tests/conftest.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
- compute_endpoint/tests/unit/test_cli_behavior.py
- compute_endpoint/tests/unit/test_endpoint_unit.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
No sense in having multiple implementations of the same thing.
Reviewer: mildly tedious, but the same basic change throughout, so marking `quick-review`
> Remove a fixture duplication

- docs/endpoints/multi_user.rst
> Document auth caching implementation

- docs/endpoints/multi_user.rst
The biggest change is to upgrade the section on `allowed_functions` generally and following the recent tightening of that logic.  The rest of the changes are mostly reorganizations of the existing text.
[sc-34267]
> Touch up Security Posture section

- compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
> Correct formatting, add warning

- compute_endpoint/globus_compute_endpoint/engines/base.py
- compute_endpoint/tests/unit/test_reporting_period.py
Observed in CI recently; don't rely on `time.sleep()` and calculations against time.  Bonus: faster tests to boot.
- Test Bug fix (non-breaking change that fixes an issue)
> Address flaky test; remove use of time

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
There may be outstanding information in the process communication pipes (how Python implements multiprocessing.* communication avenues).  Let Python's APIs know that we don't care.  Clean up, please.
> Close resources with test subprocesses

- compute_sdk/globus_compute_sdk/sdk/client.py
Give more context and an example returned data structure in the method documentation.  While here and also updating the method signature, refactor the method implementation to use set-think, and hoist the if-condition out of the loop.
> Document Client.get_batch_status better

- docs/sdk.rst
> Format class names and links in documentation

- changelog.d/20241209_081322_30907815+rjmello_globus_sdk_compute_client_sc_36127.rst
- changelog.d/20241209_143843_30907815+rjmello_globus_sdk_compute_client_sc_36127.rst
- changelog.d/20250122_104738_yadudoc1729_update_parsl_version_req.rst
- changelog.d/20250127_162749_30907815+rjmello.rst
- changelog.d/20250206_125215_kevin_remove_obsolete_funcx_upgrade_code.rst
- changelog.d/20250207_160227_30907815+rjmello_fix_default_engine.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Bump versions for 3.1.0 production release
> Bump versions for release 3.1.0

- local_dev/compose.yaml
> Add python version as an argument to local dev docker compose file

- changelog.d/20250304_112138_ravescovi_add_podman.rst
- compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
- compute_endpoint/tests/unit/test_gce_container.py
- compute_sdk/globus_compute_sdk/sdk/client.py
- docs/endpoints/endpoints.rst
This PR extends the container support for podman container execution.
> Feature: add podman container support

- compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
- compute_endpoint/tests/unit/engine/test_globuscompute.py
- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
- compute_sdk/globus_compute_sdk/sdk/web_client.py
- compute_sdk/tests/unit/test_client.py
A follow-up to [the comment in PR #1821](https://github.com/globus/globus-compute/pull/1821#discussion_r1992143340)
> Add util.get_py_version_str() to SDK

- docs/reference/client.rst
- docs/sdk.rst
Motivated by a (friendly) user complaint, update this section to match the current implementation of Batch.
Also update a couple of interdoc references (Client, Executor).
> Update Batch user guide section

- changelog.d/20250320_223511_kevin_update_parsl.rst
- compute_endpoint/setup.py
> Update Parsl and Jinja

- changelog.d/20250325_154559_chris_strategylike.rst
- changelog.d/20250325_160052_chris_pure_source_combined.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Bump versions and collect changelog for release
> Bump versions and collect changelog for 3.5.0 release

- changelog.d/20250402_134420_kevin_update_parsl_pin.rst
- compute_endpoint/setup.py
> Update Parsl pin

- compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Based on scheduling, spt might be called an extra time; for purposes of test, we only care that about the first un-idling.
- Bug fix (flaky test fixup)
> Be more precise with test event collection

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
If the MEP is HA, the so is the UEP.  Full stop.
[sc-35488]
> Make MEP and UEP ha aligned

- compute_endpoint/tests/unit/test_engines.py
Test the *unit*, not the infrastructure.  Mock out what's not interesting in this context.
> Reduce test wait time

- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
This test appears to have worked by happenstance.  I think the ordering of the decorators was confused, as this was true:
assert mock_stop_endpoint._mock_name == "get_endpoint_id"
Meanwhile, the intended mock object of interest, `Client.stop_endpoint`, was not actually mocked.
Correct test implementation by ensuring that the _responses_ are checked (the context managers).
> Fix errant test

- compute_endpoint/globus_compute_endpoint/cli.py
- compute_endpoint/tests/unit/test_cli_behavior.py
See [sc-38688]
Add MFA flag when creating policies during Endpoint configuration.
Note that the original story used ``--auth-mfa-required`` but the PR uses ``--auth-policy-mfa-required`` to better align with the other auth policy parameters.
> Add MFA flag to policy creation when configuring Endpoint

- compute_endpoint/tests/unit/test_cli_behavior.py
> Remove unnecessary engine instantiation in tests

- compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
I suspect this was a vestigial thought-process or unintentional copy-pasta.  It is unused now, so remove it.
> Remove unused event

- changelog.d/20250506_185402_chris_update_gare_handler.rst
- compute_sdk/globus_compute_sdk/sdk/utils/gare.py
- compute_sdk/setup.py
> Bump Globus SDK for cleaner GARE handler

- compute_sdk/globus_compute_sdk/sdk/executor.py
- compute_sdk/tests/unit/test_executor.py
A minor refactor for clarity in an upcoming PR.
> Decouple task collection from group reload

- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/tests/unit/test_client.py
At this time, the Globus SDK provides no protection against concurrent use of the internal request pool.  This implementation still does not prevent a user from directly accessing the underlying request routines&nbsp;&mdash;&nbsp;that would best be done within the Globus SDK&nbsp;&mdash;&nbsp;but at least guards access via the Client's interface.
Reviewer: this PR pulls out a commit from the currently-proposed #1880.  I will wait to merge #1880 until this PR lands.  Meanwhile, I marked this `quick-review` because the thrust of this change is simply:
```diff
- api_call(...)
+ with self._request_lock:
+     api_call(...)
```
(and possibly the test to verify the change).
[sc-39660]
- Bug fix (an edge-case that I'm not clear anyone has yet encountered, but important for #1880 assurances)
> Lock-guard all client requests

- compute_sdk/globus_compute_sdk/sdk/client.py
- compute_sdk/tests/unit/test_client.py
[[sc-38692]](https://app.shortcut.com/globus/story/38692/warn-users-that-they-need-to-be-covered-under-baa-for-a-given-institution-when-submitting-pii)
> Display any HA warnings supplied by the services

- compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
With thanks to @lgorenstein for the find.
> Update serialization mismatch warning url

- compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
- compute_endpoint/tests/unit/test_endpointmanager_unit.py
Just use the static method directly.
> Minor test refactor

- smoke_tests/Makefile
- smoke_tests/tests/conftest.py
In particular, use `local_compute_services` flag.
> Update smoketest for local runs

- changelog.d/20250916_144323_30907815+rjmello_bump_parsl_2025_09_15.rst
- changelog.d/20250916_151835_30907815+rjmello_python_mismatch_sc_31360.rst
- changelog.d/20250919_102327_kevin_two_instances_of_same_ep_fix.rst
- compute_endpoint/globus_compute_endpoint/version.py
- compute_endpoint/setup.py
- compute_sdk/globus_compute_sdk/version.py
- docs/changelog.rst
Bump versions and collect change-log since 3.14.0
> Bump versions and collect change-log for release 3.15.0

- compute_sdk/tests/unit/test_shell_functions.py
Pytest will not clean up environment variables set with `os.environ`, so I've updated a few tests to use `monkeypatch` instead.
> Make ShellFunction test environment vars ephemeral
